#!/usr/bin/env python3
"""Generate deterministic metamorphic/property probes for Eshkol.

Each trial is seeded by its case index through an explicit xorshift64* PRNG.
The generated programs contain no runtime randomness; rerunning this generator
with the same arguments reproduces the corpus byte-for-byte.
"""

import argparse
import math
from pathlib import Path


MASK = (1 << 64) - 1
DEFAULT_TRIALS = 32


class Rng:
    def __init__(self, case_index):
        self.state = (0x9E3779B97F4A7C15 ^ ((case_index + 1) * 0xD1B54A32D192ED03)) & MASK

    def next_u64(self):
        x = self.state
        x ^= (x >> 12) & MASK
        x ^= (x << 25) & MASK
        x ^= (x >> 27) & MASK
        self.state = x & MASK
        return (self.state * 0x2545F4914F6CDD1D) & MASK

    def randint(self, lo, hi):
        return lo + (self.next_u64() % (hi - lo + 1))

    def choice(self, items):
        return items[self.randint(0, len(items) - 1)]


def esk_string(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == "\"":
            out.append("\\\"")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def lst(values):
    if not values:
        return "'()"
    return "(list " + " ".join(str(v) for v in values) + ")"


def str_lit(rng):
    alphabet = "abcXYZ019_-"
    n = rng.randint(0, 8)
    return "".join(rng.choice(alphabet) for _ in range(n))


def ints(rng, n=None, lo=-9, hi=9):
    if n is None:
        n = rng.randint(0, 7)
    return [rng.randint(lo, hi) for _ in range(n)]


def header(title, trials, laws):
    lines = [
        ";; Generated by tests/metamorphic/gen_metamorphic.py -- DO NOT EDIT",
        f";; FAMILY: {title}",
        f";; TRIALS: {trials}",
        ";; LAWS: " + ", ".join(laws),
        "",
        "(require stdlib)",
        "",
        "(define metamorphic-passed 0)",
        "(define metamorphic-failed 0)",
        "(define metamorphic-xknown 0)",
        "",
        "(define (metamorphic-check name ok counterexample)",
        "  (if ok",
        "      (begin",
        "        (set! metamorphic-passed (+ metamorphic-passed 1))",
        "        (display \"PASS: \") (display name) (newline))",
        "      (begin",
        "        (set! metamorphic-failed (+ metamorphic-failed 1))",
        "        (display \"FAIL: \") (display name)",
        "        (display \" counterexample=\") (display counterexample)",
        "        (newline))))",
        "",
        "(define (metamorphic-xknown! name task counterexample)",
        "  (set! metamorphic-xknown (+ metamorphic-xknown 1))",
        "  (display \"XKNOWN: \") (display name)",
        "  (display \" task=\") (display task)",
        "  (display \" counterexample=\") (display counterexample)",
        "  (newline))",
        "",
    ]
    return lines


def footer(family, trials, laws):
    return [
        "",
        "(display \"METAMORPHIC-SUMMARY family=" + family +
        " laws=" + str(len(laws)) + " trials=" + str(trials) +
        " passed=\") (display metamorphic-passed)",
        "(display \" failed=\") (display metamorphic-failed)",
        "(display \" xknown=\") (display metamorphic-xknown) (newline)",
    ]


def emit_check(lines, name, expr, counterexample):
    lines.append(f"(metamorphic-check {esk_string(name)} {expr} {esk_string(counterexample)})")


def gen_list_vector(trials):
    laws = [
        "reverse-reverse=id",
        "length-append additivity",
        "map fusion",
        "append associativity",
        "list<->vector roundtrip",
    ]
    lines = header("list-vector", trials, laws)
    for i in range(trials):
        rng = Rng(i)
        a = ints(rng)
        b = ints(rng)
        c = ints(rng)
        l_a, l_b, l_c = lst(a), lst(b), lst(c)
        f_mul, f_add = rng.randint(-4, 4), rng.randint(-5, 5)
        g_mul, g_add = rng.randint(-4, 4), rng.randint(-5, 5)
        f = f"(lambda (x) (+ (* {f_mul} x) {f_add}))"
        g = f"(lambda (x) (+ (* {g_mul} x) {g_add}))"
        fg = f"(lambda (x) ({f} ({g} x)))"
        cex = f"case={i} a={a} b={b} c={c}"
        emit_check(lines, f"list.reverse_reverse.case{i}",
                   f"(equal? (reverse (reverse {l_a})) {l_a})", cex)
        emit_check(lines, f"list.length_append.case{i}",
                   f"(= (length (append {l_a} {l_b})) (+ (length {l_a}) (length {l_b})))", cex)
        emit_check(lines, f"list.map_fusion.case{i}",
                   f"(equal? (map {f} (map {g} {l_a})) (map {fg} {l_a}))",
                   cex + f" f=(*{f_mul})+{f_add} g=(*{g_mul})+{g_add}")
        emit_check(lines, f"list.append_assoc.case{i}",
                   f"(equal? (append (append {l_a} {l_b}) {l_c}) (append {l_a} (append {l_b} {l_c})))",
                   cex)
        emit_check(lines, f"vector.list_vector_roundtrip.case{i}",
                   f"(equal? (vector->list (list->vector {l_a})) {l_a})", cex)
    lines.extend(footer("list-vector", trials, laws))
    return "\n".join(lines) + "\n"


def gen_sorting(trials):
    laws = ["sort idempotent", "sort permutation", "sort ordered"]
    lines = header("sorting", trials, laws)
    lines.extend([
        "(define (metamorphic-ordered? xs)",
        "  (if (or (null? xs) (null? (cdr xs)))",
        "      #t",
        "      (and (<= (car xs) (cadr xs)) (metamorphic-ordered? (cdr xs)))))",
        "",
        "(define (metamorphic-count x xs)",
        "  (if (null? xs)",
        "      0",
        "      (+ (if (= x (car xs)) 1 0) (metamorphic-count x (cdr xs)))))",
        "",
        "(define (metamorphic-same-bag? xs ys)",
        "  (and (= (length xs) (length ys))",
        "       (let loop ((rest xs))",
        "         (if (null? rest)",
        "             #t",
        "             (and (= (metamorphic-count (car rest) xs)",
        "                     (metamorphic-count (car rest) ys))",
        "                  (loop (cdr rest)))))))",
        "",
    ])
    for i in range(trials):
        rng = Rng(i)
        values = ints(rng, n=rng.randint(0, 9), lo=-6, hi=6)
        expr = lst(values)
        sorted_expr = f"(sort {expr} <)"
        cex = f"case={i} xs={values}"
        emit_check(lines, f"sort.idempotent.case{i}",
                   f"(equal? (sort {sorted_expr} <) {sorted_expr})", cex)
        emit_check(lines, f"sort.permutation.case{i}",
                   f"(metamorphic-same-bag? {expr} {sorted_expr})", cex)
        emit_check(lines, f"sort.ordered.case{i}",
                   f"(metamorphic-ordered? {sorted_expr})", cex)
    lines.extend(footer("sorting", trials, laws))
    return "\n".join(lines) + "\n"


def norm_rat(n, d):
    if d < 0:
        n, d = -n, -d
    g = math.gcd(abs(n), abs(d))
    return n // g, d // g


def gen_numeric(trials):
    laws = [
        "commutativity exact",
        "associativity exact",
        "distributivity exact",
        "rational numerator/denominator",
        "expt addition law",
        "gcd/lcm product law",
        "min+max=a+b",
    ]
    lines = header("numeric", trials, laws)
    for i in range(trials):
        rng = Rng(i)
        a, b, c = rng.randint(-20, 20), rng.randint(-20, 20), rng.randint(-20, 20)
        base = rng.randint(1, 7)
        m, n = rng.randint(0, 6), rng.randint(0, 6)
        g1, g2 = rng.randint(1, 80), rng.randint(1, 80)
        rn = rng.randint(-50, 50)
        rd = rng.choice([d for d in range(-17, 18) if d != 0])
        nn, dd = norm_rat(rn, rd)
        cex = f"case={i} a={a} b={b} c={c} base={base} m={m} n={n} rational={rn}/{rd}"
        emit_check(lines, f"numeric.commutative_add.case{i}", f"(= (+ {a} {b}) (+ {b} {a}))", cex)
        emit_check(lines, f"numeric.commutative_mul.case{i}", f"(= (* {a} {b}) (* {b} {a}))", cex)
        emit_check(lines, f"numeric.associative_add.case{i}",
                   f"(= (+ (+ {a} {b}) {c}) (+ {a} (+ {b} {c})))", cex)
        emit_check(lines, f"numeric.associative_mul.case{i}",
                   f"(= (* (* {a} {b}) {c}) (* {a} (* {b} {c})))", cex)
        emit_check(lines, f"numeric.distributive.case{i}",
                   f"(= (* {a} (+ {b} {c})) (+ (* {a} {b}) (* {a} {c})))", cex)
        emit_check(lines, f"numeric.rational_num_denom.case{i}",
                   f"(and (= (numerator (/ {rn} {rd})) {nn}) (= (denominator (/ {rn} {rd})) {dd}))",
                   cex + f" normalized={nn}/{dd}")
        emit_check(lines, f"numeric.expt_addition.case{i}",
                   f"(= (expt {base} (+ {m} {n})) (* (expt {base} {m}) (expt {base} {n})))",
                   cex)
        emit_check(lines, f"numeric.gcd_lcm.case{i}",
                   f"(= (* (gcd {g1} {g2}) (lcm {g1} {g2})) (abs (* {g1} {g2})))",
                   cex + f" gcd_lcm_inputs={g1},{g2}")
        emit_check(lines, f"numeric.min_max_sum.case{i}",
                   f"(= (+ (min {a} {b}) (max {a} {b})) (+ {a} {b}))", cex)
    lines.extend(footer("numeric", trials, laws))
    return "\n".join(lines) + "\n"


def exact_number_expr(rng):
    if rng.randint(0, 2) == 0:
        return str(rng.randint(-5000, 5000))
    n = rng.randint(-99, 99)
    d = rng.choice([2, 3, 4, 5, 7, 8, 9, 11])
    return f"(/ {n} {d})"


def gen_string_char(trials):
    laws = [
        "list<->string roundtrip",
        "substring-whole=id",
        "number->string->number exact",
    ]
    lines = header("string-char", trials, laws)
    for i in range(trials):
        rng = Rng(i)
        s = str_lit(rng)
        se = esk_string(s)
        num = exact_number_expr(rng)
        cex = f"case={i} s={s!r} n={num}"
        emit_check(lines, f"string.list_string_roundtrip.case{i}",
                   f"(string=? (list->string (string->list {se})) {se})", cex)
        emit_check(lines, f"string.substring_whole.case{i}",
                   f"(string=? (substring {se} 0 (string-length {se})) {se})", cex)
        emit_check(lines, f"number.string_number_roundtrip_exact.case{i}",
                   f"(and (exact? (string->number (number->string {num}))) (= (string->number (number->string {num})) {num}))",
                   cex)
    lines.extend(footer("string-char", trials, laws))
    return "\n".join(lines) + "\n"


def gen_roundtrip_control(trials):
    laws = [
        "write then read=id",
        "tensor save/load",
        "call/cc identity",
        "apply/map consistency",
        "apply/sum consistency",
        "values roundtrip",
    ]
    lines = header("roundtrip-control", trials, laws)
    lines.extend([
        "(define (metamorphic-sum xs)",
        "  (if (null? xs) 0 (+ (car xs) (metamorphic-sum (cdr xs)))))",
        "",
    ])
    for i in range(trials):
        rng = Rng(i)
        x, y, z = rng.randint(-50, 50), rng.randint(-50, 50), rng.randint(-50, 50)
        xs = ints(rng, n=rng.randint(0, 6), lo=-12, hi=12)
        delta = rng.randint(-10, 10)
        tvals = [rng.randint(-8, 8) + 0.5 for _ in range(3)]
        tensor_expr = "(tensor " + " ".join(str(v) for v in tvals) + ")"
        path = f"/tmp/eshkol-metamorphic-tensor-{i}.bin"
        cex = f"case={i} x={x} y={y} z={z} xs={xs} delta={delta} tensor={tvals}"
        lines.append(f"(define metamorphic-roundtrip-value-{i} (list {x} \"case-{i}\\nvalue\" 'roundtrip-symbol {lst(xs)}))")
        lines.append(f"(define metamorphic-roundtrip-port-{i} (open-output-string))")
        lines.append(f"(write metamorphic-roundtrip-value-{i} metamorphic-roundtrip-port-{i})")
        lines.append(f"(define metamorphic-roundtrip-text-{i} (get-output-string metamorphic-roundtrip-port-{i}))")
        emit_check(lines, f"roundtrip.write_read.case{i}",
                   f"(equal? (read (open-input-string metamorphic-roundtrip-text-{i})) metamorphic-roundtrip-value-{i})",
                   cex)
        emit_check(lines, f"control.callcc_identity.case{i}",
                   f"(= (call/cc (lambda (k) {x})) {x})", cex)
        emit_check(lines, f"control.apply_map_consistency.case{i}",
                   f"(equal? (map (lambda (v) (apply + (list v {delta}))) {lst(xs)}) (map (lambda (v) (+ v {delta})) {lst(xs)}))",
                   cex)
        emit_check(lines, f"control.apply_sum.case{i}",
                   f"(= (apply + {lst(xs)}) (metamorphic-sum {lst(xs)}))", cex)
        emit_check(lines, f"control.values_roundtrip.case{i}",
                   f"(equal? (let-values (((a b c) (values {x} {y} {z}))) (list a b c)) (list {x} {y} {z}))",
                   cex)
        lines.append(f"(define metamorphic-tensor-{i} {tensor_expr})")
        lines.append(f"(define metamorphic-tensor-save-ok-{i} (tensor-save {esk_string(path)} metamorphic-tensor-{i}))")
        lines.append(f"(define metamorphic-tensor-loaded-{i} (tensor-load {esk_string(path)}))")
        tensor_ok = (
            f"(and metamorphic-tensor-save-ok-{i} (tensor? metamorphic-tensor-loaded-{i}) "
            f"(= (tensor-ref metamorphic-tensor-loaded-{i} 0) {tvals[0]}) "
            f"(= (tensor-ref metamorphic-tensor-loaded-{i} 1) {tvals[1]}) "
            f"(= (tensor-ref metamorphic-tensor-loaded-{i} 2) {tvals[2]}))"
        )
        emit_check(lines, f"roundtrip.tensor_save_load.case{i}", tensor_ok, cex + f" path={path}")
    lines.extend(footer("roundtrip-control", trials, laws))
    return "\n".join(lines) + "\n"


GENERATORS = [
    ("metamorphic_list_vector.esk", gen_list_vector),
    ("metamorphic_sorting.esk", gen_sorting),
    ("metamorphic_numeric.esk", gen_numeric),
    ("metamorphic_string_char.esk", gen_string_char),
    ("metamorphic_roundtrip_control.esk", gen_roundtrip_control),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="tests/metamorphic/generated")
    ap.add_argument("--trials", type=int, default=DEFAULT_TRIALS)
    args = ap.parse_args()

    if args.trials <= 0:
        raise SystemExit("--trials must be positive")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    manifest = [
        "# Generated by tests/metamorphic/gen_metamorphic.py -- DO NOT EDIT",
        f"trials={args.trials}",
        "prng=xorshift64star seeded by case index",
        "",
    ]
    for filename, generator in GENERATORS:
        text = generator(args.trials)
        (outdir / filename).write_text(text, encoding="utf-8")
        manifest.append(filename)
    (outdir / "MANIFEST.txt").write_text("\n".join(manifest) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
