#!/usr/bin/env bash
# gen_stress_sources.sh — deterministically regenerate the large stress-corpus
# sources that are too big / too mechanical to commit verbatim.
#
# Output: tests/stress/generated/*.esk  (gitignored; scripts/run_stress.sh
# invokes this before running the sweep).
#
# Every generator is deterministic: same script -> byte-identical sources.
set -eu
cd "$(dirname "$0")"
mkdir -p generated

# ── parser_nested_parens_10k.esk ─────────────────────────────────────────────
# 10,000-deep nested arithmetic expression. Exercises parser recursion depth
# and codegen of a 10k-deep expression tree. Expected value: 10000.
perl -e '
  print "; generated by gen_stress_sources.sh - 10k-deep nested parens\n";
  print "(display \"OK \")\n(display ";
  print "(+ 1 " x 10000; print "0"; print ")" x 10000;
  print ")\n(newline)\n"' > generated/parser_nested_parens_10k.esk

# ── parser_quoted_list_10k.esk ───────────────────────────────────────────────
# One quoted literal list of 10,000 elements. Exercises the reader/quote
# path (not cons-by-cons construction). list-ref proves the tail survived.
perl -e '
  print "; generated by gen_stress_sources.sh - 10k-element quoted list\n";
  print "(require stdlib)\n";
  print "(define big-quoted (quote ("; print join(" ", 0..9999); print ")))\n";
  print "(display \"OK \")\n(display (list-ref big-quoted 9999))\n(newline)\n"
' > generated/parser_quoted_list_10k.esk

# ── parser_defines_1mb.esk ───────────────────────────────────────────────────
# ~1 MB source file of 32,000 top-level defines. Exercises parser/codegen
# throughput and per-define symbol-table growth on a single translation unit.
perl -e '
  print "; generated by gen_stress_sources.sh - 1MB of top-level defines\n";
  my $n = 32000;
  for my $i (0 .. $n - 1) {
    printf "(define stress-generated-var-%05d %d)\n", $i, $i;
  }
  print "(display \"OK \")\n";
  print "(display (+ stress-generated-var-31999 stress-generated-var-00001))\n";
  print "(newline)\n"' > generated/parser_defines_1mb.esk

# ── parser_quasiquote_deep.esk ───────────────────────────────────────────────
# SINGLE-LEVEL quasiquote whose template is a 1000-deep nested list with an
# unquote at the innermost position: `(1 (2 (3 ... (,(+ 500 500)) ...))).
# A TCO walker descends 999 cdr/car steps to recover the innermost value.
# (Nested multi-level quasiquote is broken today - see found/nested_quasiquote.esk.)
perl -e '
  print "; generated by gen_stress_sources.sh - 1000-deep quasiquote template\n";
  my $d = 999;
  my $expr = "(quasiquote ";
  $expr .= "($_ " for (1 .. $d);
  $expr .= "((unquote (+ 500 500)))";
  $expr .= ")" x $d;
  $expr .= ")";
  print "(define deep-qq $expr)\n";
  print <<"EOT";
(define (descend x n)
  (if (= n 0)
      (car x)
      (descend (car (cdr x)) (- n 1))))
(display "OK ")
(display (car (descend deep-qq $d)))
(newline)
EOT
' > generated/parser_quasiquote_deep.esk

# ── path_nested_lets_1000.esk ────────────────────────────────────────────────
# 1000 syntactically nested lets; innermost expression references both the
# outermost and innermost binding. Expected: 1 + 1000 = 1001.
perl -e '
  print "; generated by gen_stress_sources.sh - 1000 nested lets\n";
  print "(display \"OK \")\n(display ";
  print "(let ((x$_ $_)) " for (1 .. 1000);
  print "(+ x1 x1000)"; print ")" x 1000;
  print ")\n(newline)\n"' > generated/path_nested_lets_1000.esk

# ── path_identifier_10k.esk ──────────────────────────────────────────────────
# A single identifier of length 10,000, defined and referenced.
perl -e '
  print "; generated by gen_stress_sources.sh - 10k-char identifier\n";
  my $id = "a" x 10000;
  print "(define $id 42)\n(display \"OK \")\n(display $id)\n(newline)\n"
' > generated/path_identifier_10k.esk

echo "gen_stress_sources.sh: $(ls generated/*.esk | wc -l | tr -d ' ') generated sources in tests/stress/generated/"
