#!/usr/bin/env python3
"""Generate tests/ad/taylor_integral_family_test.esk (SW-210).

The expected values are closed-form derivatives from sympy, evaluated to 30
digits and printed at double precision. Re-run after changing the sweep:

    python3 tests/ad/gen_taylor_integral_family_test.py > tests/ad/taylor_integral_family_test.esk
"""
import sympy as sp

x, y = sp.symbols("x y")
UNARY = [
    ("asin", sp.asin(x), "0.3"), ("acos", sp.acos(x), "0.3"),
    ("atan", sp.atan(x), "0.7"), ("asinh", sp.asinh(x), "0.6"),
    ("acosh", sp.acosh(x), "1.7"), ("atanh", sp.atanh(x), "0.4"),
    ("log2", sp.log(x, 2), "1.3"), ("log10", sp.log(x, 10), "1.3"),
    ("exp2", 2**x, "0.5"), ("cbrt", sp.root(x, 3), "2.0"),
]
# cbrt of a negative point is the real cube root.
NEG_CBRT = (-sp.root(-x, 3), "-3.0")
ATAN2 = [  # (label, expression in x, body, point)
    ("atan2 in y, |x|>=|y|", sp.atan2(x, sp.Rational(2)), "(atan x 2.0)", "0.5"),
    ("atan2 in y, |y|>|x|", sp.atan2(x, sp.Rational(3, 10)), "(atan x 0.3)", "1.0"),
    ("atan2 in x, left half", sp.atan2(sp.Rational(1, 2), x), "(atan 0.5 x)", "-1.5"),
    ("atan2 procedure", sp.atan2(x, -sp.Rational(1, 4)), "(atan2 x -0.25)", "0.8"),
]


def val(expr, point):
    return sp.N(expr.subs(x, sp.Rational(point)), 30)


def lit(v):
    return repr(float(v))


out = []
emit = out.append
emit(";; SW-210 regression: the integral family of unary numeric builtins on")
emit(";; Taylor carriers. Generated by tests/ad/gen_taylor_integral_family_test.py")
emit(";; from sympy closed forms; do not edit the expected values by hand.")
emit("(define failures 0)")
emit("(define checks 0)")
emit("(define (check name got expected)")
emit("  (set! checks (+ checks 1))")
emit("  (if (and (number? got)")
emit("           (<= (abs (- got expected)) (+ 1e-12 (* 1e-9 (abs expected)))))")
emit("      #t")
emit("      (begin (set! failures (+ failures 1))")
emit("             (display \"FAIL: \") (display name) (display \" got \")")
emit("             (write got) (display \" want \") (write expected) (newline))))")
emit("(define (check-exact name got expected)")
emit("  (set! checks (+ checks 1))")
emit("  (if (and (exact? got) (= got expected))")
emit("      #t")
emit("      (begin (set! failures (+ failures 1))")
emit("             (display \"FAIL: \") (display name) (display \" got \")")
emit("             (write got) (display \" want exact \") (write expected) (newline))))")
emit("")
emit(";; Orders 1-5 of every function through the classic tower, the same orders")
emit(";; with the pass nested inside and around a first-order `derivative` (the")
emit(";; level carrier and the reverse-seed dual tower), and the Taylor list.")
rows = UNARY + [("cbrt", NEG_CBRT[0], NEG_CBRT[1])]
for name, f, p in rows:
    for k in range(1, 6):
        want = lit(val(sp.diff(f, x, k), p))
        emit(f'(check "{name} d{k} at {p}" (derivative-n {name} {p} {k}) {want})')
        emit(f'(check "{name} d{k} lambda at {p}" (derivative-n (lambda (x) ({name} x)) {p} {k}) {want})')
    for k in range(1, 5):
        want = lit(val(sp.diff(f, x, k + 1), p))
        emit(f'(check "{name} level d{k} of d1 at {p}" '
             f'(derivative-n (lambda (x) (derivative {name} x)) {p} {k}) {want})')
        emit(f'(check "{name} d1 of d{k} at {p}" '
             f'(derivative (lambda (x) (derivative-n {name} x {k})) {p}) {want})')
    coeffs = [lit(val(sp.diff(f, x, k), p) / sp.factorial(k)) for k in range(0, 4)]
    emit(f'(define tc (taylor {name} {p} 3))')
    for k, c in enumerate(coeffs):
        emit(f'(check "{name} taylor c{k} at {p}" (list-ref tc {k}) {c})')
for label, f, body, p in ATAN2:
    for k in range(1, 6):
        want = lit(val(sp.diff(f, x, k), p))
        emit(f'(check "{label} d{k}" (derivative-n (lambda (x) {body}) {p} {k}) {want})')
    for k in range(1, 4):
        want = lit(val(sp.diff(f, x, k + 1), p))
        emit(f'(check "{label} level d{k} of d1" '
             f'(derivative-n (lambda (x) (derivative (lambda (x) {body}) x)) {p} {k}) {want})')

emit("")
emit(";; The review's cases.")
a = sp.symbols("a")
emit('(check "nested d1 of atan as a level" '
     '(derivative-n (lambda (a) (* a (derivative atan 1.0))) 2.0 1) 0.5)')
emit('(check "atan d2 at 1.0" (derivative-n atan 1.0 2) -0.5)')
emit('(check "atan d3 lambda at 0.5" (derivative-n (lambda (x) (atan x)) 0.5 3) -0.256)')
mixed = sp.diff(sp.diff(sp.atan(a * x), x, 2), a).subs({a: sp.Rational(3, 2), x: sp.Rational(1, 2)})
emit(f'(check "d/da of atan(a x) d2" (derivative (lambda (a) (derivative-n (lambda (x) (atan (* a x))) 0.5 2)) 1.5) {lit(sp.N(mixed, 30))})')
mixed2 = sp.diff(sp.diff(sp.atan2(x, a), x), a).subs({a: sp.Rational(3, 2), x: sp.Rational(1, 2)})
emit(f'(check "nested jets through atan2" (derivative (lambda (a) (derivative (lambda (x) (atan x a)) 0.5)) 1.5) {lit(sp.N(mixed2, 30))})')

emit("")
emit(";; Exact inputs stay exact where every coefficient is rational.")
emit(f'(check-exact "atan d3 at exact 0" (derivative-n atan 0 3) {sp.diff(sp.atan(x), x, 3).subs(x, 0)})')
emit(f'(check-exact "atanh d3 at exact 0" (derivative-n atanh 0 3) {sp.diff(sp.atanh(x), x, 3).subs(x, 0)})')
emit(f'(check-exact "cbrt d3 at exact 8" (derivative-n cbrt 8 3) {sp.diff(sp.root(x, 3), x, 3).subs(x, 8)})')
emit(f'(check-exact "cbrt d2 at exact -27" (derivative-n cbrt -27 2) {sp.simplify(sp.diff(-sp.root(-x, 3), x, 2).subs(x, -27))})')
emit('(check-exact "floor d2 at 5/2" (derivative-n floor 5/2 2) 0)')
emit('(check-exact "floor d0 at 5/2" (derivative-n floor 5/2 0) 2)')
emit('(check-exact "round d0 at 5/2" (derivative-n round 5/2 0) 2)')
emit('(check-exact "exp2 d0 at 3" (derivative-n exp2 3 0) 8)')
emit('(check-exact "log2 d0 at 8" (derivative-n log2 8 0) 3)')
mixed_exact = sp.diff(sp.diff(sp.atan(a * x), x, 2), a).subs({a: sp.Rational(3, 2), x: sp.Rational(1, 2)})
emit(f'(check-exact "level keeps the exact tail" (derivative (lambda (a) (derivative-n (lambda (x) (atan (* a x))) 1/2 2)) 3/2) {mixed_exact})')

emit("")
emit(";; SW-222: poles. A simple pole reaches the closed form's IEEE infinity at")
emit(";; every order; a pole of higher order than the seed stays NaN.")
emit("(define (check-ieee name got want)")
emit("  (set! checks (+ checks 1))")
emit("  (if (and (number? got) (if (nan? want) (nan? got) (= got want)))")
emit("      #t")
emit("      (begin (set! failures (+ failures 1))")
emit("             (display \"FAIL: \") (display name) (display \" got \")")
emit("             (write got) (display \" want \") (write want) (newline))))")
emit("(define +inf (/ 1.0 0.0))")
emit("(define -inf (/ -1.0 0.0))")
emit("(define nan (- +inf +inf))")
for label, expr, want in [
    ("1/x d2 at 0", "(derivative-n (lambda (x) (/ 1.0 x)) 0.0 2)", "+inf"),
    ("1/x d3 at 0", "(derivative-n (lambda (x) (/ 1.0 x)) 0.0 3)", "-inf"),
    ("1/x d2 at -0.0", "(derivative-n (lambda (x) (/ 1.0 x)) -0.0 2)", "-inf"),
    ("1/x nested jets at 0", "(derivative (lambda (x) (derivative (lambda (y) (/ 1.0 y)) x)) 0.0)", "+inf"),
    ("1/x^2 jet at 0 (double pole)", "(derivative (lambda (x) (/ 1.0 (* x x))) 0.0)", "nan"),
    ("1/x^2 d1 at 0 (double pole)", "(derivative-n (lambda (x) (/ 1.0 (* x x))) 0.0 1)", "nan"),
    ("cbrt d1 at exact 0", "(derivative-n cbrt 0 1)", "+inf"),
    ("cbrt d1 at 0.0", "(derivative-n cbrt 0.0 1)", "+inf"),
    ("cbrt d2 at 0.0", "(derivative-n cbrt 0.0 2)", "-inf"),
    ("cbrt jet at 0.0", "(derivative cbrt 0.0)", "+inf"),
]:
    emit(f'(check-ieee "{label}" {expr} {want})')

emit("")
emit(";; The rounding functions are constant between their jumps.")
for name in ["floor", "ceiling", "truncate", "round"]:
    for k in (1, 2, 3):
        emit(f'(check "{name} d{k} at 1.3" (derivative-n {name} 1.3 {k}) 0.0)')
    emit(f'(check "{name} level at 1.3" (derivative-n (lambda (x) (* x ({name} x))) 1.3 2) 0.0)')

emit("")
emit("(if (= failures 0)")
emit("    (begin (display \"PASS: taylor_integral_family \") (display checks) (newline))")
emit("    (begin (display \"FAIL: \") (display failures) (display \" of \") (display checks) (newline)))")
print("\n".join(out))
