#!/usr/bin/env python3
"""Generate tests/ad/complex_carrier_math_test.esk (SW-211).

Every complex procedure with a plain complex kernel, and `expt`, applied to a
complex value that carries a derivative, against sympy closed forms:

    python3 tests/ad/gen_complex_carrier_math_test.py > tests/ad/complex_carrier_math_test.esk
"""
import sympy as sp

x = sp.symbols("x")
I = sp.I
P1 = (sp.Rational(1), sp.Rational(1))           # 1+1i
P2 = (sp.Rational(1, 2), sp.Rational(2, 5))     # 0.5+0.4i, away from every cut
FUNCS = [
    ("exp", sp.exp(x), P1), ("exp2", 2**x, P1), ("log", sp.log(x), P1),
    ("log2", sp.log(x) / sp.log(2), P1), ("log10", sp.log(x) / sp.log(10), P1),
    ("sqrt", sp.sqrt(x), P1), ("sin", sp.sin(x), P1), ("cos", sp.cos(x), P1),
    ("tan", sp.tan(x), P2), ("sinh", sp.sinh(x), P1), ("cosh", sp.cosh(x), P1),
    ("tanh", sp.tanh(x), P2), ("asin", sp.asin(x), P2), ("acos", sp.acos(x), P2),
    ("atan", sp.atan(x), P2), ("asinh", sp.asinh(x), P2), ("acosh", sp.acosh(x), P1),
    ("atanh", sp.atanh(x), P2),
]
EXPT = [  # body in w, sympy expression
    ("(expt w 3)", x**3), ("(expt w -2)", x**-2), ("(expt w 0)", x**0),
    ("(expt w 2.5)", x**sp.Rational(5, 2)), ("(expt 2 w)", 2**x),
    ("(expt w (make-rectangular 0.5 1.0))", sp.exp((sp.Rational(1, 2) + I) * sp.log(x))),
]


def lit(v):
    return repr(float(v))


def z(p):
    return f"(make-rectangular {lit(p[0])} {lit(p[1])})"


def at(expr, p):
    v = complex(sp.N(expr.subs(x, p[0] + I * p[1]), 30))
    return lit(v.real), lit(v.imag)


out = []
emit = out.append
emit(";; SW-211 regression: complex `expt`, `log`, `angle` and every complex")
emit(";; procedure with a plain complex kernel keep the derivative a complex")
emit(";; value carries. Generated by tests/ad/gen_complex_carrier_math_test.py.")
emit("(define failures 0)")
emit("(define checks 0)")
emit("(define (close? got expected)")
emit("  (<= (abs (- got expected)) (+ 1e-12 (* 1e-9 (abs expected)))))")
emit("(define (check-z name got r i)")
emit("  (set! checks (+ checks 1))")
emit("  (if (and (number? got) (close? (real-part got) r) (close? (imag-part got) i))")
emit("      #t")
emit("      (begin (set! failures (+ failures 1))")
emit("             (display \"FAIL: \") (display name) (display \" got \") (write got)")
emit("             (display \" want \") (write r) (display \" \") (write i) (newline))))")
emit("")
emit(";; The review's cases.")
emit('(check-z "d1 of w^3 at 1+1i" (derivative (lambda (w) (expt w 3)) (make-rectangular 1 1)) 0.0 6.0)')
emit('(check-z "derivative-n log at 1+1i" (derivative-n log (make-rectangular 1 1) 1) 0.5 -0.5)')
emit('(check-z "angle along the real axis" (derivative (lambda (t) (angle (make-rectangular t 1.0))) 1.0) -0.5 0.0)')
emit('(check-z "angle along the imaginary axis" (derivative (lambda (t) (angle (make-rectangular 1.0 t))) 1.0) 0.5 0.0)')
emit("")
for name, f, p in FUNCS:
    for k in (1, 2, 3):
        r, i = at(sp.diff(f, x, k), p)
        emit(f'(check-z "{name} d{k}" (derivative-n {name} {z(p)} {k}) {r} {i})')
    r, i = at(sp.diff(f, x), p)
    emit(f'(check-z "{name} jet d1" (derivative (lambda (w) ({name} w)) {z(p)}) {r} {i})')
    r, i = at(sp.diff(f, x, 2), p)
    emit(f'(check-z "{name} nested d1 of d1" '
         f'(derivative (lambda (v) (derivative (lambda (w) ({name} w)) v)) {z(p)}) {r} {i})')
for body, f in EXPT:
    for k in (1, 2, 3):
        r, i = at(sp.diff(f, x, k), P1)
        emit(f'(check-z "{body} d{k}" (derivative-n (lambda (w) {body}) {z(P1)} {k}) {r} {i})')
    r, i = at(sp.diff(f, x), P1)
    emit(f'(check-z "{body} jet d1" (derivative (lambda (w) {body}) {z(P1)}) {r} {i})')
emit("")
emit("(if (= failures 0)")
emit("    (begin (display \"PASS: complex_carrier_math \") (display checks) (newline))")
emit("    (begin (display \"FAIL: \") (display failures) (display \" of \") (display checks) (newline)))")
print("\n".join(out))
