/**
 * @file vm_prelude_cache.c
 * @brief Prelude bytecode cache generator.
 *
 * When compiled standalone, generates vm_prelude_cache.h containing
 * the pre-compiled prelude bytecode as C arrays. This eliminates
 * the ~50ms prelude compilation on every REPL startup.
 *
 * Build: gcc -O2 -DGENERATE_PRELUDE_CACHE eshkol_vm.c -o gen_prelude -lm
 * Run:   ./gen_prelude > vm_prelude_cache.h
 *
 * Usage in vm_wasm_repl.c:
 *   #include "vm_prelude_cache.h"
 *   // Skip compile_and_run for prelude, load cached bytecode directly
 *
 * Copyright (C) Tsotchke Corporation. MIT License.
 */

#ifdef GENERATE_PRELUDE_CACHE

#define ESHKOL_VM_LIBRARY_MODE 1
#define ESHKOL_VM_NO_DISASM 1
#include "eshkol_vm.c"

int main(void) {
    FuncChunk chunk; chunk_init_arrays(&chunk);
    emit_builtin_preamble(&chunk);

    /* Compile the standard prelude */
    static const char* scheme_prelude =
        "(define (map f lst) (let loop ((l lst) (acc (list))) (if (null? l) (reverse acc) (loop (cdr l) (cons (f (car l)) acc)))))\n"
        "(define (filter pred lst) (let loop ((l lst) (acc (list))) (if (null? l) (reverse acc) (if (pred (car l)) (loop (cdr l) (cons (car l) acc)) (loop (cdr l) acc)))))\n"
        "(define (fold-left f init lst) (let loop ((l lst) (acc init)) (if (null? l) acc (loop (cdr l) (f acc (car l))))))\n"
        "(define (fold-right f init lst) (if (null? lst) init (f (car lst) (fold-right f init (cdr lst)))))\n"
        "(define (for-each f lst) (if (null? lst) 0 (begin (f (car lst)) (for-each f (cdr lst)))))\n"
        "(define (any pred lst) (if (null? lst) #f (if (pred (car lst)) #t (any pred (cdr lst)))))\n"
        "(define (every pred lst) (if (null? lst) #t (if (pred (car lst)) (every pred (cdr lst)) #f)))\n"
        "(define (find pred lst) (if (null? lst) #f (if (pred (car lst)) (car lst) (find pred (cdr lst)))))\n"
        "(define (take n lst) (if (= n 0) (list) (if (null? lst) (list) (cons (car lst) (take (- n 1) (cdr lst))))))\n"
        "(define (drop n lst) (if (= n 0) lst (if (null? lst) (list) (drop (- n 1) (cdr lst)))))\n"
        "(define (reduce f init lst) (fold-left f init lst))\n"
        "(define (merge compare a b) (cond ((null? a) b) ((null? b) a) ((compare (car a) (car b)) (cons (car a) (merge compare (cdr a) b))) (else (cons (car b) (merge compare a (cdr b))))))\n"
        "(define (sort compare lst) (if (or (null? lst) (null? (cdr lst))) lst (let ((half (quotient (length lst) 2))) (merge compare (sort compare (take half lst)) (sort compare (drop half lst))))))\n"
        "(define + (lambda args (fold-left add2 0 args)))\n"
        "(define * (lambda args (fold-left mul2 1 args)))\n"
        "(define (- . args) (if (null? (cdr args)) (sub2 0 (car args)) (fold-left sub2 (car args) (cdr args))))\n"
        "(define (/ . args) (if (null? (cdr args)) (div2 1 (car args)) (fold-left div2 (car args) (cdr args))))\n"
        "(define _append-2 append)\n"
        "(define (append . lists) (fold-right _append-2 '() lists))\n"
        "(define (number->string n . args) (_number->string-2 n (if (null? args) 10 (car args))))\n"
        "(define (atan x . rest) (if (null? rest) (_atan1 x) (_atan2 x (car rest))))\n"
        "(define (max a . rest) (fold-left _max2 a rest))\n"
        "(define (min a . rest) (fold-left _min2 a rest))\n"
        "(define (string-append . args) (fold-left _string-append-2 \"\" args))\n"
        "(define (make-list n val) (let loop ((i 0) (acc (list))) (if (= i n) acc (loop (+ i 1) (cons val acc)))))\n"
        "(define (make-factor-graph n . rest) (if (null? rest) (_make-fg2 n (make-list n 2)) (_make-fg2 n (car rest))))\n";
    src_ptr = scheme_prelude;
    while (1) {
        skip_ws(); if (!*src_ptr) break;
        Node* expr = parse_sexp(); if (!expr) break;
        int lb = chunk.n_locals;
        compile_expr(&chunk, expr, 0);
        if (chunk.n_locals == lb) chunk_emit(&chunk, OP_POP, 0);
        free_node(expr);
    }

    /* Output as C header */
    printf("/* Auto-generated by vm_prelude_cache.c — DO NOT EDIT */\n");
    printf("#ifndef VM_PRELUDE_CACHE_H\n");
    printf("#define VM_PRELUDE_CACHE_H\n\n");

    /* Emit code array */
    printf("static const int prelude_code_len = %d;\n", chunk.code_len);
    printf("static const int prelude_n_locals = %d;\n", chunk.n_locals);
    printf("static const int prelude_n_constants = %d;\n", chunk.n_constants);
    printf("\nstatic const uint8_t prelude_ops[] = {\n    ");
    for (int i = 0; i < chunk.code_len; i++) {
        printf("%d", chunk.code[i].op);
        if (i < chunk.code_len - 1) printf(", ");
        if ((i + 1) % 20 == 0) printf("\n    ");
    }
    printf("\n};\n");

    printf("\nstatic const int32_t prelude_operands[] = {\n    ");
    for (int i = 0; i < chunk.code_len; i++) {
        printf("%d", chunk.code[i].operand);
        if (i < chunk.code_len - 1) printf(", ");
        if ((i + 1) % 15 == 0) printf("\n    ");
    }
    printf("\n};\n");

    /* Emit constants: type + value */
    printf("\nstatic const uint8_t prelude_const_types[] = {\n    ");
    for (int i = 0; i < chunk.n_constants; i++) {
        printf("%d", chunk.constants[i].type);
        if (i < chunk.n_constants - 1) printf(", ");
        if ((i + 1) % 20 == 0) printf("\n    ");
    }
    printf("\n};\n");

    printf("\nstatic const int64_t prelude_const_ints[] = {\n    ");
    for (int i = 0; i < chunk.n_constants; i++) {
        if (chunk.constants[i].type == VAL_INT || chunk.constants[i].type == VAL_BOOL)
            printf("%lldLL", (long long)chunk.constants[i].as.i);
        else
            printf("0LL");
        if (i < chunk.n_constants - 1) printf(", ");
        if ((i + 1) % 10 == 0) printf("\n    ");
    }
    printf("\n};\n");

    printf("\nstatic const double prelude_const_floats[] = {\n    ");
    for (int i = 0; i < chunk.n_constants; i++) {
        if (chunk.constants[i].type == VAL_FLOAT)
            printf("%.17g", chunk.constants[i].as.f);
        else
            printf("0.0");
        if (i < chunk.n_constants - 1) printf(", ");
        if ((i + 1) % 8 == 0) printf("\n    ");
    }
    printf("\n};\n");

    /* Emit local names */
    printf("\nstatic const char* prelude_local_names[] = {\n");
    for (int i = 0; i < chunk.n_locals; i++) {
        printf("    \"%s\"", chunk.locals[i].name ? chunk.locals[i].name : "_");
        if (i < chunk.n_locals - 1) printf(",");
        printf("\n");
    }
    printf("};\n");

    printf("\n#endif /* VM_PRELUDE_CACHE_H */\n");

    chunk_free_arrays(&chunk);
    return 0;
}

#endif /* GENERATE_PRELUDE_CACHE */
