/**
 * @file vm_prelude_cache.c
 * @brief Prelude bytecode cache generator.
 *
 * When compiled standalone, generates vm_prelude_cache.h containing
 * the pre-compiled prelude bytecode as C arrays. This eliminates
 * the ~50ms prelude compilation on every REPL startup.
 *
 * Build: gcc -O2 -DGENERATE_PRELUDE_CACHE eshkol_vm.c -o gen_prelude -lm
 * Run:   ./gen_prelude > vm_prelude_cache.h
 *
 * Usage in vm_wasm_repl.c:
 *   #include "vm_prelude_cache.h"
 *   // Skip compile_and_run for prelude, load cached bytecode directly
 *
 * Copyright (C) Tsotchke Corporation. MIT License.
 */

#ifdef GENERATE_PRELUDE_CACHE

#define ESHKOL_VM_LIBRARY_MODE 1
#define ESHKOL_VM_NO_DISASM 1
#include "eshkol_vm.c"

int main(void) {
    FuncChunk chunk; chunk_init_arrays(&chunk);
    emit_builtin_preamble(&chunk);

    /* Compile the canonical prelude — same string as the runtime sites in
     * eshkol_vm.c (they all #include "vm_prelude_source.h"). */
    src_ptr = ESHKOL_VM_PRELUDE_SOURCE;
    while (1) {
        skip_ws(); if (!*src_ptr) break;
        Node* expr = parse_sexp(); if (!expr) break;
        int lb = chunk.n_locals;
        compile_expr(&chunk, expr, 0);
        if (chunk.n_locals == lb) chunk_emit(&chunk, OP_POP, 0);
        free_node(expr);
    }

    /* Output as C header */
    printf("/* Auto-generated by vm_prelude_cache.c — DO NOT EDIT */\n");
    printf("#ifndef VM_PRELUDE_CACHE_H\n");
    printf("#define VM_PRELUDE_CACHE_H\n\n");

    /* Emit code array */
    printf("static const int prelude_code_len = %d;\n", chunk.code_len);
    printf("static const int prelude_n_locals = %d;\n", chunk.n_locals);
    printf("static const int prelude_n_constants = %d;\n", chunk.n_constants);
    printf("\nstatic const uint8_t prelude_ops[] = {\n    ");
    for (int i = 0; i < chunk.code_len; i++) {
        printf("%d", chunk.code[i].op);
        if (i < chunk.code_len - 1) printf(", ");
        if ((i + 1) % 20 == 0) printf("\n    ");
    }
    printf("\n};\n");

    printf("\nstatic const int32_t prelude_operands[] = {\n    ");
    for (int i = 0; i < chunk.code_len; i++) {
        printf("%d", chunk.code[i].operand);
        if (i < chunk.code_len - 1) printf(", ");
        if ((i + 1) % 15 == 0) printf("\n    ");
    }
    printf("\n};\n");

    /* Emit constants: type + value */
    printf("\nstatic const uint8_t prelude_const_types[] = {\n    ");
    for (int i = 0; i < chunk.n_constants; i++) {
        printf("%d", chunk.constants[i].type);
        if (i < chunk.n_constants - 1) printf(", ");
        if ((i + 1) % 20 == 0) printf("\n    ");
    }
    printf("\n};\n");

    printf("\nstatic const int64_t prelude_const_ints[] = {\n    ");
    for (int i = 0; i < chunk.n_constants; i++) {
        if (chunk.constants[i].type == VAL_INT || chunk.constants[i].type == VAL_BOOL)
            printf("%lldLL", (long long)chunk.constants[i].as.i);
        else
            printf("0LL");
        if (i < chunk.n_constants - 1) printf(", ");
        if ((i + 1) % 10 == 0) printf("\n    ");
    }
    printf("\n};\n");

    printf("\nstatic const double prelude_const_floats[] = {\n    ");
    for (int i = 0; i < chunk.n_constants; i++) {
        if (chunk.constants[i].type == VAL_FLOAT)
            printf("%.17g", chunk.constants[i].as.f);
        else
            printf("0.0");
        if (i < chunk.n_constants - 1) printf(", ");
        if ((i + 1) % 8 == 0) printf("\n    ");
    }
    printf("\n};\n");

    /* Emit local names */
    printf("\nstatic const char* prelude_local_names[] = {\n");
    for (int i = 0; i < chunk.n_locals; i++) {
        printf("    \"%s\"", chunk.locals[i].name ? chunk.locals[i].name : "_");
        if (i < chunk.n_locals - 1) printf(",");
        printf("\n");
    }
    printf("};\n");

    printf("\n#endif /* VM_PRELUDE_CACHE_H */\n");

    chunk_free_arrays(&chunk);
    return 0;
}

#endif /* GENERATE_PRELUDE_CACHE */
