static void vm_run(VM* vm) {
#if defined(__GNUC__) || defined(__clang__)
/* =========================================================================
 * Computed-goto (threaded) dispatch — GCC/Clang only.
 *
 * Each handler ends with DISPATCH() which fetches the next instruction and
 * jumps directly to its handler via the dispatch_table, eliminating the
 * switch overhead (no bounds check, no indirect branch through a jump table
 * generated by the compiler — just a single indirect goto).
 * ========================================================================= */

    static void* dispatch_table[OP_COUNT] = {
        [OP_NOP]           = &&lbl_NOP,
        [OP_CONST]         = &&lbl_CONST,
        [OP_NIL]           = &&lbl_NIL,
        [OP_TRUE]          = &&lbl_TRUE,
        [OP_FALSE]         = &&lbl_FALSE,
        [OP_POP]           = &&lbl_POP,
        [OP_DUP]           = &&lbl_DUP,
        [OP_ADD]           = &&lbl_ADD,
        [OP_SUB]           = &&lbl_SUB,
        [OP_MUL]           = &&lbl_MUL,
        [OP_DIV]           = &&lbl_DIV,
        [OP_MOD]           = &&lbl_MOD,
        [OP_NEG]           = &&lbl_NEG,
        [OP_ABS]           = &&lbl_ABS,
        [OP_EQ]            = &&lbl_EQ,
        [OP_LT]            = &&lbl_LT,
        [OP_GT]            = &&lbl_GT,
        [OP_LE]            = &&lbl_LE,
        [OP_GE]            = &&lbl_GE,
        [OP_NOT]           = &&lbl_NOT,
        [OP_GET_LOCAL]     = &&lbl_GET_LOCAL,
        [OP_SET_LOCAL]     = &&lbl_SET_LOCAL,
        [OP_GET_UPVALUE]   = &&lbl_GET_UPVALUE,
        [OP_SET_UPVALUE]   = &&lbl_SET_UPVALUE,
        [OP_CLOSURE]       = &&lbl_CLOSURE,
        [OP_CALL]          = &&lbl_CALL,
        [OP_TAIL_CALL]     = &&lbl_TAIL_CALL,
        [OP_RETURN]        = &&lbl_RETURN,
        [OP_JUMP]          = &&lbl_JUMP,
        [OP_JUMP_IF_FALSE] = &&lbl_JUMP_IF_FALSE,
        [OP_LOOP]          = &&lbl_LOOP,
        [OP_CONS]          = &&lbl_CONS,
        [OP_CAR]           = &&lbl_CAR,
        [OP_CDR]           = &&lbl_CDR,
        [OP_NULL_P]        = &&lbl_NULL_P,
        [OP_PRINT]         = &&lbl_PRINT,
        [OP_HALT]          = &&lbl_HALT,
        [OP_NATIVE_CALL]   = &&lbl_NATIVE_CALL,
        [OP_CLOSE_UPVALUE] = &&lbl_CLOSE_UPVALUE,
        [OP_VEC_CREATE]    = &&lbl_VEC_CREATE,
        [OP_VEC_REF]       = &&lbl_VEC_REF,
        [OP_VEC_SET]       = &&lbl_VEC_SET,
        [OP_VEC_LEN]       = &&lbl_VEC_LEN,
        [OP_STR_REF]       = &&lbl_STR_REF,
        [OP_STR_LEN]       = &&lbl_STR_LEN,
        [OP_PAIR_P]        = &&lbl_PAIR_P,
        [OP_NUM_P]         = &&lbl_NUM_P,
        [OP_STR_P]         = &&lbl_STR_P,
        [OP_BOOL_P]        = &&lbl_BOOL_P,
        [OP_PROC_P]        = &&lbl_PROC_P,
        [OP_VEC_P]         = &&lbl_VEC_P,
        [OP_SET_CAR]       = &&lbl_SET_CAR,
        [OP_SET_CDR]       = &&lbl_SET_CDR,
        [OP_POPN]          = &&lbl_POPN,
        [OP_OPEN_CLOSURE]  = &&lbl_NOP,
        [OP_CALLCC]        = &&lbl_CALLCC,
        [OP_INVOKE_CC]     = &&lbl_NOP,
        [OP_PUSH_HANDLER]  = &&lbl_PUSH_HANDLER,
        [OP_POP_HANDLER]   = &&lbl_POP_HANDLER,
        [OP_GET_EXN]       = &&lbl_GET_EXN,
        [OP_PACK_REST]     = &&lbl_PACK_REST,
        [OP_WIND_PUSH]     = &&lbl_WIND_PUSH,
        [OP_WIND_POP]      = &&lbl_WIND_POP,
    };

    #define DISPATCH() do { \
        if (vm->halted || vm->error || vm->pc >= vm->code_len) goto vm_exit; \
        instr = vm->code[vm->pc++]; \
        goto *dispatch_table[instr.op]; \
    } while(0)

    Instr instr;
    DISPATCH();

    /* --- Constants & Stack --- */

    lbl_NOP:
        DISPATCH();

    lbl_CONST:
        if (instr.operand < 0 || instr.operand >= vm->n_constants) {
            printf("INVALID CONSTANT INDEX %d\n", instr.operand);
            vm->error = 1; goto vm_exit;
        }
        vm_push(vm, vm->constants[instr.operand]);
        DISPATCH();

    lbl_NIL:   vm_push(vm, NIL_VAL);     DISPATCH();
    lbl_TRUE:  vm_push(vm, BOOL_VAL(1)); DISPATCH();
    lbl_FALSE: vm_push(vm, BOOL_VAL(0)); DISPATCH();
    lbl_POP:   vm_pop(vm);               DISPATCH();
    lbl_DUP:   vm_push(vm, vm_peek(vm, 0)); DISPATCH();

    /* --- Arithmetic --- */

    lbl_ADD: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, number_val(as_number(a) + as_number(b))); DISPATCH(); }
    lbl_SUB: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, number_val(as_number(a) - as_number(b))); DISPATCH(); }
    lbl_MUL: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, number_val(as_number(a) * as_number(b))); DISPATCH(); }
    lbl_DIV: { Value b = vm_pop(vm), a = vm_pop(vm);
        double bd = as_number(b);
        if (bd == 0) { printf("DIVIDE BY ZERO\n"); vm->error = 1; goto vm_exit; }
        vm_push(vm, number_val(as_number(a) / bd)); DISPATCH(); }
    lbl_MOD: {
        Value b = vm_pop(vm), a = vm_pop(vm);
        double bd = as_number(b);
        if (bd == 0) { printf("MODULO BY ZERO\n"); vm->error = 1; goto vm_exit; }
        double r = fmod(as_number(a), bd);
        if (r != 0 && ((r > 0) != (bd > 0))) r += bd;
        vm_push(vm, number_val(r));
        DISPATCH();
    }
    lbl_NEG: { Value a = vm_pop(vm); vm_push(vm, number_val(-as_number(a))); DISPATCH(); }
    lbl_ABS: { Value a = vm_pop(vm); vm_push(vm, number_val(fabs(as_number(a)))); DISPATCH(); }

    /* --- Comparison --- */

    lbl_EQ: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) == as_number(b))); DISPATCH(); }
    lbl_LT: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) <  as_number(b))); DISPATCH(); }
    lbl_GT: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) >  as_number(b))); DISPATCH(); }
    lbl_LE: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) <= as_number(b))); DISPATCH(); }
    lbl_GE: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) >= as_number(b))); DISPATCH(); }
    lbl_NOT: { Value a = vm_pop(vm); vm_push(vm, BOOL_VAL(!is_truthy(a))); DISPATCH(); }

    /* --- Variables --- */

    lbl_GET_LOCAL:
        vm_push(vm, vm->stack[vm->fp + instr.operand]);
        DISPATCH();
    lbl_SET_LOCAL:
        vm->stack[vm->fp + instr.operand] = vm_peek(vm, 0);
        vm_pop(vm);
        DISPATCH();
    lbl_GET_UPVALUE: {
        Value closure_val = vm->stack[vm->fp - 1];
        if (closure_val.type == VAL_CLOSURE) {
            HeapObject* cl = vm->heap.objects[closure_val.as.ptr];
            if (instr.operand >= 0 && instr.operand < cl->closure.n_upvalues) {
                vm_push(vm, cl->closure.upvalues[instr.operand]);
            } else {
                printf("UPVALUE INDEX OUT OF BOUNDS\n");
                vm_push(vm, NIL_VAL);
            }
        } else {
            vm_push(vm, NIL_VAL);
        }
        DISPATCH();
    }
    lbl_SET_UPVALUE: {
        Value closure_val = vm->stack[vm->fp - 1];
        if (closure_val.type == VAL_CLOSURE) {
            HeapObject* cl = vm->heap.objects[closure_val.as.ptr];
            if (instr.operand >= 0 && instr.operand < cl->closure.n_upvalues) {
                cl->closure.upvalues[instr.operand] = vm_peek(vm, 0);
            } else {
                printf("UPVALUE INDEX OUT OF BOUNDS\n");
            }
        }
        vm_pop(vm);
        DISPATCH();
    }

    /* --- Closures --- */

    lbl_CLOSURE: {
        int const_idx = instr.operand & 0xFFFF;
        int n_upvalues = (instr.operand >> 16) & 0xFF;
        if (n_upvalues > 16) n_upvalues = 16;
        Value func_const = vm->constants[const_idx];
        int32_t func_pc = (int32_t)func_const.as.i;
        int32_t ptr = heap_alloc(&vm->heap);
        if (ptr < 0) { vm->error = 1; goto vm_exit; }
        vm->heap.objects[ptr]->type = HEAP_CLOSURE;
        vm->heap.objects[ptr]->closure.func_pc = func_pc;
        vm->heap.objects[ptr]->closure.n_upvalues = n_upvalues;
        for (int i = n_upvalues - 1; i >= 0; i--) {
            vm->heap.objects[ptr]->closure.upvalues[i] = vm_pop(vm);
        }
        vm_push(vm, CLOSURE_VAL(ptr));
        DISPATCH();
    }

    /* --- Function call --- */

    lbl_CALL: {
        int argc = instr.operand;
        Value func = vm->stack[vm->sp - 1 - argc];

        if (func.type != VAL_CLOSURE) {
            printf("ERROR: calling non-function\n");
            vm->error = 1; goto vm_exit;
        }

        HeapObject* cl = vm->heap.objects[func.as.ptr];

        if (vm->frame_count >= MAX_FRAMES) { printf("FRAME OVERFLOW\n"); vm->error = 1; goto vm_exit; }
        vm->frames[vm->frame_count].return_pc = vm->pc;
        vm->frames[vm->frame_count].return_fp = vm->fp;
        vm->frames[vm->frame_count].func_pc = cl->closure.func_pc;
        vm->frame_count++;

        vm->fp = vm->sp - argc;
        vm->pc = cl->closure.func_pc;
        DISPATCH();
    }

    lbl_TAIL_CALL: {
        int argc = instr.operand;
        Value func = vm->stack[vm->sp - 1 - argc];
        if (func.type != VAL_CLOSURE) { vm->error = 1; goto vm_exit; }
        HeapObject* cl = vm->heap.objects[func.as.ptr];

        for (int i = 0; i < argc; i++) {
            vm->stack[vm->fp + i] = vm->stack[vm->sp - argc + i];
        }
        vm->sp = vm->fp + argc;
        vm->pc = cl->closure.func_pc;
        DISPATCH();
    }

    lbl_RETURN: {
        Value result = vm_pop(vm);
        if (vm->frame_count <= 0) {
            vm_push(vm, result);
            vm->halted = 1;
            goto vm_exit;
        }
        vm->frame_count--;
        /* Check for native-call sentinel */
        if (vm->frames[vm->frame_count].return_pc == -1) {
            vm_push(vm, result);
            vm->halted = 1;
            goto vm_exit;
        }
        vm->sp = vm->fp - 1;
        vm->fp = vm->frames[vm->frame_count].return_fp;
        vm->pc = vm->frames[vm->frame_count].return_pc;
        vm_push(vm, result);
        DISPATCH();
    }

    /* --- Control Flow --- */

    lbl_JUMP:
        vm->pc = instr.operand;
        DISPATCH();
    lbl_JUMP_IF_FALSE: {
        Value cond = vm_pop(vm);
        if (!is_truthy(cond)) vm->pc = instr.operand;
        DISPATCH();
    }
    lbl_LOOP:
        vm->pc = instr.operand;
        DISPATCH();

    /* --- Pairs --- */

    lbl_CONS: {
        Value car = vm_pop(vm), cdr = vm_pop(vm);
        int32_t ptr = heap_alloc(&vm->heap);
        if (ptr < 0) { vm->error = 1; goto vm_exit; }
        vm->heap.objects[ptr]->type = HEAP_CONS;
        vm->heap.objects[ptr]->cons.car = car;
        vm->heap.objects[ptr]->cons.cdr = cdr;
        vm_push(vm, PAIR_VAL(ptr));
        DISPATCH();
    }
    lbl_CAR: {
        Value pair = vm_pop(vm);
        if (pair.type != VAL_PAIR) { printf("CAR on non-pair\n"); vm->error = 1; goto vm_exit; }
        vm_push(vm, vm->heap.objects[pair.as.ptr]->cons.car);
        DISPATCH();
    }
    lbl_CDR: {
        Value pair = vm_pop(vm);
        if (pair.type != VAL_PAIR) { printf("CDR on non-pair\n"); vm->error = 1; goto vm_exit; }
        vm_push(vm, vm->heap.objects[pair.as.ptr]->cons.cdr);
        DISPATCH();
    }
    lbl_NULL_P: {
        Value v = vm_pop(vm);
        vm_push(vm, BOOL_VAL(v.type == VAL_NIL));
        DISPATCH();
    }

    /* --- I/O --- */

    lbl_PRINT: {
        Value v = vm_pop(vm);
        print_value(vm, v);
        printf("\n");
        if (vm->n_outputs < 256) vm->outputs[vm->n_outputs++] = v;
        DISPATCH();
    }

    lbl_HALT:
        vm->halted = 1;
        goto vm_exit;

    lbl_NATIVE_CALL: {
        vm_dispatch_native(vm, instr.operand);
        DISPATCH();
    }

    lbl_CLOSE_UPVALUE: {
        /* Patch the TOS closure's upvalue[operand] to point to the closure itself */
        Value cl_val = vm_peek(vm, 0);
        if (cl_val.type == VAL_CLOSURE) {
            HeapObject* cl = vm->heap.objects[cl_val.as.ptr];
            if (instr.operand >= 0 && instr.operand < cl->closure.n_upvalues)
                cl->closure.upvalues[instr.operand] = cl_val;
        }
        DISPATCH();
    }

    lbl_VEC_CREATE: {
        int count = instr.operand;
        int32_t ptr = heap_alloc(&vm->heap);
        if (ptr < 0) { vm->error = 1; goto vm_exit; }
        vm->heap.objects[ptr]->type = HEAP_VECTOR;
        VmVector* vec = (VmVector*)vm_alloc(&vm->heap.regions, sizeof(VmVector));
        if (!vec) { vm->error = 1; goto vm_exit; }
        vec->len = count;
        vec->cap = count;
        vec->items = (Value*)vm_alloc(&vm->heap.regions, count * sizeof(Value));
        if (!vec->items && count > 0) { vm->error = 1; goto vm_exit; }
        for (int i = count - 1; i >= 0; i--) vec->items[i] = vm_pop(vm);
        vm->heap.objects[ptr]->opaque.ptr = vec;
        vm_push(vm, (Value){.type = VAL_VECTOR, .as.ptr = ptr});
        DISPATCH();
    }

    lbl_VEC_REF: {
        Value idx = vm_pop(vm), vec_val = vm_pop(vm);
        if (vec_val.type != VAL_VECTOR) { vm_push(vm, NIL_VAL); DISPATCH(); }
        VmVector* vec = (VmVector*)vm->heap.objects[vec_val.as.ptr]->opaque.ptr;
        int i = (int)as_number(idx);
        if (vec && i >= 0 && i < vec->len) vm_push(vm, vec->items[i]);
        else vm_push(vm, NIL_VAL);
        DISPATCH();
    }

    lbl_VEC_SET: {
        Value val = vm_pop(vm), idx = vm_pop(vm), vec_val = vm_pop(vm);
        if (vec_val.type == VAL_VECTOR) {
            VmVector* vec = (VmVector*)vm->heap.objects[vec_val.as.ptr]->opaque.ptr;
            int i = (int)as_number(idx);
            if (vec && i >= 0 && i < vec->len) vec->items[i] = val;
        }
        vm_push(vm, NIL_VAL);
        DISPATCH();
    }

    lbl_VEC_LEN: {
        Value vec_val = vm_pop(vm);
        if (vec_val.type == VAL_VECTOR) {
            VmVector* vec = (VmVector*)vm->heap.objects[vec_val.as.ptr]->opaque.ptr;
            vm_push(vm, INT_VAL(vec ? vec->len : 0));
        } else vm_push(vm, INT_VAL(0));
        DISPATCH();
    }

    lbl_STR_REF: {
        Value idx = vm_pop(vm), str_val = vm_pop(vm);
        if (str_val.type == VAL_STRING) {
            VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
            int i = (int)as_number(idx);
            if (s && i >= 0 && i < s->byte_len) vm_push(vm, INT_VAL((unsigned char)s->data[i]));
            else vm_push(vm, INT_VAL(0));
        } else vm_push(vm, INT_VAL(0));
        DISPATCH();
    }

    lbl_STR_LEN: {
        Value str_val = vm_pop(vm);
        if (str_val.type == VAL_STRING) {
            VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
            vm_push(vm, INT_VAL(s ? s->byte_len : 0));
        } else vm_push(vm, INT_VAL(0));
        DISPATCH();
    }

    lbl_PAIR_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_PAIR)); DISPATCH(); }
    lbl_NUM_P:   { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_INT || v.type == VAL_FLOAT)); DISPATCH(); }
    lbl_STR_P:   { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_STRING)); DISPATCH(); }
    lbl_BOOL_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_BOOL)); DISPATCH(); }
    lbl_PROC_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_CLOSURE)); DISPATCH(); }
    lbl_VEC_P:   { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_VECTOR)); DISPATCH(); }

    lbl_SET_CAR: {
        Value val = vm_pop(vm), pair = vm_pop(vm);
        if (pair.type == VAL_PAIR) vm->heap.objects[pair.as.ptr]->cons.car = val;
        vm_push(vm, NIL_VAL);
        DISPATCH();
    }
    lbl_SET_CDR: {
        Value val = vm_pop(vm), pair = vm_pop(vm);
        if (pair.type == VAL_PAIR) vm->heap.objects[pair.as.ptr]->cons.cdr = val;
        vm_push(vm, NIL_VAL);
        DISPATCH();
    }

    lbl_POPN: {
        int n = instr.operand;
        if (n > 0 && vm->sp > n) {
            Value top = vm->stack[vm->sp - 1];
            vm->sp -= n;
            vm->stack[vm->sp - 1] = top;
        }
        DISPATCH();
    }

    lbl_CALLCC: {
        /* Simplified: capture continuation as a closure that invokes OP_INVOKE_CC */
        /* For now, push NIL — full continuations need the compiler's execute_chunk support */
        Value proc = vm_pop(vm);
        (void)proc;
        vm_push(vm, NIL_VAL);
        DISPATCH();
    }

    lbl_PUSH_HANDLER: {
        /* operand = handler PC. For now, just record it. */
        vm_push(vm, NIL_VAL); /* placeholder */
        vm->pc = instr.operand; /* jump to handler on error — simplified */
        DISPATCH();
    }

    lbl_POP_HANDLER: DISPATCH();

    lbl_GET_EXN: {
        vm_push(vm, NIL_VAL); /* simplified: no exception register in base VM */
        DISPATCH();
    }

    lbl_PACK_REST: {
        int n_fixed = instr.operand;
        int n_args = vm->sp - vm->fp;
        Value list = NIL_VAL;
        for (int i = n_args - 1; i >= n_fixed; i--) {
            Value item = vm->stack[vm->fp + i];
            int32_t p = heap_alloc(&vm->heap);
            if (p < 0) { vm->error = 1; goto vm_exit; }
            vm->heap.objects[p]->type = HEAP_CONS;
            vm->heap.objects[p]->cons.car = item;
            vm->heap.objects[p]->cons.cdr = list;
            list = PAIR_VAL(p);
        }
        vm->sp = vm->fp + n_fixed;
        vm_push(vm, list);
        DISPATCH();
    }

    lbl_WIND_PUSH: {
        vm_pop(vm); /* consume after thunk — simplified */
        DISPATCH();
    }

    lbl_WIND_POP: DISPATCH();

vm_exit:
    #undef DISPATCH
    ;

#else
/* =========================================================================
 * Fallback: standard switch dispatch for non-GCC/Clang compilers (MSVC etc.)
 * ========================================================================= */

    int step_count = 0;
    while (!vm->halted && !vm->error && vm->pc < vm->code_len) {
        if (++step_count > 10000000) {
            fprintf(stderr, "VM: 10M steps exceeded at pc=%d op=%d fp=%d sp=%d fc=%d\n",
                    vm->pc, vm->code[vm->pc].op, vm->fp, vm->sp, vm->frame_count);
            vm->error = 1; break;
        }
        Instr instr = vm->code[vm->pc++];

        switch (instr.op) {
        case OP_NOP: break;

        case OP_CONST:
            if (instr.operand < 0 || instr.operand >= vm->n_constants) {
                printf("INVALID CONSTANT INDEX %d\n", instr.operand);
                vm->error = 1; break;
            }
            vm_push(vm, vm->constants[instr.operand]);
            break;

        case OP_NIL:   vm_push(vm, NIL_VAL); break;
        case OP_TRUE:  vm_push(vm, BOOL_VAL(1)); break;
        case OP_FALSE: vm_push(vm, BOOL_VAL(0)); break;
        case OP_POP:   vm_pop(vm); break;
        case OP_DUP:   vm_push(vm, vm_peek(vm, 0)); break;

        /* Arithmetic */
        case OP_ADD: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, number_val(as_number(a) + as_number(b))); break; }
        case OP_SUB: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, number_val(as_number(a) - as_number(b))); break; }
        case OP_MUL: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, number_val(as_number(a) * as_number(b))); break; }
        case OP_DIV: { Value b = vm_pop(vm), a = vm_pop(vm);
            double bd = as_number(b);
            if (bd == 0) { printf("DIVIDE BY ZERO\n"); vm->error = 1; break; }
            vm_push(vm, number_val(as_number(a) / bd)); break; }
        case OP_MOD: {
            Value b = vm_pop(vm), a = vm_pop(vm);
            double bd = as_number(b);
            if (bd == 0) { printf("MODULO BY ZERO\n"); vm->error = 1; break; }
            double r = fmod(as_number(a), bd);
            if (r != 0 && ((r > 0) != (bd > 0))) r += bd;
            vm_push(vm, number_val(r));
            break;
        }
        case OP_NEG: { Value a = vm_pop(vm); vm_push(vm, number_val(-as_number(a))); break; }
        case OP_ABS: { Value a = vm_pop(vm); vm_push(vm, number_val(fabs(as_number(a)))); break; }

        /* Comparison — push proper booleans */
        case OP_EQ: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) == as_number(b))); break; }
        case OP_LT: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) < as_number(b))); break; }
        case OP_GT: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) > as_number(b))); break; }
        case OP_LE: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) <= as_number(b))); break; }
        case OP_GE: { Value b = vm_pop(vm), a = vm_pop(vm); vm_push(vm, BOOL_VAL(as_number(a) >= as_number(b))); break; }
        case OP_NOT: { Value a = vm_pop(vm); vm_push(vm, BOOL_VAL(!is_truthy(a))); break; }

        /* Variables */
        case OP_GET_LOCAL:
            vm_push(vm, vm->stack[vm->fp + instr.operand]);
            break;
        case OP_SET_LOCAL:
            vm->stack[vm->fp + instr.operand] = vm_peek(vm, 0);
            vm_pop(vm);
            break;
        case OP_GET_UPVALUE: {
            Value closure_val = vm->stack[vm->fp - 1]; /* closure is just below frame */
            if (closure_val.type == VAL_CLOSURE) {
                HeapObject* cl = vm->heap.objects[closure_val.as.ptr];
                if (instr.operand >= 0 && instr.operand < cl->closure.n_upvalues) {
                    vm_push(vm, cl->closure.upvalues[instr.operand]);
                } else {
                    printf("UPVALUE INDEX OUT OF BOUNDS\n");
                    vm_push(vm, NIL_VAL);
                }
            } else {
                vm_push(vm, NIL_VAL);
            }
            break;
        }
        case OP_SET_UPVALUE: {
            Value closure_val = vm->stack[vm->fp - 1];
            if (closure_val.type == VAL_CLOSURE) {
                HeapObject* cl = vm->heap.objects[closure_val.as.ptr];
                if (instr.operand >= 0 && instr.operand < cl->closure.n_upvalues) {
                    cl->closure.upvalues[instr.operand] = vm_peek(vm, 0);
                } else {
                    printf("UPVALUE INDEX OUT OF BOUNDS\n");
                }
            }
            vm_pop(vm);
            break;
        }

        /* Closures */
        case OP_CLOSURE: {
            /* Operand: low 16 bits = constant pool index, bits 16-23 = n_upvalues */
            int const_idx = instr.operand & 0xFFFF;
            int n_upvalues = (instr.operand >> 16) & 0xFF;
            if (n_upvalues > 16) n_upvalues = 16;
            Value func_const = vm->constants[const_idx];
            int32_t func_pc = (int32_t)func_const.as.i;
            int32_t ptr = heap_alloc(&vm->heap);
            if (ptr < 0) { vm->error = 1; break; }
            vm->heap.objects[ptr]->type = HEAP_CLOSURE;
            vm->heap.objects[ptr]->closure.func_pc = func_pc;
            vm->heap.objects[ptr]->closure.n_upvalues = n_upvalues;
            /* Pop upvalues from stack (pushed before CLOSURE, in reverse order) */
            for (int i = n_upvalues - 1; i >= 0; i--) {
                vm->heap.objects[ptr]->closure.upvalues[i] = vm_pop(vm);
            }
            vm_push(vm, CLOSURE_VAL(ptr));
            break;
        }

        /* Function call */
        case OP_CALL: {
            int argc = instr.operand;
            Value func = vm->stack[vm->sp - 1 - argc]; /* function is below args */

            if (func.type != VAL_CLOSURE) {
                printf("ERROR: calling non-function\n");
                vm->error = 1; break;
            }

            HeapObject* cl = vm->heap.objects[func.as.ptr];

            /* Save call frame */
            if (vm->frame_count >= MAX_FRAMES) { printf("FRAME OVERFLOW\n"); vm->error = 1; break; }
            vm->frames[vm->frame_count].return_pc = vm->pc;
            vm->frames[vm->frame_count].return_fp = vm->fp;
            vm->frames[vm->frame_count].func_pc = cl->closure.func_pc;
            vm->frame_count++;

            /* Set up new frame: func sits at sp-argc-1, args at sp-argc..sp-1 */
            vm->fp = vm->sp - argc;
            vm->pc = cl->closure.func_pc;
            break;
        }

        case OP_TAIL_CALL: {
            int argc = instr.operand;
            Value func = vm->stack[vm->sp - 1 - argc];
            if (func.type != VAL_CLOSURE) { vm->error = 1; break; }
            HeapObject* cl = vm->heap.objects[func.as.ptr];

            /* Move args to current frame position (reuse frame) */
            for (int i = 0; i < argc; i++) {
                vm->stack[vm->fp + i] = vm->stack[vm->sp - argc + i];
            }
            vm->sp = vm->fp + argc;
            /* Update closure slot so GET_UPVALUE sees the NEW closure's upvalues */
            vm->stack[vm->fp - 1] = func;
            vm->pc = cl->closure.func_pc;
            break;
        }

        case OP_RETURN: {
            Value result = vm_pop(vm);
            if (vm->frame_count <= 0) {
                /* Top-level return */
                vm_push(vm, result);
                vm->halted = 1;
                break;
            }
            vm->frame_count--;
            /* Check for native-call sentinel */
            if (vm->frames[vm->frame_count].return_pc == -1) {
                vm_push(vm, result);
                vm->halted = 1;
                break;
            }
            vm->sp = vm->fp - 1; /* discard frame + function slot */
            vm->fp = vm->frames[vm->frame_count].return_fp;
            vm->pc = vm->frames[vm->frame_count].return_pc;
            vm_push(vm, result);
            break;
        }

        /* Control Flow */
        case OP_JUMP:
            vm->pc = instr.operand;
            break;
        case OP_JUMP_IF_FALSE: {
            Value cond = vm_pop(vm);
            if (!is_truthy(cond)) vm->pc = instr.operand;
            break;
        }
        case OP_LOOP:
            vm->pc = instr.operand;
            break;

        /* Pairs */
        case OP_CONS: {
            Value car = vm_pop(vm), cdr = vm_pop(vm);  /* TOS=car, SOS=cdr */
            int32_t ptr = heap_alloc(&vm->heap);
            if (ptr < 0) { vm->error = 1; break; }
            vm->heap.objects[ptr]->type = HEAP_CONS;
            vm->heap.objects[ptr]->cons.car = car;
            vm->heap.objects[ptr]->cons.cdr = cdr;
            vm_push(vm, PAIR_VAL(ptr));
            break;
        }
        case OP_CAR: {
            Value pair = vm_pop(vm);
            if (pair.type != VAL_PAIR) { printf("CAR on non-pair\n"); vm->error = 1; break; }
            vm_push(vm, vm->heap.objects[pair.as.ptr]->cons.car);
            break;
        }
        case OP_CDR: {
            Value pair = vm_pop(vm);
            if (pair.type != VAL_PAIR) { printf("CDR on non-pair\n"); vm->error = 1; break; }
            vm_push(vm, vm->heap.objects[pair.as.ptr]->cons.cdr);
            break;
        }
        case OP_NULL_P: {
            Value v = vm_pop(vm);
            vm_push(vm, BOOL_VAL(v.type == VAL_NIL));
            break;
        }

        /* I/O */
        case OP_PRINT: {
            Value v = vm_pop(vm);
            fprintf(stderr, "[PRINT] type=%d i=%lld f=%f sp=%d fp=%d\n",
                    v.type, (long long)v.as.i, v.as.f, vm->sp, vm->fp);
            print_value(vm, v);
            printf("\n");
            if (vm->n_outputs < 256) vm->outputs[vm->n_outputs++] = v;
            break;
        }

        case OP_HALT:
            fprintf(stderr, "[HALT] at sp=%d fp=%d frames=%d\n", vm->sp, vm->fp, vm->frame_count);
            vm->halted = 1;
            break;

        case OP_NATIVE_CALL: {
            vm_dispatch_native(vm, instr.operand);
            break;
        }

        case OP_CLOSE_UPVALUE: {
            Value cl_val = vm_peek(vm, 0);
            if (cl_val.type == VAL_CLOSURE) {
                HeapObject* cl = vm->heap.objects[cl_val.as.ptr];
                if (instr.operand >= 0 && instr.operand < cl->closure.n_upvalues)
                    cl->closure.upvalues[instr.operand] = cl_val;
            }
            break;
        }

        case OP_VEC_CREATE: {
            int count = instr.operand;
            int32_t ptr = heap_alloc(&vm->heap);
            if (ptr < 0) { vm->error = 1; break; }
            vm->heap.objects[ptr]->type = HEAP_VECTOR;
            VmVector* vec = (VmVector*)vm_alloc(&vm->heap.regions, sizeof(VmVector));
            if (!vec) { vm->error = 1; break; }
            vec->len = count; vec->cap = count;
            vec->items = (Value*)vm_alloc(&vm->heap.regions, count * sizeof(Value));
            if (!vec->items && count > 0) { vm->error = 1; break; }
            for (int i = count - 1; i >= 0; i--) vec->items[i] = vm_pop(vm);
            vm->heap.objects[ptr]->opaque.ptr = vec;
            vm_push(vm, (Value){.type = VAL_VECTOR, .as.ptr = ptr});
            break;
        }

        case OP_VEC_REF: {
            Value idx = vm_pop(vm), vec_val = vm_pop(vm);
            if (vec_val.type != VAL_VECTOR) { vm_push(vm, NIL_VAL); break; }
            VmVector* vec = (VmVector*)vm->heap.objects[vec_val.as.ptr]->opaque.ptr;
            int i = (int)as_number(idx);
            if (vec && i >= 0 && i < vec->len) vm_push(vm, vec->items[i]);
            else vm_push(vm, NIL_VAL);
            break;
        }

        case OP_VEC_SET: {
            Value val = vm_pop(vm), idx = vm_pop(vm), vec_val = vm_pop(vm);
            if (vec_val.type == VAL_VECTOR) {
                VmVector* vec = (VmVector*)vm->heap.objects[vec_val.as.ptr]->opaque.ptr;
                int i = (int)as_number(idx);
                if (vec && i >= 0 && i < vec->len) vec->items[i] = val;
            }
            vm_push(vm, NIL_VAL);
            break;
        }

        case OP_VEC_LEN: {
            Value vec_val = vm_pop(vm);
            if (vec_val.type == VAL_VECTOR) {
                VmVector* vec = (VmVector*)vm->heap.objects[vec_val.as.ptr]->opaque.ptr;
                vm_push(vm, INT_VAL(vec ? vec->len : 0));
            } else vm_push(vm, INT_VAL(0));
            break;
        }

        case OP_STR_REF: {
            Value idx = vm_pop(vm), str_val = vm_pop(vm);
            if (str_val.type == VAL_STRING) {
                VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
                int i = (int)as_number(idx);
                if (s && i >= 0 && i < s->byte_len) vm_push(vm, INT_VAL((unsigned char)s->data[i]));
                else vm_push(vm, INT_VAL(0));
            } else vm_push(vm, INT_VAL(0));
            break;
        }

        case OP_STR_LEN: {
            Value str_val = vm_pop(vm);
            if (str_val.type == VAL_STRING) {
                VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
                vm_push(vm, INT_VAL(s ? s->byte_len : 0));
            } else vm_push(vm, INT_VAL(0));
            break;
        }

        case OP_PAIR_P: { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_PAIR)); break; }
        case OP_NUM_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_INT || v.type == VAL_FLOAT)); break; }
        case OP_STR_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_STRING)); break; }
        case OP_BOOL_P: { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_BOOL)); break; }
        case OP_PROC_P: { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_CLOSURE)); break; }
        case OP_VEC_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_VECTOR)); break; }

        case OP_SET_CAR: {
            Value val = vm_pop(vm), pair = vm_pop(vm);
            if (pair.type == VAL_PAIR) vm->heap.objects[pair.as.ptr]->cons.car = val;
            vm_push(vm, NIL_VAL); break;
        }
        case OP_SET_CDR: {
            Value val = vm_pop(vm), pair = vm_pop(vm);
            if (pair.type == VAL_PAIR) vm->heap.objects[pair.as.ptr]->cons.cdr = val;
            vm_push(vm, NIL_VAL); break;
        }

        case OP_POPN: {
            int n = instr.operand;
            if (n > 0 && vm->sp > n) {
                Value top = vm->stack[vm->sp - 1];
                vm->sp -= n;
                vm->stack[vm->sp - 1] = top;
            }
            break;
        }

        case OP_CALLCC: { Value proc = vm_pop(vm); (void)proc; vm_push(vm, NIL_VAL); break; }
        case OP_INVOKE_CC: break;
        case OP_OPEN_CLOSURE: break;
        case OP_PUSH_HANDLER: { vm_push(vm, NIL_VAL); vm->pc = instr.operand; break; }
        case OP_POP_HANDLER: break;
        case OP_GET_EXN: { vm_push(vm, NIL_VAL); break; }
        case OP_PACK_REST: {
            int n_fixed = instr.operand;
            int n_args = vm->sp - vm->fp;
            Value list = NIL_VAL;
            for (int i = n_args - 1; i >= n_fixed; i--) {
                Value item = vm->stack[vm->fp + i];
                int32_t p = heap_alloc(&vm->heap);
                if (p < 0) { vm->error = 1; break; }
                vm->heap.objects[p]->type = HEAP_CONS;
                vm->heap.objects[p]->cons.car = item;
                vm->heap.objects[p]->cons.cdr = list;
                list = PAIR_VAL(p);
            }
            vm->sp = vm->fp + n_fixed;
            vm_push(vm, list);
            break;
        }
        case OP_WIND_PUSH: vm_pop(vm); break;
        case OP_WIND_POP: break;
        /* OP_CLOSE_UPVALUE handled at line 720 — no duplicate */

        default:
            printf("UNKNOWN OPCODE %d\n", instr.op);
            vm->error = 1;
            break;
        }
    }
#endif
}

/*******************************************************************************
 * Test Programs
 ******************************************************************************/

static const char* opnames[] = {
    "NOP","CONST","NIL","TRUE","FALSE","POP","DUP",
    "ADD","SUB","MUL","DIV","MOD","NEG","ABS",
    "EQ","LT","GT","LE","GE","NOT",
    "GETL","SETL","GETUP","SETUP",
    "CLOSURE","CALL","TCALL","RET",
    "JUMP","JIF","LOOP",
    "CONS","CAR","CDR","NULLP",
    "PRINT","HALT","NATIVE"
};

static void emit(VM* vm, uint8_t op, int32_t operand) {
    if (vm->code_len >= 4096) return;
    vm->code[vm->code_len++] = (Instr){op, operand};
}

static VM* vm_create(void) {
    VM* vm = (VM*)calloc(1, sizeof(VM));
    if (!vm) return NULL;
    vm_init(vm);
    vm->code = (Instr*)calloc(4096, sizeof(Instr));
    if (!vm->code) { free(vm); return NULL; }
    return vm;
}
static void vm_free(VM* vm) {
    heap_destroy(&vm->heap);
    free(vm->code);
    free(vm);
}

