/**
 * @file vm_run.c
 * @brief The bytecode interpreter's DISPATCH LOOP: fetch, decode, and route
 *        every opcode to its body.
 *
 * One interpreter, two dispatch mechanisms. On GCC/Clang each opcode handler
 * ends by jumping directly to the next handler through a label-address table
 * (computed-goto threading), which avoids the switch statement's bounds check
 * and indirect branch; every other compiler gets the plain `switch` loop
 * below the `#else`.
 *
 * The opcode bodies themselves live beside this file, one module per
 * responsibility, so that a fix to an opcode lands once instead of once per
 * dispatch mechanism:
 *
 *   vm_ops.c        numeric-operand guards, comparison, pair, vector and
 *                   operand-stack opcodes
 *   vm_frame.c      upvalue access, closure construction, the return sequence
 *   vm_control.c    continuation capture/resume, dynamic-wind rerooting,
 *                   the exception-handler stack
 *   vm_limits.c     the runaway-instruction guard and timeout checkpoint
 *   vm_lifecycle.c  vm_create()/vm_free() and the test-program assembler
 *   vm_native.c     the native-call trampoline OP_NATIVE_CALL dispatches to
 *
 * What stays inline here is what the two dispatch mechanisms do NOT share:
 * the arithmetic opcodes (only the threaded path records reverse-mode AD tape
 * nodes), the local-variable, string-accessor, call and call/cc bodies, and
 * the loop's own control flow.
 */

void vm_run(VM* vm) {
    const int owns_native_escape = !vm->native_escape_ready;
    if (owns_native_escape) {
        vm->native_escape_ready = 1;
        if (setjmp(vm->native_escape_jmp) != 0) {
            /* A handled raise or continuation crossed one or more native C
             * helper frames.  Its handler/continuation already restored pc,
             * stack, frames, winds, parameters, and promise state; resume the
             * owning interpreter loop from that exact state. */
            vm->native_call_depth = 0;
            vm->halted = 0;
            vm->error = 0;
        }
    }
#if defined(__GNUC__) || defined(__clang__)
/* =========================================================================
 * Computed-goto (threaded) dispatch — GCC/Clang only.
 *
 * Each handler ends with DISPATCH() which fetches the next instruction and
 * jumps directly to its handler via the dispatch_table, eliminating the
 * switch overhead (no bounds check, no indirect branch through a jump table
 * generated by the compiler — just a single indirect goto).
 * ========================================================================= */

    static void* dispatch_table[OP_COUNT] = {
        [OP_NOP]           = &&lbl_NOP,
        [OP_CONST]         = &&lbl_CONST,
        [OP_NIL]           = &&lbl_NIL,
        [OP_TRUE]          = &&lbl_TRUE,
        [OP_FALSE]         = &&lbl_FALSE,
        [OP_POP]           = &&lbl_POP,
        [OP_DUP]           = &&lbl_DUP,
        [OP_ADD]           = &&lbl_ADD,
        [OP_SUB]           = &&lbl_SUB,
        [OP_MUL]           = &&lbl_MUL,
        [OP_DIV]           = &&lbl_DIV,
        [OP_MOD]           = &&lbl_MOD,
        [OP_NEG]           = &&lbl_NEG,
        [OP_ABS]           = &&lbl_ABS,
        [OP_EQ]            = &&lbl_EQ,
        [OP_LT]            = &&lbl_LT,
        [OP_GT]            = &&lbl_GT,
        [OP_LE]            = &&lbl_LE,
        [OP_GE]            = &&lbl_GE,
        [OP_NOT]           = &&lbl_NOT,
        [OP_GET_LOCAL]     = &&lbl_GET_LOCAL,
        [OP_SET_LOCAL]     = &&lbl_SET_LOCAL,
        [OP_GET_UPVALUE]   = &&lbl_GET_UPVALUE,
        [OP_SET_UPVALUE]   = &&lbl_SET_UPVALUE,
        [OP_CLOSURE]       = &&lbl_CLOSURE,
        [OP_CALL]          = &&lbl_CALL,
        [OP_TAIL_CALL]     = &&lbl_TAIL_CALL,
        [OP_TAIL_CALL_POPN] = &&lbl_TAIL_CALL,
        [OP_RETURN]        = &&lbl_RETURN,
        [OP_JUMP]          = &&lbl_JUMP,
        [OP_JUMP_IF_FALSE] = &&lbl_JUMP_IF_FALSE,
        [OP_LOOP]          = &&lbl_LOOP,
        [OP_CONS]          = &&lbl_CONS,
        [OP_CAR]           = &&lbl_CAR,
        [OP_CDR]           = &&lbl_CDR,
        [OP_NULL_P]        = &&lbl_NULL_P,
        [OP_PRINT]         = &&lbl_PRINT,
        [OP_HALT]          = &&lbl_HALT,
        [OP_NATIVE_CALL]   = &&lbl_NATIVE_CALL,
        [OP_CLOSE_UPVALUE] = &&lbl_CLOSE_UPVALUE,
        [OP_VEC_CREATE]    = &&lbl_VEC_CREATE,
        [OP_VEC_REF]       = &&lbl_VEC_REF,
        [OP_VEC_SET]       = &&lbl_VEC_SET,
        [OP_VEC_LEN]       = &&lbl_VEC_LEN,
        [OP_STR_REF]       = &&lbl_STR_REF,
        [OP_STR_LEN]       = &&lbl_STR_LEN,
        [OP_PAIR_P]        = &&lbl_PAIR_P,
        [OP_NUM_P]         = &&lbl_NUM_P,
        [OP_STR_P]         = &&lbl_STR_P,
        [OP_BOOL_P]        = &&lbl_BOOL_P,
        [OP_PROC_P]        = &&lbl_PROC_P,
        [OP_VEC_P]         = &&lbl_VEC_P,
        [OP_SET_CAR]       = &&lbl_SET_CAR,
        [OP_SET_CDR]       = &&lbl_SET_CDR,
        [OP_POPN]          = &&lbl_POPN,
        [OP_OPEN_CLOSURE]  = &&lbl_NOP,
        [OP_CALLCC]        = &&lbl_CALLCC,
        [OP_INVOKE_CC]     = &&lbl_INVOKE_CC,
        [OP_PUSH_HANDLER]  = &&lbl_PUSH_HANDLER,
        [OP_POP_HANDLER]   = &&lbl_POP_HANDLER,
        [OP_GET_EXN]       = &&lbl_GET_EXN,
        [OP_PACK_REST]     = &&lbl_PACK_REST,
        [OP_WIND_PUSH]     = &&lbl_WIND_PUSH,
        [OP_WIND_POP]      = &&lbl_WIND_POP,
        [OP_VOID]          = &&lbl_VOID,
        [OP_LANGUAGE_COVERAGE] = &&lbl_LANGUAGE_COVERAGE,
        [OP_LANGUAGE_COVERAGE_CALL] = &&lbl_LANGUAGE_COVERAGE_CALL,
        [OP_GLOBAL_MARK]   = &&lbl_GLOBAL_MARK,
    };

    #define DISPATCH() do { \
        if (vm->halted || vm->error || vm->pc >= vm->code_len) goto vm_exit; \
        if (--vm_check_budget == 0) { \
            vm_check_budget = VM_CHECK_INTERVAL; \
            if (!vm_limits_checkpoint(vm, &vm->insns_executed, vm_max_insn)) \
                goto vm_exit; \
        } \
        instr = vm->code[vm->pc++]; \
        goto *dispatch_table[instr.op]; \
    } while(0)

    Instr instr;
    /* budget lives on the VM (vm->insns_executed) so it survives the
     * native-escape longjmp a continuation invoke performs; as a local it
     * reset to 0 on every re-entry and the runaway guard never tripped. */
    const uint64_t vm_max_insn = g_eshkol_vm_max_insn;
    unsigned vm_check_budget = VM_CHECK_INTERVAL;
    DISPATCH();

    /* --- Constants & Stack --- */

    lbl_NOP:
        DISPATCH();

    lbl_CONST:
        if (instr.operand < 0 || instr.operand >= vm->n_constants) {
            fprintf(stderr, "INVALID CONSTANT INDEX %d\n", instr.operand);
            vm->error = 1; goto vm_exit;
        }
        /* A literal constant is never a tape node; clear any stale mapping on
         * its slot so reverse-mode AD treats it as an ad_const operand rather
         * than reusing a prior node index left in ad_node_map (only when a tape
         * is active — a NULL check keeps non-AD execution untouched). */
        if (vm->active_tape && vm->sp >= 0 && vm->sp < STACK_SIZE)
            vm->ad_node_map[vm->sp] = -1;
        vm_push(vm, vm->constants[instr.operand]);
        DISPATCH();

    lbl_NIL:   vm_push(vm, NIL_VAL);     DISPATCH();
    lbl_TRUE:  vm_push(vm, BOOL_VAL(1)); DISPATCH();
    lbl_FALSE: vm_push(vm, BOOL_VAL(0)); DISPATCH();
    lbl_POP:   vm_pop(vm);               DISPATCH();
    lbl_DUP:   vm_push(vm, vm_peek(vm, 0)); DISPATCH();

    /* --- Arithmetic ---
     *
     * Reverse-mode AD tracing: when vm->active_tape is set, binary/unary
     * operations record on the Wengert tape in addition to computing values.
     * ad_node_map[stack_slot] tracks which tape node corresponds to each
     * stack value (-1 = untracked). Untracked operands that interact with
     * tracked ones are promoted to ad_const nodes on the tape.
     */

#define VM_AD_BINARY(vm, a_sp, b_sp, tape_fn, result_val) do { \
    if ((vm)->active_tape) { \
        AdTape* _t = (AdTape*)(vm)->active_tape; \
        int _an = (vm)->ad_node_map[(a_sp)]; \
        int _bn = (vm)->ad_node_map[(b_sp)]; \
        if (_an != -1 || _bn != -1) { \
            if (_an == -1) _an = ad_const(_t, as_number((vm)->stack[(a_sp)])); \
            if (_bn == -1) _bn = ad_const(_t, as_number((vm)->stack[(b_sp)])); \
            (vm)->ad_node_map[(vm)->sp] = tape_fn(_t, _an, _bn); \
        } else { (vm)->ad_node_map[(vm)->sp] = -1; } \
    } else { (vm)->ad_node_map[(vm)->sp] = -1; } \
} while(0)

#define VM_AD_UNARY(vm, a_sp, tape_fn) do { \
    if ((vm)->active_tape) { \
        AdTape* _t = (AdTape*)(vm)->active_tape; \
        int _an = (vm)->ad_node_map[(a_sp)]; \
        if (_an != -1) { \
            (vm)->ad_node_map[(vm)->sp] = tape_fn(_t, _an); \
        } else { (vm)->ad_node_map[(vm)->sp] = -1; } \
    } else { (vm)->ad_node_map[(vm)->sp] = -1; } \
} while(0)

    lbl_ADD: { int b_sp = vm->sp - 1, a_sp = vm->sp - 2;
        Value b = vm_pop(vm), a = vm_pop(vm);
        if (!vm_require_arithmetic_numbers(vm, a, b, "+")) DISPATCH();
        /* SW-09: neither operand check below recognizes VAL_I128, so a
         * generic `+` over i128 values used to fall all the way through to
         * the double path, where as_number_vm() reads a heap-boxed i128 as
         * 0.0 — silently answering 0 with exit 0. The VM has no i128
         * opcodes (that is v1.3.5 scope); raise instead of fabricating a
         * result. The native engine already raises for the same case
         * (LE-03, "Type error in +: expected number, vector, or tensor"). */
        if (a.type == VAL_I128 || b.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "+: i128 arithmetic is not supported on the VM (no i128 opcodes "
                "are implemented in the bytecode interpreter); use the native "
                "backend");
            DISPATCH();
        }
        if (a.type == VAL_HYPER_DUAL || b.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 1905); }
        else if (a.type == VAL_DUAL || b.type == VAL_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 373); }
        else if (a.type == VAL_RATIONAL || b.type == VAL_RATIONAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 331); }
        else if (a.type == VAL_COMPLEX || b.type == VAL_COMPLEX) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 307); }
        else if (vm_either_bignum(a, b)) { vm->ad_node_map[vm->sp] = -1; vm_bignum_arith(vm, a, b, '+'); }
        else if (a.type == VAL_INT && b.type == VAL_INT) { int64_t r; VM_AD_BINARY(vm, a_sp, b_sp, ad_add, 0);
            if (__builtin_add_overflow(a.as.i, b.as.i, &r)) vm_bignum_arith(vm, a, b, '+'); else vm_push(vm, INT_VAL(r)); }
        else { VM_AD_BINARY(vm, a_sp, b_sp, ad_add, 0);
            vm_push(vm, number_val_contagious(a, b, as_number_vm(vm, a) + as_number_vm(vm, b))); } DISPATCH(); }
    lbl_SUB: { int b_sp = vm->sp - 1, a_sp = vm->sp - 2;
        Value b = vm_pop(vm), a = vm_pop(vm);
        if (!vm_require_arithmetic_numbers(vm, a, b, "-")) DISPATCH();
        /* SW-09b: same family as lbl_ADD's guard — every arithmetic/
         * comparison opcode that falls through to as_number_vm() misreads
         * a heap-boxed VAL_I128 as 0.0. */
        if (a.type == VAL_I128 || b.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "-: i128 arithmetic is not supported on the VM (no i128 opcodes "
                "are implemented in the bytecode interpreter); use the native "
                "backend");
            DISPATCH();
        }
        if (a.type == VAL_HYPER_DUAL || b.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 1906); }
        else if (a.type == VAL_DUAL || b.type == VAL_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 374); }
        else if (a.type == VAL_RATIONAL || b.type == VAL_RATIONAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 332); }
        else if (a.type == VAL_COMPLEX || b.type == VAL_COMPLEX) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 308); }
        else if (vm_either_bignum(a, b)) { vm->ad_node_map[vm->sp] = -1; vm_bignum_arith(vm, a, b, '-'); }
        else if (a.type == VAL_INT && b.type == VAL_INT) { int64_t r; VM_AD_BINARY(vm, a_sp, b_sp, ad_sub, 0);
            if (__builtin_sub_overflow(a.as.i, b.as.i, &r)) vm_bignum_arith(vm, a, b, '-'); else vm_push(vm, INT_VAL(r)); }
        else { VM_AD_BINARY(vm, a_sp, b_sp, ad_sub, 0);
            vm_push(vm, number_val_contagious(a, b, as_number_vm(vm, a) - as_number_vm(vm, b))); } DISPATCH(); }
    lbl_MUL: { int b_sp = vm->sp - 1, a_sp = vm->sp - 2;
        Value b = vm_pop(vm), a = vm_pop(vm);
        if (!vm_require_arithmetic_numbers(vm, a, b, "*")) DISPATCH();
        /* SW-09b: see lbl_ADD/lbl_SUB. */
        if (a.type == VAL_I128 || b.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "*: i128 arithmetic is not supported on the VM (no i128 opcodes "
                "are implemented in the bytecode interpreter); use the native "
                "backend");
            DISPATCH();
        }
        if (a.type == VAL_HYPER_DUAL || b.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 1907); }
        else if (a.type == VAL_DUAL || b.type == VAL_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 375); }
        else if (a.type == VAL_RATIONAL || b.type == VAL_RATIONAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 333); }
        else if (a.type == VAL_COMPLEX || b.type == VAL_COMPLEX) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 309); }
        else if (vm_either_bignum(a, b)) { vm->ad_node_map[vm->sp] = -1; vm_bignum_arith(vm, a, b, '*'); }
        else if (a.type == VAL_INT && b.type == VAL_INT) { int64_t r; VM_AD_BINARY(vm, a_sp, b_sp, ad_mul, 0);
            if (__builtin_mul_overflow(a.as.i, b.as.i, &r)) vm_bignum_arith(vm, a, b, '*'); else vm_push(vm, INT_VAL(r)); }
        else { VM_AD_BINARY(vm, a_sp, b_sp, ad_mul, 0);
            vm_push(vm, number_val_contagious(a, b, as_number_vm(vm, a) * as_number_vm(vm, b))); } DISPATCH(); }
    lbl_DIV: { int b_sp = vm->sp - 1, a_sp = vm->sp - 2;
        Value b = vm_pop(vm), a = vm_pop(vm);
        if (!vm_require_arithmetic_numbers(vm, a, b, "/")) DISPATCH();
        /* SW-09b: see lbl_ADD/lbl_SUB/lbl_MUL. */
        if (a.type == VAL_I128 || b.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "/: i128 arithmetic is not supported on the VM (no i128 opcodes "
                "are implemented in the bytecode interpreter); use the native "
                "backend");
            DISPATCH();
        }
        if (a.type == VAL_HYPER_DUAL || b.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 1908); }
        else if (a.type == VAL_DUAL || b.type == VAL_DUAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 376); }
        else if (a.type == VAL_RATIONAL || b.type == VAL_RATIONAL) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 334); }
        else if (a.type == VAL_COMPLEX || b.type == VAL_COMPLEX) { vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 310); }
        else if (a.type == VAL_INT && b.type == VAL_INT) {
            /* exact/exact -> exact result (R7RS): native 334 (rational div)
             * reduces the fraction and collapses denom==1 back to an integer,
             * so (/ 1 3) yields 1/3 and (/ 6 3) yields 2 rather than the
             * inexact float the double path produced. */
            if (b.as.i == 0) { fprintf(stderr, "DIVIDE BY ZERO\n"); vm->error = 1; goto vm_exit; }
            vm_push(vm, a); vm_push(vm, b); vm_dispatch_native(vm, 334);
        }
        /* A bignum operand must reach the bignum domain: as_number() reads a
         * heap pointer's .as.i and answers 0.0, so falling through to the
         * double path below made every bignum division silently produce 0. */
        else if (vm_either_bignum(a, b)) { vm->ad_node_map[vm->sp] = -1; vm_bignum_arith(vm, a, b, '/'); if (vm->error) goto vm_exit; }
        else {
        double bd = as_number_vm(vm, b);
        /* Only EXACT-by-exact-zero is an error.  With any inexact operand this
         * is IEEE-754 division and must yield +nan.0 / ±inf.0 like native —
         * erroring here aborted the run and dropped every later top-level
         * form (tests/vm_parity/corpus/37_float_div_zero.esk). */
        if (bd == 0 && vm_is_exact_number(a) && vm_is_exact_number(b)) {
            fprintf(stderr, "DIVIDE BY ZERO\n"); vm->error = 1; goto vm_exit; }
        VM_AD_BINARY(vm, a_sp, b_sp, ad_div, 0);
        vm_push(vm, number_val_contagious(a, b, as_number_vm(vm, a) / bd)); } DISPATCH(); }
    lbl_MOD: {
        Value b = vm_pop(vm), a = vm_pop(vm);
        /* SW-09b: see lbl_ADD. modulo's double path (fmod) reads a
         * heap-boxed VAL_I128 as 0.0 exactly like the other arithmetic ops. */
        if (a.type == VAL_I128 || b.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "modulo: i128 arithmetic is not supported on the VM (no i128 "
                "opcodes are implemented in the bytecode interpreter); use the "
                "native backend");
            DISPATCH();
        }
        if (vm_either_bignum(a, b)) { vm->ad_node_map[vm->sp] = -1; vm_bignum_arith(vm, a, b, 'm'); DISPATCH(); }
        if (a.type == VAL_INT && b.type == VAL_INT) {
            if (b.as.i == 0) { fprintf(stderr, "MODULO BY ZERO\n"); vm->error = 1; goto vm_exit; }
            int64_t r = a.as.i % b.as.i; if (r != 0 && ((r ^ b.as.i) < 0)) r += b.as.i;
            vm_push(vm, INT_VAL(r)); DISPATCH();
        }
        double bd = as_number_vm(vm, b);
        if (bd == 0) { fprintf(stderr, "MODULO BY ZERO\n"); vm->error = 1; goto vm_exit; }
        double r = fmod(as_number_vm(vm, a), bd);
        if (r != 0 && ((r > 0) != (bd > 0))) r += bd;
        vm_push(vm, number_val_contagious(a, b, r));
        DISPATCH();
    }
    lbl_NEG: { int a_sp = vm->sp - 1; Value a = vm_pop(vm);
        /* SW-09b: see lbl_ADD. Unary negate has the same fall-through-to-
         * double shape as the binary ops. */
        if (a.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "-: i128 arithmetic is not supported on the VM (no i128 opcodes "
                "are implemented in the bytecode interpreter); use the native "
                "backend");
            DISPATCH();
        }
        if (a.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_dispatch_native(vm, 1909); }
        else if (a.type == VAL_DUAL) { vm_push(vm, a); vm_dispatch_native(vm, 384); }
        /* A rational must negate in the rational domain: falling through to the
         * double path read the heap pointer as 0.0, so (- 1/3) answered -0. */
        else if (a.type == VAL_RATIONAL) { vm_push(vm, a); vm_dispatch_native(vm, 335); }
        else if (a.type == VAL_BIGNUM) { vm->ad_node_map[vm->sp] = -1; vm_push_bignum_norm(vm, bignum_neg(&vm->heap.regions, (VmBignum*)vm->heap.objects[a.as.ptr]->opaque.ptr)); }
        else if (a.type == VAL_INT) { VM_AD_UNARY(vm, a_sp, ad_neg);
            if (a.as.i == INT64_MIN) vm_push_bignum_norm(vm, bignum_neg(&vm->heap.regions, bignum_from_int64(&vm->heap.regions, a.as.i)));
            else vm_push(vm, INT_VAL(-a.as.i)); }
        else { VM_AD_UNARY(vm, a_sp, ad_neg); vm_push(vm, number_val_contagious1(a, -as_number_vm(vm, a))); } DISPATCH(); }
    lbl_ABS: { int a_sp = vm->sp - 1; Value a = vm_pop(vm);
        /* SW-09b: see lbl_NEG. */
        if (a.type == VAL_I128) {
            vm_raise_error_msg(vm,
                "abs: i128 arithmetic is not supported on the VM (no i128 "
                "opcodes are implemented in the bytecode interpreter); use the "
                "native backend");
            DISPATCH();
        }
        if (a.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_dispatch_native(vm, 1916); }
        else if (a.type == VAL_DUAL) { vm_push(vm, a); vm_dispatch_native(vm, 383); }
        /* See lbl_NEG: (abs 1/3) answered 0 through the double path. */
        else if (a.type == VAL_RATIONAL) { vm_push(vm, a); vm_dispatch_native(vm, 336); }
        else if (a.type == VAL_BIGNUM) { vm->ad_node_map[vm->sp] = -1; vm_push_bignum_norm(vm, bignum_abs_val(&vm->heap.regions, (VmBignum*)vm->heap.objects[a.as.ptr]->opaque.ptr)); }
        else if (a.type == VAL_INT) { VM_AD_UNARY(vm, a_sp, ad_abs);
            if (a.as.i == INT64_MIN) vm_push_bignum_norm(vm, bignum_abs_val(&vm->heap.regions, bignum_from_int64(&vm->heap.regions, a.as.i)));
            else vm_push(vm, INT_VAL(a.as.i < 0 ? -a.as.i : a.as.i)); }
        else { VM_AD_UNARY(vm, a_sp, ad_abs); vm_push(vm, number_val_contagious1(a, fabs(as_number_vm(vm, a)))); } DISPATCH(); }

    /* --- Comparison --- */

    lbl_EQ: vm_exec_eq(vm); DISPATCH();
    lbl_LT: vm_exec_lt(vm); DISPATCH();
    lbl_GT: vm_exec_gt(vm); DISPATCH();
    lbl_LE: vm_exec_le(vm); DISPATCH();
    lbl_GE: vm_exec_ge(vm); DISPATCH();
    lbl_NOT: { Value a = vm_pop(vm); vm_push(vm, BOOL_VAL(!is_truthy(a))); DISPATCH(); }

    /* --- Variables --- */

    lbl_GET_LOCAL: {
        int src = vm->fp + instr.operand;
        if (src < 0 || src >= STACK_SIZE) {
            fprintf(stderr, "GET_LOCAL: index %d out of bounds [0, %d)\n", src, STACK_SIZE);
            vm->error = 1; goto vm_exit;
        }
        if (vm->sp >= 0 && vm->sp < STACK_SIZE)
            vm->ad_node_map[vm->sp] = vm->ad_node_map[src];
        vm_push(vm, vm->stack[src]);
        DISPATCH(); }
    lbl_SET_LOCAL: {
        int dst = vm->fp + instr.operand;
        if (dst < 0 || dst >= STACK_SIZE) {
            fprintf(stderr, "SET_LOCAL: index %d out of bounds [0, %d)\n", dst, STACK_SIZE);
            vm->error = 1; goto vm_exit;
        }
        if (vm->sp > 0 && vm->sp <= STACK_SIZE)
            vm->ad_node_map[dst] = vm->ad_node_map[vm->sp - 1];
        vm->stack[dst] = vm_peek(vm, 0);
        vm_pop(vm);
        DISPATCH(); }
    lbl_GET_UPVALUE: vm_exec_get_upvalue(vm, instr.operand); DISPATCH();
    lbl_SET_UPVALUE: vm_exec_set_upvalue(vm, instr.operand); DISPATCH();

    /* --- Closures --- */

    lbl_CLOSURE: vm_exec_closure(vm, instr.operand); DISPATCH();

    /* --- Function call --- */

    lbl_CALL: {
        int argc = instr.operand;
        Value func = vm->stack[vm->sp - 1 - argc];

        vm_language_coverage_named_call(vm, func);

        if (func.type == VAL_PARAMETER_OBJ) {
            Value result = vm_parameter_invoke(vm, func, &vm->stack[vm->sp - argc], argc);
            vm->sp -= argc + 1;
            vm_push(vm, result);
            DISPATCH();
        }

        /* Continuation invocation: (k value) */
        if (func.type == VAL_CONTINUATION && argc >= 1) {
            Value val = vm->stack[vm->sp - 1];
            VmContinuation* cont = (VmContinuation*)vm->heap.objects[func.as.ptr]->opaque.ptr;
            if (cont) {
                vm_continuation_resume(vm, cont, val);
                DISPATCH();
            }
        }

        if (func.type != VAL_CLOSURE) {
            fprintf(stderr,
                    "ERROR: calling non-function at pc=%d argc=%d type=%d\n",
                    vm->pc - 1, argc, (int)func.type);
            vm->error = 1; goto vm_exit;
        }

        HeapObject* cl = vm->heap.objects[func.as.ptr];

        if (vm->frame_count >= MAX_FRAMES) { fprintf(stderr, "FRAME OVERFLOW\n"); vm->error = 1; goto vm_exit; }
        vm->frames[vm->frame_count].return_pc = vm->pc;
        vm->frames[vm->frame_count].return_fp = vm->fp;
        vm->frames[vm->frame_count].func_pc = cl->closure.func_pc;
        vm->frame_count++;

        vm->fp = vm->sp - argc;
        vm->pc = cl->closure.func_pc;
        DISPATCH();
    }

    lbl_TAIL_CALL: {
        int argc = instr.op == OP_TAIL_CALL_POPN
                       ? (instr.operand & 0xFFFF) : instr.operand;
        Value func = vm->stack[vm->sp - 1 - argc];
        vm_language_coverage_named_call(vm, func);
        if (func.type == VAL_PARAMETER_OBJ) {
            Value result = vm_parameter_invoke(vm, func, &vm->stack[vm->sp - argc], argc);
            if (vm->frame_count <= 0) {
                vm->sp = 0;
                vm_push(vm, result);
                vm->halted = 1;
                goto vm_exit;
            }
            vm->frame_count--;
            if (vm->frames[vm->frame_count].return_pc == -1) {
                vm->sp = 0;
                vm_push(vm, result);
                vm->halted = 1;
                goto vm_exit;
            }
            vm->sp = vm->fp - 1;
            vm->fp = vm->frames[vm->frame_count].return_fp;
            vm->pc = vm->frames[vm->frame_count].return_pc;
            vm_push(vm, result);
            DISPATCH();
        }
        /* Continuation invocation in tail position */
        if (func.type == VAL_CONTINUATION && argc >= 1) {
            Value val = vm->stack[vm->sp - 1];
            VmContinuation* cont = (VmContinuation*)vm->heap.objects[func.as.ptr]->opaque.ptr;
            if (cont) {
                vm_continuation_resume(vm, cont, val);
                DISPATCH();
            }
        }
        if (func.type != VAL_CLOSURE) { vm->error = 1; goto vm_exit; }
        HeapObject* cl = vm->heap.objects[func.as.ptr];

        for (int i = 0; i < argc; i++) {
            vm->stack[vm->fp + i] = vm->stack[vm->sp - argc + i];
        }
        vm->sp = vm->fp + argc;
        /* Update closure slot so GET_UPVALUE sees the NEW closure's upvalues */
        vm->stack[vm->fp - 1] = func;
        vm->pc = cl->closure.func_pc;
        DISPATCH();
    }

    lbl_RETURN: vm_exec_return(vm); DISPATCH();

    /* --- Control Flow --- */

    lbl_JUMP:
        vm->pc = instr.operand;
        DISPATCH();
    lbl_JUMP_IF_FALSE: {
        Value cond = vm_pop(vm);
        if (!is_truthy(cond)) vm->pc = instr.operand;
        DISPATCH();
    }
    lbl_LOOP:
        vm->pc = instr.operand;
        DISPATCH();

    /* --- Pairs --- */

    lbl_CONS: vm_exec_cons(vm); DISPATCH();
    lbl_CAR: vm_exec_car(vm); DISPATCH();
    lbl_CDR: vm_exec_cdr(vm); DISPATCH();
    lbl_NULL_P: {
        Value v = vm_pop(vm);
        vm_push(vm, BOOL_VAL(v.type == VAL_NIL));
        DISPATCH();
    }

    /* --- I/O --- */

    lbl_PRINT: {
        Value v = vm_pop(vm);
        if (v.type != VAL_VOID) {
            print_value(vm, v);
            printf("\n"); fflush(stdout);
            if (vm->n_outputs < 256) vm->outputs[vm->n_outputs++] = v;
        }
        DISPATCH();
    }

    lbl_VOID:
        vm_push(vm, (Value){.type = VAL_VOID});
        DISPATCH();

    lbl_LANGUAGE_COVERAGE:
        DISPATCH();

    lbl_LANGUAGE_COVERAGE_CALL:
        vm->language_coverage_call_hash = (uint32_t)instr.operand;
        vm->language_coverage_call_pc = vm->pc;
        DISPATCH();

    lbl_HALT:
        vm->halted = 1;
        goto vm_exit;

    lbl_NATIVE_CALL: {
        vm_language_coverage_native_dispatch(vm, instr.operand);
        vm_dispatch_native(vm, instr.operand);
        DISPATCH();
    }

    lbl_CLOSE_UPVALUE: vm_exec_close_upvalue(vm, instr.operand); DISPATCH();

    lbl_VEC_CREATE: vm_exec_vec_create(vm, instr.operand); DISPATCH();

    lbl_VEC_REF: vm_exec_vec_ref(vm); DISPATCH();

    lbl_VEC_SET: vm_exec_vec_set(vm); DISPATCH();

    lbl_VEC_LEN: vm_exec_vec_len(vm); DISPATCH();

    /* The threaded (computed-goto) bodies below and the switch-based fallback
     * further down are the two halves of the same interpreter; the inline
     * string accessor fast paths must enforce the same catchable
     * out-of-range contract as the native codegen in BOTH.  See
     * vm_raise_error_msg() in vm_native.c. */
    lbl_STR_REF: {
        Value idx = vm_pop(vm), str_val = vm_pop(vm);
        if (str_val.type == VAL_STRING) {
            VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
            int i = (int)as_number(idx);
            if (!s || i < 0 || i >= s->byte_len) {
                vm_raise_error_msg(vm, "string-ref: index out of bounds");
                DISPATCH();
            }
            /* R7RS string-ref returns a character, not its integer code. */
            vm_push(vm, (Value){.type = VAL_CHAR, .as.i = (unsigned char)s->data[i]});
        } else vm_push(vm, (Value){.type = VAL_CHAR, .as.i = 0});
        DISPATCH();
    }

    lbl_STR_LEN: {
        Value str_val = vm_pop(vm);
        if (str_val.type == VAL_STRING) {
            VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
            vm_push(vm, INT_VAL(s ? s->byte_len : 0));
        } else vm_push(vm, INT_VAL(0));
        DISPATCH();
    }

    lbl_PAIR_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_PAIR)); DISPATCH(); }
    /* SW-31: number? is the WHOLE tower, not just fixnum/flonum. This single
     * opcode also used to serve `integer?` and `real?`, which is how
     * (integer? 5.5) answered #t; those now lower to their own natives. */
    lbl_NUM_P:   { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(vm_tag_is_number(v))); DISPATCH(); }
    lbl_STR_P:   { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_STRING)); DISPATCH(); }
    lbl_BOOL_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_BOOL)); DISPATCH(); }
    lbl_PROC_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_CLOSURE)); DISPATCH(); }
    lbl_VEC_P:   { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_VECTOR)); DISPATCH(); }

    lbl_SET_CAR: vm_exec_set_car(vm); DISPATCH();
    lbl_SET_CDR: vm_exec_set_cdr(vm); DISPATCH();

    lbl_POPN: vm_exec_popn(vm, instr.operand); DISPATCH();

    lbl_CALLCC: {
        Value proc = vm_pop(vm);
        if (proc.type != VAL_CLOSURE) { vm_push(vm, NIL_VAL); DISPATCH(); }
        /* Validate bounds before capture */
        if (vm->sp > STACK_SIZE || vm->frame_count > MAX_FRAMES) { vm->error = 1; goto vm_exit; }
        int32_t cont_ptr = heap_alloc(&vm->heap);
        if (cont_ptr < 0) { vm->error = 1; goto vm_exit; }
        vm->heap.objects[cont_ptr]->type = HEAP_CONTINUATION;
        /* Store: pc, fp, sp, frame_count, n_handlers, n_winds + copy of stack + frames */
        VmContinuation* cont = (VmContinuation*)vm_alloc(&vm->heap.regions,
            vm_continuation_allocation_size(vm));
        if (!cont) { vm->error = 1; goto vm_exit; }
        cont->pc = vm->pc; cont->fp = vm->fp; cont->sp = vm->sp;
        cont->frame_count = vm->frame_count;
        cont->n_handlers = vm->n_handlers;
        cont->promise_mark = vm->promise_eval_head;
        vm_capture_continuation_stack(vm, cont);
        vm_capture_continuation_dynamic_state(vm, cont);
        vm->heap.objects[cont_ptr]->opaque.ptr = cont;
        /* Create continuation closure: a special closure that invokes OP_INVOKE_CC */
        Value cont_val = (Value){.type = VAL_CONTINUATION, .as.ptr = cont_ptr};
        /* Call proc(continuation) */
        vm_push(vm, proc);
        vm_push(vm, cont_val);
        /* Set up call frame for proc(k) */
        HeapObject* cl_cc = vm->heap.objects[proc.as.ptr];
        if (vm->frame_count >= MAX_FRAMES) { vm->error = 1; goto vm_exit; }
        vm->frames[vm->frame_count].return_pc = vm->pc;
        vm->frames[vm->frame_count].return_fp = vm->fp;
        vm->frames[vm->frame_count].func_pc = cl_cc->closure.func_pc;
        vm->frame_count++;
        vm->fp = vm->sp - 1; /* 1 arg: the continuation */
        vm->pc = cl_cc->closure.func_pc;
        DISPATCH();
    }

    lbl_PUSH_HANDLER: vm_exec_push_handler(vm, instr.operand); DISPATCH();

    lbl_POP_HANDLER: {
        if (vm->n_handlers > 0) vm->n_handlers--;
        DISPATCH();
    }

    lbl_GET_EXN: {
        vm_push(vm, vm->current_exception);
        DISPATCH();
    }

    lbl_INVOKE_CC: vm_exec_invoke_cc(vm); DISPATCH();

    lbl_PACK_REST: {
        int n_fixed = instr.operand;
        int n_args = vm->sp - vm->fp;
        Value list = NIL_VAL;
        for (int i = n_args - 1; i >= n_fixed; i--) {
            Value item = vm->stack[vm->fp + i];
            int32_t p = heap_alloc(&vm->heap);
            if (p < 0) { vm->error = 1; goto vm_exit; }
            vm->heap.objects[p]->type = HEAP_CONS;
            vm->heap.objects[p]->cons.car = item;
            vm->heap.objects[p]->cons.cdr = list;
            list = PAIR_VAL(p);
        }
        vm->sp = vm->fp + n_fixed;
        vm_push(vm, list);
        DISPATCH();
    }

    lbl_WIND_PUSH: {
        /* The compiler has already called `before`; it leaves the before
         * closure below the after closure so the entry can record BOTH.
         * `before` is what a continuation re-entering this extent must run
         * again (see vm_reroot_winds). */
        Value after = vm_pop(vm);
        Value before = vm_pop(vm);
        if (vm->n_winds >= 32) { fprintf(stderr, "WIND STACK OVERFLOW\n"); vm->error = 1; goto vm_exit; }
        vm->wind_stack[vm->n_winds].before = before;
        vm->wind_stack[vm->n_winds].after = after;
        vm->n_winds++;
        DISPATCH();
    }

    lbl_WIND_POP: {
        /* Normal-path after invocation is emitted explicitly by the
         * compiler.  This opcode only removes the exceptional-exit guard. */
        if (vm->n_winds > 0) vm->n_winds--;
        DISPATCH();
    }

    lbl_GLOBAL_MARK: {
        /* Raise the STORE/CONTROL boundary. Monotonic: a top-level binding,
         * once established, stays established even if a continuation
         * re-entry rewinds the instruction pointer past its define. */
        if (instr.operand > vm->global_top) vm->global_top = instr.operand;
        DISPATCH();
    }

vm_exit:
    #undef DISPATCH
    if (owns_native_escape) vm->native_escape_ready = 0;

#else
/* =========================================================================
 * Fallback: standard switch dispatch for non-GCC/Clang compilers (MSVC etc.)
 * ========================================================================= */

    /* Same guard and the same configurable ceiling as the computed-goto path
     * above, so the two dispatch implementations of this one interpreter agree
     * about when a program has run away. */
    /* budget lives on the VM (vm->insns_executed) so it survives the
     * native-escape longjmp a continuation invoke performs; as a local it
     * reset to 0 on every re-entry and the runaway guard never tripped. */
    const uint64_t vm_max_insn = g_eshkol_vm_max_insn;
    unsigned vm_check_budget = VM_CHECK_INTERVAL;
    while (!vm->halted && !vm->error && vm->pc < vm->code_len) {
        if (--vm_check_budget == 0) {
            vm_check_budget = VM_CHECK_INTERVAL;
            if (!vm_limits_checkpoint(vm, &vm->insns_executed, vm_max_insn)) break;
        }
        Instr instr = vm->code[vm->pc++];

        switch (instr.op) {
        case OP_NOP: break;

        case OP_CONST:
            if (instr.operand < 0 || instr.operand >= vm->n_constants) {
                fprintf(stderr, "INVALID CONSTANT INDEX %d\n", instr.operand);
                vm->error = 1; break;
            }
            vm_push(vm, vm->constants[instr.operand]);
            break;

        case OP_NIL:   vm_push(vm, NIL_VAL); break;
        case OP_TRUE:  vm_push(vm, BOOL_VAL(1)); break;
        case OP_FALSE: vm_push(vm, BOOL_VAL(0)); break;
        case OP_POP:   vm_pop(vm); break;
        case OP_DUP:   vm_push(vm, vm_peek(vm, 0)); break;

        /* Arithmetic */
        case OP_ADD: { Value b = vm_pop(vm), a = vm_pop(vm);
            if (!vm_require_arithmetic_numbers(vm, a, b, "+")) break;
            /* SW-09: see the identical guard in lbl_ADD above — this switch-
             * based loop is the non-computed-goto twin of the same opcode
             * and must reject i128 operands the same way, not silently
             * coerce them to 0.0 via as_number_vm(). */
            if (a.type == VAL_I128 || b.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "+: i128 arithmetic is not supported on the VM (no i128 opcodes "
                    "are implemented in the bytecode interpreter); use the native "
                    "backend");
                break;
            }
            if (a.type==VAL_HYPER_DUAL||b.type==VAL_HYPER_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,1905); }
            else if (a.type==VAL_DUAL||b.type==VAL_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,373); }
            else if (a.type==VAL_RATIONAL||b.type==VAL_RATIONAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,331); }
            else if (a.type==VAL_COMPLEX||b.type==VAL_COMPLEX) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,307); }
            else if (vm_either_bignum(a,b)) vm_bignum_arith(vm,a,b,'+');
            else if (a.type==VAL_INT && b.type==VAL_INT) { int64_t r; if (__builtin_add_overflow(a.as.i,b.as.i,&r)) vm_bignum_arith(vm,a,b,'+'); else vm_push(vm, INT_VAL(r)); }
            else vm_push(vm, number_val_contagious(a, b, as_number_vm(vm,a) + as_number_vm(vm,b))); break; }
        case OP_SUB: { Value b = vm_pop(vm), a = vm_pop(vm);
            if (!vm_require_arithmetic_numbers(vm, a, b, "-")) break;
            /* SW-09b: switch-based twin of lbl_SUB. */
            if (a.type == VAL_I128 || b.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "-: i128 arithmetic is not supported on the VM (no i128 opcodes "
                    "are implemented in the bytecode interpreter); use the native "
                    "backend");
                break;
            }
            if (a.type==VAL_HYPER_DUAL||b.type==VAL_HYPER_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,1906); }
            else if (a.type==VAL_DUAL||b.type==VAL_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,374); }
            else if (a.type==VAL_RATIONAL||b.type==VAL_RATIONAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,332); }
            else if (a.type==VAL_COMPLEX||b.type==VAL_COMPLEX) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,308); }
            else if (vm_either_bignum(a,b)) vm_bignum_arith(vm,a,b,'-');
            else if (a.type==VAL_INT && b.type==VAL_INT) { int64_t r; if (__builtin_sub_overflow(a.as.i,b.as.i,&r)) vm_bignum_arith(vm,a,b,'-'); else vm_push(vm, INT_VAL(r)); }
            else vm_push(vm, number_val_contagious(a, b, as_number_vm(vm,a) - as_number_vm(vm,b))); break; }
        case OP_MUL: { Value b = vm_pop(vm), a = vm_pop(vm);
            if (!vm_require_arithmetic_numbers(vm, a, b, "*")) break;
            /* SW-09b: switch-based twin of lbl_MUL. */
            if (a.type == VAL_I128 || b.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "*: i128 arithmetic is not supported on the VM (no i128 opcodes "
                    "are implemented in the bytecode interpreter); use the native "
                    "backend");
                break;
            }
            if (a.type==VAL_HYPER_DUAL||b.type==VAL_HYPER_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,1907); }
            else if (a.type==VAL_DUAL||b.type==VAL_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,375); }
            else if (a.type==VAL_RATIONAL||b.type==VAL_RATIONAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,333); }
            else if (a.type==VAL_COMPLEX||b.type==VAL_COMPLEX) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,309); }
            else if (vm_either_bignum(a,b)) vm_bignum_arith(vm,a,b,'*');
            else if (a.type==VAL_INT && b.type==VAL_INT) { int64_t r; if (__builtin_mul_overflow(a.as.i,b.as.i,&r)) vm_bignum_arith(vm,a,b,'*'); else vm_push(vm, INT_VAL(r)); }
            else vm_push(vm, number_val_contagious(a, b, as_number_vm(vm,a) * as_number_vm(vm,b))); break; }
        case OP_DIV: { Value b = vm_pop(vm), a = vm_pop(vm);
            if (!vm_require_arithmetic_numbers(vm, a, b, "/")) break;
            /* SW-09b: switch-based twin of lbl_DIV. */
            if (a.type == VAL_I128 || b.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "/: i128 arithmetic is not supported on the VM (no i128 opcodes "
                    "are implemented in the bytecode interpreter); use the native "
                    "backend");
                break;
            }
            if (a.type==VAL_HYPER_DUAL||b.type==VAL_HYPER_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,1908); }
            else if (a.type==VAL_DUAL||b.type==VAL_DUAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,376); }
            else if (a.type==VAL_RATIONAL||b.type==VAL_RATIONAL) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,334); }
            else if (a.type==VAL_COMPLEX||b.type==VAL_COMPLEX) { vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,310); }
            else if (a.type==VAL_INT && b.type==VAL_INT) {
                /* exact/exact → exact result (R7RS): native 334 (rational div)
                 * reduces the fraction and collapses denom==1 back to an
                 * integer, so (/ 1 3) yields 1/3 and (/ 6 3) yields 2 rather
                 * than the inexact float the double path produced. */
                if (b.as.i == 0) { fprintf(stderr, "DIVIDE BY ZERO\n"); vm->error = 1; break; }
                vm_push(vm,a); vm_push(vm,b); vm_dispatch_native(vm,334);
            }
            /* See the threaded-dispatch OP_DIV above: bignums need the bignum
             * domain, and only EXACT-by-exact-zero is an error. */
            else if (vm_either_bignum(a,b)) { vm_bignum_arith(vm,a,b,'/'); }
            else { double bd = as_number_vm(vm,b);
            if (bd == 0 && vm_is_exact_number(a) && vm_is_exact_number(b)) {
                fprintf(stderr, "DIVIDE BY ZERO\n"); vm->error = 1; break; }
            vm_push(vm, number_val_contagious(a, b, as_number_vm(vm,a) / bd)); } break; }
        case OP_MOD: {
            Value b = vm_pop(vm), a = vm_pop(vm);
            /* SW-09b: switch-based twin of lbl_MOD. */
            if (a.type == VAL_I128 || b.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "modulo: i128 arithmetic is not supported on the VM (no i128 "
                    "opcodes are implemented in the bytecode interpreter); use the "
                    "native backend");
                break;
            }
            if (vm_either_bignum(a, b)) { vm_bignum_arith(vm, a, b, 'm'); break; }
            if (a.type == VAL_INT && b.type == VAL_INT) {
                if (b.as.i == 0) { fprintf(stderr, "MODULO BY ZERO\n"); vm->error = 1; break; }
                int64_t r = a.as.i % b.as.i; if (r != 0 && ((r ^ b.as.i) < 0)) r += b.as.i;
                vm_push(vm, INT_VAL(r)); break;
            }
            double bd = as_number_vm(vm, b);
            if (bd == 0) { fprintf(stderr, "MODULO BY ZERO\n"); vm->error = 1; break; }
            double r = fmod(as_number_vm(vm, a), bd);
            if (r != 0 && ((r > 0) != (bd > 0))) r += bd;
            vm_push(vm, number_val_contagious(a, b, r));
            break;
        }
        case OP_NEG: { Value a = vm_pop(vm);
            /* SW-09b: switch-based twin of lbl_NEG. */
            if (a.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "-: i128 arithmetic is not supported on the VM (no i128 opcodes "
                    "are implemented in the bytecode interpreter); use the native "
                    "backend");
                break;
            }
            /* See the threaded lbl_NEG: a rational needs the rational domain;
             * the double path below reads its heap pointer as 0.0. */
            if (a.type == VAL_RATIONAL) { vm_push(vm, a); vm_dispatch_native(vm, 335); break; }
            if (a.type == VAL_BIGNUM) { vm_push_bignum_norm(vm, bignum_neg(&vm->heap.regions, (VmBignum*)vm->heap.objects[a.as.ptr]->opaque.ptr)); break; }
            if (a.type == VAL_INT && a.as.i != INT64_MIN) { vm_push(vm, INT_VAL(-a.as.i)); break; }
            if (a.type == VAL_INT) { vm_push_bignum_norm(vm, bignum_neg(&vm->heap.regions, bignum_from_int64(&vm->heap.regions, a.as.i))); break; }
            vm_push(vm, number_val_contagious1(a, -as_number_vm(vm, a))); break; }
        case OP_ABS: { Value a = vm_pop(vm);
            /* SW-09b: switch-based twin of lbl_ABS. */
            if (a.type == VAL_I128) {
                vm_raise_error_msg(vm,
                    "abs: i128 arithmetic is not supported on the VM (no i128 "
                    "opcodes are implemented in the bytecode interpreter); use the "
                    "native backend");
                break;
            }
            /* SW-40: this switch arm is the twin of lbl_ABS and must carry the
             * SAME carrier arms. It was missing both AD ones, so on a build
             * that uses the switch dispatch (no computed-goto — the Windows/
             * MSVC lane) a derivative through `abs` fell to the double path,
             * which discards the tangent and answers 0. The computed-goto loop
             * has had these two lines all along; the twin simply drifted. */
            if (a.type == VAL_HYPER_DUAL) { vm_push(vm, a); vm_dispatch_native(vm, 1916); break; }
            if (a.type == VAL_DUAL) { vm_push(vm, a); vm_dispatch_native(vm, 383); break; }
            if (a.type == VAL_RATIONAL) { vm_push(vm, a); vm_dispatch_native(vm, 336); break; }
            if (a.type == VAL_BIGNUM) { vm_push_bignum_norm(vm, bignum_abs_val(&vm->heap.regions, (VmBignum*)vm->heap.objects[a.as.ptr]->opaque.ptr)); break; }
            if (a.type == VAL_INT && a.as.i != INT64_MIN) { vm_push(vm, INT_VAL(a.as.i < 0 ? -a.as.i : a.as.i)); break; }
            if (a.type == VAL_INT) { vm_push_bignum_norm(vm, bignum_abs_val(&vm->heap.regions, bignum_from_int64(&vm->heap.regions, a.as.i))); break; }
            vm_push(vm, number_val_contagious1(a, fabs(as_number_vm(vm, a)))); break; }

        /* Comparison — push proper booleans */
        case OP_EQ: vm_exec_eq(vm); break;
        case OP_LT: vm_exec_lt(vm); break;
        case OP_GT: vm_exec_gt(vm); break;
        case OP_LE: vm_exec_le(vm); break;
        case OP_GE: vm_exec_ge(vm); break;
        case OP_NOT: { Value a = vm_pop(vm); vm_push(vm, BOOL_VAL(!is_truthy(a))); break; }

        /* Variables */
        case OP_GET_LOCAL: {
            int src = vm->fp + instr.operand;
            if (src >= 0 && src < STACK_SIZE && vm->sp < STACK_SIZE)
                vm->ad_node_map[vm->sp] = vm->ad_node_map[src];
            vm_push(vm, vm->stack[src]);
            break; }
        case OP_SET_LOCAL:
            vm->stack[vm->fp + instr.operand] = vm_peek(vm, 0);
            vm_pop(vm);
            break;
        case OP_GET_UPVALUE: vm_exec_get_upvalue(vm, instr.operand); break;
        case OP_SET_UPVALUE: vm_exec_set_upvalue(vm, instr.operand); break;

        /* Closures */
        case OP_CLOSURE: vm_exec_closure(vm, instr.operand); break;

        /* Function call */
        case OP_CALL: {
            int argc = instr.operand;
            Value func = vm->stack[vm->sp - 1 - argc]; /* function is below args */

            vm_language_coverage_named_call(vm, func);

            if (func.type == VAL_PARAMETER_OBJ) {
                Value result = vm_parameter_invoke(vm, func,
                    &vm->stack[vm->sp - argc], argc);
                vm->sp -= argc + 1;
                vm_push(vm, result);
                break;
            }

            /* Continuation invocation: (k value) */
            if (func.type == VAL_CONTINUATION && argc >= 1) {
                Value val = vm->stack[vm->sp - 1];
                VmContinuation* cont = (VmContinuation*)vm->heap.objects[func.as.ptr]->opaque.ptr;
                if (cont) {
                    vm_continuation_resume(vm, cont, val);
                }
                break;
            }

            if (func.type != VAL_CLOSURE) {
                fprintf(stderr,
                        "ERROR: calling non-function at pc=%d argc=%d type=%d\n",
                        vm->pc - 1, argc, (int)func.type);
                vm->error = 1; break;
            }

            HeapObject* cl = vm->heap.objects[func.as.ptr];

            /* Save call frame */
            if (vm->frame_count >= MAX_FRAMES) { fprintf(stderr, "FRAME OVERFLOW\n"); vm->error = 1; break; }
            vm->frames[vm->frame_count].return_pc = vm->pc;
            vm->frames[vm->frame_count].return_fp = vm->fp;
            vm->frames[vm->frame_count].func_pc = cl->closure.func_pc;
            vm->frame_count++;

            /* Set up new frame: func sits at sp-argc-1, args at sp-argc..sp-1 */
            vm->fp = vm->sp - argc;
            vm->pc = cl->closure.func_pc;
            break;
        }

        case OP_TAIL_CALL:
        case OP_TAIL_CALL_POPN: {
            int argc = instr.op == OP_TAIL_CALL_POPN
                           ? (instr.operand & 0xFFFF) : instr.operand;
            Value func = vm->stack[vm->sp - 1 - argc];
            vm_language_coverage_named_call(vm, func);
            if (func.type == VAL_PARAMETER_OBJ) {
                Value result = vm_parameter_invoke(vm, func,
                    &vm->stack[vm->sp - argc], argc);
                if (vm->frame_count <= 0) {
                    vm->sp = 0;
                    vm_push(vm, result);
                    vm->halted = 1;
                    break;
                }
                vm->frame_count--;
                if (vm->frames[vm->frame_count].return_pc == -1) {
                    vm->sp = 0;
                    vm_push(vm, result);
                    vm->halted = 1;
                    break;
                }
                vm->sp = vm->fp - 1;
                vm->fp = vm->frames[vm->frame_count].return_fp;
                vm->pc = vm->frames[vm->frame_count].return_pc;
                vm_push(vm, result);
                break;
            }
            if (func.type == VAL_CONTINUATION && argc >= 1) {
                Value val = vm->stack[vm->sp - 1];
                VmContinuation* cont = (VmContinuation*)
                    vm->heap.objects[func.as.ptr]->opaque.ptr;
                if (cont) {
                    vm_continuation_resume(vm, cont, val);
                }
                break;
            }
            if (func.type != VAL_CLOSURE) { vm->error = 1; break; }
            HeapObject* cl = vm->heap.objects[func.as.ptr];

            /* Move args to current frame position (reuse frame) */
            for (int i = 0; i < argc; i++) {
                vm->stack[vm->fp + i] = vm->stack[vm->sp - argc + i];
            }
            vm->sp = vm->fp + argc;
            /* Update closure slot so GET_UPVALUE sees the NEW closure's upvalues */
            vm->stack[vm->fp - 1] = func;
            vm->pc = cl->closure.func_pc;
            break;
        }

        case OP_RETURN: vm_exec_return(vm); break;

        /* Control Flow */
        case OP_JUMP:
            vm->pc = instr.operand;
            break;
        case OP_JUMP_IF_FALSE: {
            Value cond = vm_pop(vm);
            if (!is_truthy(cond)) vm->pc = instr.operand;
            break;
        }
        case OP_LOOP:
            vm->pc = instr.operand;
            break;

        /* Pairs */
        case OP_CONS: vm_exec_cons(vm); break;
        case OP_CAR: vm_exec_car(vm); break;
        case OP_CDR: vm_exec_cdr(vm); break;
        case OP_NULL_P: {
            Value v = vm_pop(vm);
            vm_push(vm, BOOL_VAL(v.type == VAL_NIL));
            break;
        }

        /* I/O */
        case OP_PRINT: {
            Value v = vm_pop(vm);
            if (v.type != VAL_VOID) {
                print_value(vm, v);
                printf("\n");
                if (vm->n_outputs < 256) vm->outputs[vm->n_outputs++] = v;
            }
            break;
        }

        case OP_VOID:
            vm_push(vm, (Value){.type = VAL_VOID});
            break;

        case OP_LANGUAGE_COVERAGE:
            break;

        case OP_LANGUAGE_COVERAGE_CALL:
            vm->language_coverage_call_hash = (uint32_t)instr.operand;
            vm->language_coverage_call_pc = vm->pc;
            break;

        case OP_HALT:
            vm->halted = 1;
            break;

        case OP_NATIVE_CALL: {
            vm_language_coverage_native_dispatch(vm, instr.operand);
            vm_dispatch_native(vm, instr.operand);
            break;
        }

        case OP_CLOSE_UPVALUE: vm_exec_close_upvalue(vm, instr.operand); break;

        case OP_VEC_CREATE: vm_exec_vec_create(vm, instr.operand); break;

        /* OP_VEC_REF / OP_VEC_SET / OP_STR_REF are the inline fast paths the
         * VM compiler emits for direct (vector-ref v i) / (vector-set! v i x) /
         * (string-ref s i) calls; the native-call handlers (vm_native.c cases
         * 219/220/551) serve the indirect/higher-order calls.  Both must
         * enforce the same catchable out-of-range contract as the native
         * codegen — see vm_raise_error_msg() in vm_native.c. */
        case OP_VEC_REF: vm_exec_vec_ref(vm); break;

        case OP_VEC_SET: vm_exec_vec_set(vm); break;

        case OP_VEC_LEN: vm_exec_vec_len(vm); break;

        case OP_STR_REF: {
            Value idx = vm_pop(vm), str_val = vm_pop(vm);
            if (str_val.type == VAL_STRING) {
                VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
                int i = (int)as_number(idx);
                if (!s || i < 0 || i >= s->char_len) {
                    vm_raise_error_msg(vm, "string-ref: index out of bounds");
                    break;
                }
                /* R7RS string-ref returns a character, not its integer code. */
                vm_push(vm, (Value){.type = VAL_CHAR, .as.i = vm_string_ref(s, i)});
            } else vm_push(vm, (Value){.type = VAL_CHAR, .as.i = 0});
            break;
        }

        case OP_STR_LEN: {
            Value str_val = vm_pop(vm);
            if (str_val.type == VAL_STRING) {
                VmString* s = (VmString*)vm->heap.objects[str_val.as.ptr]->opaque.ptr;
                vm_push(vm, INT_VAL(s ? vm_string_length(s) : 0));
            } else vm_push(vm, INT_VAL(0));
            break;
        }

        case OP_PAIR_P: { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_PAIR)); break; }
        case OP_NUM_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(vm_tag_is_number(v))); break; } /* SW-31 */
        case OP_STR_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_STRING)); break; }
        case OP_BOOL_P: { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_BOOL)); break; }
        case OP_PROC_P: { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_CLOSURE)); break; }
        case OP_VEC_P:  { Value v = vm_pop(vm); vm_push(vm, BOOL_VAL(v.type == VAL_VECTOR)); break; }

        case OP_SET_CAR: vm_exec_set_car(vm); break;
        case OP_SET_CDR: vm_exec_set_cdr(vm); break;

        case OP_POPN: vm_exec_popn(vm, instr.operand); break;

        case OP_CALLCC: {
            /* Switch fallback: same logic as computed-goto lbl_CALLCC */
            Value proc = vm_pop(vm);
            if (proc.type != VAL_CLOSURE) { vm_push(vm, NIL_VAL); break; }
            int32_t cont_ptr = heap_alloc(&vm->heap);
            if (cont_ptr < 0) { vm->error = 1; break; }
            vm->heap.objects[cont_ptr]->type = HEAP_CONTINUATION;
            VmContinuation* cont = (VmContinuation*)vm_alloc(&vm->heap.regions,
                vm_continuation_allocation_size(vm));
            if (!cont) { vm->error = 1; break; }
            cont->pc = vm->pc; cont->fp = vm->fp; cont->sp = vm->sp;
            cont->frame_count = vm->frame_count;
            cont->n_handlers = vm->n_handlers;
            cont->promise_mark = vm->promise_eval_head;
            vm_capture_continuation_stack(vm, cont);
            vm_capture_continuation_dynamic_state(vm, cont);
            vm->heap.objects[cont_ptr]->opaque.ptr = cont;
            Value cont_val = (Value){.type = VAL_CONTINUATION, .as.ptr = cont_ptr};
            vm_push(vm, proc); vm_push(vm, cont_val);
            HeapObject* cl_cc = vm->heap.objects[proc.as.ptr];
            if (vm->frame_count >= MAX_FRAMES) { vm->error = 1; break; }
            vm->frames[vm->frame_count].return_pc = vm->pc;
            vm->frames[vm->frame_count].return_fp = vm->fp;
            vm->frames[vm->frame_count].func_pc = cl_cc->closure.func_pc;
            vm->frame_count++;
            vm->fp = vm->sp - 1; vm->pc = cl_cc->closure.func_pc;
            break;
        }
        case OP_INVOKE_CC: vm_exec_invoke_cc(vm); break;
        case OP_OPEN_CLOSURE: break;
        case OP_PUSH_HANDLER: vm_exec_push_handler(vm, instr.operand); break;
        case OP_POP_HANDLER: { if (vm->n_handlers > 0) vm->n_handlers--; break; }
        case OP_GET_EXN: { vm_push(vm, vm->current_exception); break; }
        case OP_PACK_REST: {
            int n_fixed = instr.operand;
            int n_args = vm->sp - vm->fp;
            Value list = NIL_VAL;
            for (int i = n_args - 1; i >= n_fixed; i--) {
                Value item = vm->stack[vm->fp + i];
                int32_t p = heap_alloc(&vm->heap);
                if (p < 0) { vm->error = 1; break; }
                vm->heap.objects[p]->type = HEAP_CONS;
                vm->heap.objects[p]->cons.car = item;
                vm->heap.objects[p]->cons.cdr = list;
                list = PAIR_VAL(p);
            }
            vm->sp = vm->fp + n_fixed;
            vm_push(vm, list);
            break;
        }
        case OP_WIND_PUSH: {
            Value after = vm_pop(vm);
            Value before = vm_pop(vm);
            if (vm->n_winds < 32) { vm->wind_stack[vm->n_winds].before = before; vm->wind_stack[vm->n_winds].after = after; vm->n_winds++; }
            break;
        }
        case OP_WIND_POP: {
            if (vm->n_winds > 0) vm->n_winds--;
            break;
        }
        case OP_GLOBAL_MARK: {
            if (instr.operand > vm->global_top) vm->global_top = instr.operand;
            break;
        }
        /* OP_CLOSE_UPVALUE handled at line 720 — no duplicate */

        default:
            fprintf(stderr, "UNKNOWN OPCODE %d\n", instr.op);
            vm->error = 1;
            break;
        }
    }
    if (owns_native_escape) vm->native_escape_ready = 0;
#endif
}
