#!/usr/bin/env python3
"""bench/generate_large_single_file.py — synthetic large-single-file .esk generator.

A 2026-08-26 downstream-consumer audit measured a real-world compile-time
shape Eshkol's own corpus never exercises: a single hand-written file with
many top-level `define`s (as opposed to the same code volume spread across
many separately-compiled files) took disproportionately longer to
`--emit-object` than a multi-file bundle of comparable total size — 4x+
slower for a file with roughly the same or smaller code volume, and it never
finished within the audit's time window. Eshkol's own `tests/`/`bench/`
corpus has no file or generated fixture anywhere near that shape (many
top-level definitions sharing ONE translation unit, each referencing a few
earlier ones), so a regression in large-single-file compile time would ship
undetected.

This generator produces a SYNTHETIC fixture with a comparable shape —
deterministic, self-contained, and NOT derived from any external codebase:

  - N top-level `define`s (default 208, matching the audit's measured file)
  - each function body is a `let*` of a few bindings, sometimes wrapped in a
    `cond` (roughly one function in five, matching the audit's measured
    195 let/let* forms and 46 cond forms across 208 defines)
  - each function calls 1-2 EARLIER-numbered functions (deterministic index
    arithmetic, no randomness) so the definitions genuinely interact within
    the one translation unit, rather than being N independent islands a
    front end could trivially parallelize or skip relating to each other
  - a small, fixed number of lambda-valued definitions (default 4, matching
    the audit's "only 4 lambdas") since the measured pathology is specific
    to top-level `define` volume, not closures
  - no `(require ...)`/`(load ...)` of other files: everything the audit
    flagged as the anomaly is the SINGLE TRANSLATION UNIT effect, so the
    fixture stays exactly one file with no fan-out to explain away

Usage:
    python3 bench/generate_large_single_file.py --defines 208 --out FILE.esk
    python3 bench/generate_large_single_file.py --self-test
"""

from __future__ import annotations

import argparse
import sys


def generate(num_defines: int, num_lambdas: int) -> str:
    if num_defines < 1:
        raise ValueError("num_defines must be >= 1")
    lines: list[str] = [
        ";; GENERATED by bench/generate_large_single_file.py — do not hand-edit.",
        ";; Synthetic large-single-file compile-time fixture (deterministic, self-contained).",
        f";; defines={num_defines} lambdas={num_lambdas}",
        "(require stdlib)",
        "",
    ]

    # Evenly spread the lambda-valued definitions across the file rather than
    # clustering them, so they cannot accidentally dodge whatever pass is
    # actually expensive by all landing in one corner of the unit.
    lambda_slots = set()
    if num_lambdas > 0:
        stride = max(1, num_defines // num_lambdas)
        for k in range(num_lambdas):
            lambda_slots.add(min(num_defines - 1, k * stride))

    for i in range(num_defines):
        name = f"f{i}"
        if i in lambda_slots:
            # A lambda-valued top-level definition: apply an earlier function
            # through a closure rather than calling it directly.
            ref = f"f{i // 2}" if i >= 2 else "f0" if i == 1 else None
            body = f"(lambda (x) (+ x {i}))" if ref is None else \
                f"(lambda (x) (+ ({ref} x) {i}))"
            lines.append(f"(define {name} {body})")
            continue

        a = i - 1 if i >= 1 else 0
        b = i - 2 if i >= 2 else 0
        if i % 5 == 0 and i >= 2:
            # Roughly one function in five wraps its result in a cond,
            # matching the audit's measured cond:define ratio.
            d_binding = (
                f"(d (cond ((> c 0) (f{a} c))\n"
                f"                     ((< c 0) (f{b} (- c)))\n"
                f"                     (else c)))"
            )
        else:
            d_binding = f"(d (+ (f{a} c) {b}))"
        fn = (
            f"(define (f{i} x)\n"
            f"  (let* ((a (+ x {i}))\n"
            f"         (b (* a 2))\n"
            f"         (c (- b {i % 7}))\n"
            f"         {d_binding})\n"
            f"    d))"
        )
        lines.append(fn)

    lines.append("")
    lines.append(f"(display (f{num_defines - 1} 1))")
    lines.append("(newline)")
    lines.append("")
    return "\n".join(lines)


def self_test() -> bool:
    ok = True

    def balanced(text: str) -> bool:
        depth = 0
        for ch in text:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth < 0:
                    return False
        return depth == 0

    src = generate(20, 2)
    checks = [
        ("parens balance at defines=20", balanced(src)),
        ("parens balance at defines=208 (the real fixture size)", balanced(generate(208, 4))),
        ("parens balance at defines=1 (edge case)", balanced(generate(1, 0))),
        ("parens balance at defines=2 (edge case)", balanced(generate(2, 1))),
        ("has require stdlib", "(require stdlib)" in src),
        ("has expected define count",
         sum(1 for line in src.splitlines() if line.startswith("(define ")
             or line.startswith("(define (")) == 20),
        ("has at least one lambda", "lambda" in src),
        ("has at least one cond", "cond" in src),
        ("references an earlier function from f19", "f18" in src.split("(define (f19")[1].split("(define ")[0]
         if "(define (f19" in src else False),
        ("deterministic across two runs", generate(37, 4) == generate(37, 4)),
    ]
    for label, passed in checks:
        print(f"  [{'OK' if passed else 'GATE IS BROKEN'}] {label}")
        ok = ok and passed

    try:
        generate(0, 0)
        print("  [GATE IS BROKEN] num_defines=0 should raise ValueError")
        ok = False
    except ValueError:
        print("  [OK] num_defines=0 raises ValueError")

    print("self-test: PASS" if ok else "self-test: FAIL", file=sys.stderr if not ok else sys.stdout)
    return ok


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--defines", type=int, default=208,
                         help="number of top-level define forms (default: 208, "
                              "matching the audit's measured file)")
    parser.add_argument("--lambdas", type=int, default=4,
                         help="number of lambda-valued top-level definitions (default: 4)")
    parser.add_argument("--out", default=None, help="output path (default: stdout)")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)

    if args.self_test:
        return 0 if self_test() else 1

    source = generate(args.defines, args.lambdas)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(source)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
