#!/usr/bin/env bash
# bench/axes/01_exact_ad.sh — AXIS 1: exact-AD cost curves.
#
# Substantiates two public claims about `derivative-n` (docs/guide/
# AUTOMATIC_DIFFERENTIATION.md):
#   * cost is O(k^2) in the derivative order k — a truncated-Taylor
#     recurrence, never the 2^k blowup of stacked dual numbers;
#   * evaluated at an exact (rational/bignum) point, the result is exact —
#     not a float approximation of an exact answer.
#
# Two curves, each run at BOTH an exact-rational point and a float point:
#   * ORDER sweep  — fixed workload, k = 1..24, derivative-n(f, x, k).
#   * DIMENSION sweep — fixed order k=4, workload size d = 1..64, where
#     "dimension" here means the SIZE OF THE PRIMAL COMPUTATION the
#     derivative is threaded through (a d-step multiply chain), not the
#     number of independent AD input variables. That distinction matters:
#     per docs/guide/AUTOMATIC_DIFFERENTIATION.md ("Elsewhere (vector/tensor
#     points), those entry points do a one-time boundary coercion to
#     double"), `gradient`/`jacobian` on a VECTOR point are not exact even
#     when every entry is a rational — only a single exact SCALAR point is
#     guaranteed exact. Wave 1 scopes the exact-rational dimension curve to
#     the case that is actually guaranteed exact (a scalar x threaded
#     through a d-step computation via `derivative-n`), and this comment is
#     the honest record of why: testing `gradient` on a length-d rational
#     vector would silently exercise the float path and mislabel it exact.
#
# Both curves also emit one MONO (compile-time-literal k=8) data point per
# path, alongside the general runtime-k (heap-tower) curve the sweep uses —
# this reproduces, at one point, the same MONO-vs-heap comparison
# tests/ad/taylor_tower_noheap_bench.esk already gates, so a reader can see
# how much of the runtime-k curve's cost is the heap tower itself.
#
# Timing methodology (ADR-0007 "Result protocol" / "Noise controls"):
#   * warmup is implicit in the calibration doubling loop below (the first
#     1-2 doublings ARE the warmup — code, allocator, and any lazy init
#     settle before a sample is kept);
#   * iteration count is chosen per data point so each SAMPLE (not just the
#     calibration probe) takes at least $TARGET_NS wall time;
#   * every raw sample is kept and reported (ROUNDS repeats per point), not
#     collapsed to a single number before it reaches the JSON;
#   * BLAS/OpenMP thread pools are pinned to 1 (bench_pin_single_thread) —
#     this axis is single-scalar-call latency, not throughput;
#   * timing is measured IN-PROCESS via (current-time-ns), so process
#     startup/compile time never contaminates a sample.
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../lib/common.sh
. "$REPO_ROOT/bench/lib/common.sh"

BUILD_DIR="${1:?usage: 01_exact_ad.sh <build_dir> <work_dir> <json_out> <md_out> [smoke]}"
WORK_DIR="${2:?}"
JSON_OUT="${3:?}"
MD_OUT="${4:?}"
SMOKE="${5:-0}"

ESHKOL_RUN="$BUILD_DIR/eshkol-run"
[ -x "$ESHKOL_RUN" ] || bench_die "01_exact_ad: $ESHKOL_RUN not found or not executable"

bench_pin_single_thread
mkdir -p "$WORK_DIR"

if [ "$SMOKE" = "1" ]; then
    K_LIST="1 2 4 8"
    D_LIST="1 2 4"
    TARGET_NS=20000000     # 20ms
    MAX_ITERS=2000
    ROUNDS=2
else
    K_LIST="1 2 3 4 5 6 8 10 12 16 20 24"
    D_LIST="1 2 4 8 16 32 64"
    TARGET_NS=300000000    # 300ms
    MAX_ITERS=2000000
    ROUNDS=5
fi
DIM_K=4

scheme_list() { # <words...> -> "(w1 w2 w3)"
    local out="(" first=1
    for w in "$@"; do
        [ "$first" = 1 ] || out="$out "
        out="$out$w"
        first=0
    done
    printf '%s)' "$out"
}
K_LIST_SCM="$(scheme_list $K_LIST)"

COMMON_PRELUDE() {
    cat <<EOF
;; generated by bench/axes/01_exact_ad.sh — do not edit by hand
(define TARGET-NS $TARGET_NS)
(define MAX-ITERS $MAX_ITERS)
(define ROUNDS $ROUNDS)

(define (run-n thunk n)
  (let loop ((i 0) (acc 0))
    (if (>= i n) acc (loop (+ i 1) (+ acc (thunk))))))

(define (calibrate thunk)
  (let loop ((iters 4))
    (let* ((t0 (current-time-ns))
           (dummy (run-n thunk iters))
           (t1 (current-time-ns))
           (elapsed (- t1 t0)))
      (if (or (>= elapsed TARGET-NS) (>= iters MAX-ITERS))
          iters
          (loop (* iters 2))))))

(define (sample-round thunk iters)
  (let* ((t0 (current-time-ns)) (dummy (run-n thunk iters)) (t1 (current-time-ns)))
    (- t1 t0)))

(define (sample-rounds thunk iters rounds)
  (let loop ((r 0) (acc '()))
    (if (>= r rounds) (reverse acc)
        (loop (+ r 1) (cons (sample-round thunk iters) acc)))))

(define (display-ns-list lst)
  (if (null? lst) #t
      (begin (display (car lst))
             (if (null? (cdr lst)) #t (display ","))
             (display-ns-list (cdr lst)))))

(define (bench-one kind path k thunk)
  (let* ((iters (calibrate thunk))
         (rounds (sample-rounds thunk iters ROUNDS)))
    (display "BENCH kind=") (display kind)
    (display " path=") (display path)
    (display " k=") (display k)
    (display " iters=") (display iters)
    (display " ns_samples=[") (display-ns-list rounds) (display "]")
    (newline)))
EOF
}

ORDER_SRC="$WORK_DIR/ad_order_sweep.esk"
{
    COMMON_PRELUDE
    cat <<EOF

;; f(x) = 1/(1-x): every derivative is nonzero, exercises the full
;; div/sub recurrence chain each call (same shape as
;; tests/ad/taylor_tower_noheap_bench.esk).
(define (f-float x) (/ 1.0 (- 1.0 x)))
(define (f-exact x) (/ 1 (- 1 x)))
(define x-float 0.5)
(define x-exact (/ 1 2))

;; MONO (compile-time-literal k=8) reference points, both paths.
(bench-one "ad_order_mono" "float" 8 (lambda () (derivative-n f-float x-float 8)))
(bench-one "ad_order_mono" "exact" 8 (lambda () (derivative-n f-exact x-exact 8)))

(define (run-order-sweep lst)
  (if (null? lst) #t
      (let ((k (car lst)))
        (bench-one "ad_order" "float" k (lambda () (derivative-n f-float x-float k)))
        (bench-one "ad_order" "exact" k (lambda () (derivative-n f-exact x-exact k)))
        (run-order-sweep (cdr lst)))))

(run-order-sweep '$K_LIST_SCM)
(display "DONE ad_order_sweep") (newline)
EOF
} > "$ORDER_SRC"

DIM_SRC="$WORK_DIR/ad_dim_sweep.esk"
{
    COMMON_PRELUDE
    cat <<EOF

;; f_d(x) = x^(d+1), built as an explicit d-step multiply CHAIN (not the
;; expt builtin) so the AD tower must trace d generic multiply nodes —
;; "dimension" here is the size of that chain, fixed derivative order.
;;
;; Each d gets its own TOP-LEVEL named function (f-dim-<d>) rather than a
;; closure returned from a factory: derivative-n's codegen resolves a
;; directly-named top-level function reliably (same shape as the order
;; sweep's f-float/f-exact); a closure captured two lambda layers deep
;; (thunk -> derivative-n call -> factory-returned closure) hit
;; "Failed to resolve function for derivative" in
;; lib/backend/autodiff_codegen.cpp during wave-1 development — recorded
;; here so nobody reintroduces that shape by accident.
(define dim-k $DIM_K)
(define x-float 0.5)
(define x-exact (/ 1 3))
EOF
    for d in $D_LIST; do
        cat <<EOF
(define (f-dim-$d x)
  (let loop ((i 0) (acc x))
    (if (>= i $d) acc (loop (+ i 1) (* acc x)))))
EOF
    done
    for d in $D_LIST; do
        cat <<EOF
(bench-one "ad_dim" "float" $d (lambda () (derivative-n f-dim-$d x-float dim-k)))
(bench-one "ad_dim" "exact" $d (lambda () (derivative-n f-dim-$d x-exact dim-k)))
EOF
    done
    cat <<EOF
(display "DONE ad_dim_sweep") (newline)
EOF
} > "$DIM_SRC"

bench_disk_cap_check "$WORK_DIR"

compile_and_run() { # <src> <bin> <out_log>
    local src="$1" bin="$2" out="$3"
    "$ESHKOL_RUN" "$src" -o "$bin" -L"$BUILD_DIR" >"$out.compile.log" 2>&1 \
        || bench_die "01_exact_ad: compile failed for $src (see $out.compile.log)"
    "$bin" >"$out" 2>"$out.stderr.log" \
        || bench_die "01_exact_ad: run failed for $bin (see $out.stderr.log)"
    grep -q "^DONE " "$out" || bench_die "01_exact_ad: $bin did not print its DONE marker — see $out"
}

compile_and_run "$ORDER_SRC" "$WORK_DIR/ad_order_sweep" "$WORK_DIR/order.out"
compile_and_run "$DIM_SRC" "$WORK_DIR/ad_dim_sweep" "$WORK_DIR/dim.out"
bench_disk_cap_check "$WORK_DIR"

python3 "$SCRIPT_DIR/01_exact_ad_reduce.py" \
    "$WORK_DIR/order.out" "$WORK_DIR/dim.out" "$JSON_OUT" "$MD_OUT" \
    || bench_die "01_exact_ad: result reduction failed"

bench_log "01_exact_ad: wrote $JSON_OUT and $MD_OUT"
