#!/usr/bin/env bash
# bench/axes/02_ozaki_gemm.sh — AXIS 2: Ozaki-II CRT exact f64 GEMM.
#
# Compares the GPU Ozaki-II exact-CRT DGEMM tier against the vendor BLAS
# baseline (Apple Accelerate / AMX on macOS) ON THE SAME MACHINE, on both
# axes the public claim rests on:
#   * THROUGHPUT — GF/s at a range of N, vendor BLAS vs Ozaki-II exact vs
#     the reduced-precision Ozaki-II "fast" tier (bonus, opt-in reduced
#     accuracy);
#   * ACCURACY — error vs a TRUE exact reference. Unlike the correctness
#     gate this reuses the convention of (tests/gpu/ozaki_correctness_test.esk
#     compares Ozaki-II against an independent CPU f64 triple-loop
#     reference), this axis's reference is computed in Eshkol's own EXACT
#     RATIONAL arithmetic — the reference itself has zero rounding error, not
#     just a different f64 accumulation order. That is the strongest
#     available substantiation of "Ozaki-II computes the exact product and
#     rounds once, where BLAS rounds every accumulation": both the vendor
#     BLAS result and the Ozaki-II result are compared against a reference
#     that cannot itself be wrong.
#
# The CUDA INT8-Ozaki numbers in CHANGELOG.md (RTX 3090 / RTX PRO 6000
# Blackwell) are NOT reproduced here — this machine has no NVIDIA GPU. They
# are cited in bench/README.md as prior published measurements on named
# other hardware, never re-quoted as something this suite measured.
#
# GPU/kernel selection is env-var only (no Eshkol-level GEMM API beyond the
# plain `matmul` builtin) — see docs/breakdown/GPU_ACCELERATION.md and
# tests/gpu/ozaki_correctness_gate.sh, whose env-forcing convention this
# script follows:
#   ESHKOL_GPU_MATMUL_THRESHOLD=0 ESHKOL_GPU_THRESHOLD=1 ESHKOL_GPU_VERBOSE=1
#   ESHKOL_SF64_KERNEL=ozaki|ozaki-fast   forces the GPU Ozaki-II path
#   (unset)                                default: vendor BLAS (Accelerate/AMX)
#
# Requires a real Metal (macOS) or CUDA (Linux) GPU for the Ozaki-II rows;
# on a GPU-less host those rows are SKIPPED (never faked) and the vendor-BLAS
# throughput/accuracy rows are still reported.
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../lib/common.sh
. "$REPO_ROOT/bench/lib/common.sh"

BUILD_DIR="${1:?usage: 02_ozaki_gemm.sh <build_dir> <work_dir> <json_out> <md_out> [smoke]}"
WORK_DIR="${2:?}"
JSON_OUT="${3:?}"
MD_OUT="${4:?}"
SMOKE="${5:-0}"

ESHKOL_RUN="$BUILD_DIR/eshkol-run"
[ -x "$ESHKOL_RUN" ] || bench_die "02_ozaki_gemm: $ESHKOL_RUN not found or not executable"

bench_pin_single_thread
mkdir -p "$WORK_DIR"

if [ "$SMOKE" = "1" ]; then
    N_LIST="64 128"
    ROUNDS=1
    ACC_N=16
else
    N_LIST="256 512 1024 2048 4096 8192"
    ROUNDS=3
    ACC_N=64
fi

# ── GPU presence probe (matches tests/gpu/ozaki_correctness_gate.sh) ───────
GPU_PRESENT=0
UNAME_S="$(uname -s)"
if [ "$UNAME_S" = "Darwin" ]; then
    GPU_PRESENT=1   # Metal is present on every supported macOS host
elif command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
    bench_log "02_ozaki_gemm: this host has a CUDA GPU, not Metal — Ozaki-II here is Metal-only; GPU rows will be skipped"
    GPU_PRESENT=0
fi

scheme_list() { local out="(" first=1; for w in "$@"; do [ "$first" = 1 ] || out="$out "; out="$out$w"; first=0; done; printf '%s)' "$out"; }
N_LIST_SCM="$(scheme_list $N_LIST)"

THROUGHPUT_SRC="$WORK_DIR/ozaki_throughput.esk"
cat > "$THROUGHPUT_SRC" <<EOF
;; generated by bench/axes/02_ozaki_gemm.sh — do not edit by hand
(define ROUNDS $ROUNDS)

(define (display-ns-list lst)
  (if (null? lst) #t
      (begin (display (car lst))
             (if (null? (cdr lst)) #t (display ","))
             (display-ns-list (cdr lst)))))

(define (bench-matmul n rounds)
  (let* ((a (random-tensor (list n n)))
         (b (random-tensor (list n n)))
         (warm (matmul a b)))
    (let loop ((r 0) (acc '()))
      (if (>= r rounds)
          (reverse acc)
          (loop (+ r 1) (cons (time-it (lambda () (matmul a b)) 1) acc))))))

(define (run-sizes lst)
  (if (null? lst) #t
      (let* ((n (car lst))
             (samples (bench-matmul n ROUNDS)))
        (display "BENCH n=") (display n)
        (display " ns_samples=[") (display-ns-list samples) (display "]")
        (newline)
        (run-sizes (cdr lst)))))

(run-sizes '$N_LIST_SCM)
(display "DONE ozaki_throughput") (newline)
EOF

# ── accuracy fixture: wide-dynamic-range entries, exact-rational reference ──
COORDS=""
STEP=$(( (ACC_N > 8 ? ACC_N / 8 : 1) ))
[ "$STEP" -ge 1 ] || STEP=1
r=0
while [ "$r" -lt "$ACC_N" ]; do
    c=0
    while [ "$c" -lt "$ACC_N" ]; do
        COORDS="$COORDS (cons $r $c)"
        c=$(( c + STEP ))
    done
    r=$(( r + STEP ))
done

ACCURACY_SRC="$WORK_DIR/ozaki_accuracy.esk"
cat > "$ACCURACY_SRC" <<EOF
;; generated by bench/axes/02_ozaki_gemm.sh — do not edit by hand
(define N $ACC_N)
(define total (* N N))

;; Deterministic, wide-dynamic-range (1e-3 .. 1e3) entries. The reference dot
;; product is computed in EXACT rational arithmetic over
;; (inexact->exact <the double GEMM actually received>) — i.e. the exact
;; value of the double, not the platonic pre-rounding formula value. That
;; distinction matters: comparing against the platonic value would also
;; measure input-quantization error (1/1000 is not exactly representable in
;; binary floating point), which every GEMM kernel inherits equally from its
;; f64 inputs and which is NOT what "computes the exact product, rounds once"
;; claims to avoid. Rounding once at input, then comparing against the exact
;; value of THAT rounded input, isolates the thing actually being tested:
;; whether the kernel's own reduction (K multiply-adds) introduces further
;; error beyond the one unavoidable input-rounding step.
(define (scale-for i j)
  (let ((m (modulo (+ i j) 3)))
    (cond ((= m 0) (/ 1 1000)) ((= m 1) 1) (else 1000))))
(define (sign-for i j) (if (= (modulo (* i j) 2) 0) 1 -1))
(define (base-for i j) (+ 1 (modulo (+ (* i 7) (* j 13)) 11)))
(define (entry-exact i j) (* (sign-for i j) (scale-for i j) (base-for i j)))

(define A-f (make-tensor (list N N) 0.0))
(define B-f (make-tensor (list N N) 0.0))
(define A-e (make-vector total 0))
(define B-e (make-vector total 0))

(define (fill! i)
  (if (>= i total) #t
      (let* ((row (quotient i N)) (col (modulo i N))
             (av (exact->inexact (entry-exact row col)))
             (bv (exact->inexact (entry-exact col row))))
        (tensor-set! A-f i av)
        (tensor-set! B-f i bv)
        (vector-set! A-e i (inexact->exact av))
        (vector-set! B-e i (inexact->exact bv))
        (fill! (+ i 1)))))
(fill! 0)

(define (a-ref r c) (vector-ref A-e (+ (* r N) c)))
(define (b-ref r c) (vector-ref B-e (+ (* r N) c)))
(define (exact-dot r c)
  (let loop ((k 0) (acc 0))
    (if (>= k N) acc (loop (+ k 1) (+ acc (* (a-ref r k) (b-ref k c)))))))

(define C (matmul A-f B-f))

(define (report r c)
  (let* ((approx (tensor-ref C (+ (* r N) c)))
         (exact-f (exact->inexact (exact-dot r c)))
         (err (abs (- approx exact-f)))
         (rel (if (= exact-f 0.0) err (/ err (abs exact-f)))))
    (display "SAMPLE r=") (display r) (display " c=") (display c)
    (display " approx=") (display approx)
    (display " exact=") (display exact-f)
    (display " relerr=") (display rel)
    (newline)))

(define (run-coords lst)
  (if (null? lst) #t
      (begin (report (caar lst) (cdar lst)) (run-coords (cdr lst)))))

(run-coords (list$COORDS))
(display "DONE ozaki_accuracy") (newline)
EOF

bench_disk_cap_check "$WORK_DIR"

THROUGHPUT_BIN="$WORK_DIR/ozaki_throughput"
ACCURACY_BIN="$WORK_DIR/ozaki_accuracy"
"$ESHKOL_RUN" "$THROUGHPUT_SRC" -o "$THROUGHPUT_BIN" -L"$BUILD_DIR" >"$WORK_DIR/throughput.compile.log" 2>&1 \
    || bench_die "02_ozaki_gemm: throughput fixture failed to compile (see $WORK_DIR/throughput.compile.log)"
"$ESHKOL_RUN" "$ACCURACY_SRC" -o "$ACCURACY_BIN" -L"$BUILD_DIR" >"$WORK_DIR/accuracy.compile.log" 2>&1 \
    || bench_die "02_ozaki_gemm: accuracy fixture failed to compile (see $WORK_DIR/accuracy.compile.log)"

# run_variant <tag> <env...=> writes $WORK_DIR/throughput.<tag>.out /
# accuracy.<tag>.out and their .stderr logs; sets VARIANT_DISPATCHED.
run_variant() {
    local tag="$1"; shift
    env "$@" "$THROUGHPUT_BIN" >"$WORK_DIR/throughput.$tag.out" 2>"$WORK_DIR/throughput.$tag.stderr"
    local rc1=$?
    env "$@" "$ACCURACY_BIN" >"$WORK_DIR/accuracy.$tag.out" 2>"$WORK_DIR/accuracy.$tag.stderr"
    local rc2=$?
    VARIANT_DISPATCHED=0
    if grep -q '^\[GPU\] Ozaki-II:' "$WORK_DIR/throughput.$tag.stderr" 2>/dev/null \
       || grep -q '^\[GPU\] Ozaki-II:' "$WORK_DIR/accuracy.$tag.stderr" 2>/dev/null; then
        VARIANT_DISPATCHED=1
    fi
    if [ "$rc1" -ne 0 ]; then
        bench_log "02_ozaki_gemm: throughput run for '$tag' exited $rc1 (see $WORK_DIR/throughput.$tag.stderr)"
    fi
    if [ "$rc2" -ne 0 ]; then
        bench_log "02_ozaki_gemm: accuracy run for '$tag' exited $rc2 (see $WORK_DIR/accuracy.$tag.stderr)"
    fi
}

# amx: vendor BLAS baseline, no GPU forcing.
run_variant amx
AMX_OK=1

OZAKI_OK=0
OZAKI_FAST_OK=0
if [ "$GPU_PRESENT" = "1" ]; then
    run_variant ozaki \
        ESHKOL_GPU_MATMUL_THRESHOLD=0 ESHKOL_GPU_THRESHOLD=1 ESHKOL_GPU_VERBOSE=1 \
        ESHKOL_BLAS_PEAK_GFLOPS=0.001 ESHKOL_GPU_PEAK_GFLOPS=1000000 \
        ESHKOL_SF64_KERNEL=ozaki
    [ "$VARIANT_DISPATCHED" = "1" ] && OZAKI_OK=1 || bench_log "02_ozaki_gemm: ozaki-exact never showed a GPU dispatch marker — treating as unavailable on this host"

    run_variant ozaki-fast \
        ESHKOL_GPU_MATMUL_THRESHOLD=0 ESHKOL_GPU_THRESHOLD=1 ESHKOL_GPU_VERBOSE=1 \
        ESHKOL_BLAS_PEAK_GFLOPS=0.001 ESHKOL_GPU_PEAK_GFLOPS=1000000 \
        ESHKOL_SF64_KERNEL=ozaki-fast
    [ "$VARIANT_DISPATCHED" = "1" ] && OZAKI_FAST_OK=1 || bench_log "02_ozaki_gemm: ozaki-fast never showed a GPU dispatch marker — treating as unavailable on this host"
else
    bench_log "02_ozaki_gemm: no Metal/CUDA GPU on this host — Ozaki-II rows will be marked unavailable"
fi
bench_disk_cap_check "$WORK_DIR"

python3 "$SCRIPT_DIR/02_ozaki_gemm_reduce.py" \
    --workdir "$WORK_DIR" --amx-ok "$AMX_OK" --ozaki-ok "$OZAKI_OK" --ozaki-fast-ok "$OZAKI_FAST_OK" \
    --json-out "$JSON_OUT" --md-out "$MD_OUT" \
    || bench_die "02_ozaki_gemm: result reduction failed"

bench_log "02_ozaki_gemm: wrote $JSON_OUT and $MD_OUT"
