#!/usr/bin/env bash
# bench/axes/03_flat_rss.sh — AXIS 3: flat-RSS under resident load.
#
# Re-measures BOTH the v1.3.4 native claim ("a 100k-tick loop flat at 34MB",
# RELEASE_NOTES.md, from tests/memory/iter_scope_partial_reclaim_test.esk /
# ESH-0214e) and the VM region evacuator claim (PR #461, "26MB flat vs
# 796MB", tests/memory/vm_region_flat_rss_test.sh) on current master, over a
# SWEEP of tick counts rather than one endpoint — the point of a flat-RSS
# claim is that RSS does not grow with iteration count, and that can only be
# shown by a curve.
#
# Methodology: each sweep point is one fresh process, run to completion, peak
# RSS read from `/usr/bin/time -l` (macOS) / `-v` (Linux) — this repo's
# established convention (tests/memory/*_test.sh) since Eshkol has no
# in-process RSS-sampling builtin to draw an intra-run curve from a single
# process. A curve across increasing tick counts is still a curve: a leak
# shows up as RSS growing with ticks; a flat allocator does not, whatever the
# per-point noise. This is spelled out here so nobody mistakes "one process
# per point" for "not a curve".
#
# NATIVE (AOT):  eshkol-run <src> -o <bin>; run <bin> directly.
# VM (bytecode): eshkol-vm-standalone-test <src> — a separate standalone
#                binary, not a flag on eshkol-run.
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../lib/common.sh
. "$REPO_ROOT/bench/lib/common.sh"

BUILD_DIR="${1:?usage: 03_flat_rss.sh <build_dir> <work_dir> <json_out> <md_out> [smoke]}"
WORK_DIR="${2:?}"
JSON_OUT="${3:?}"
MD_OUT="${4:?}"
SMOKE="${5:-0}"

ESHKOL_RUN="$BUILD_DIR/eshkol-run"
VM_BIN="$BUILD_DIR/eshkol-vm-standalone-test"
[ -x "$ESHKOL_RUN" ] || bench_die "03_flat_rss: $ESHKOL_RUN not found or not executable"

mkdir -p "$WORK_DIR"
bench_detect_time_mode

if [ "$SMOKE" = "1" ]; then
    NATIVE_TICKS="200 800 3200"
    VM_TICKS="200 800 3200"
    TIMEOUT_S=30
else
    NATIVE_TICKS="10000 25000 50000 100000 200000 400000"
    VM_TICKS="1000 4000 16000 64000"
    TIMEOUT_S=180
fi

# ── NATIVE fixture: same shape as tests/memory/iter_scope_partial_reclaim_test.esk
#    (ESH-0214e) — a guard-wrapped self-tail define loop mutating a bounded
#    persistent hash-table KB + vector workspace + occasionally-grown list,
#    plus transient per-tick garbage — parameterised on `ticks`. ──────────────
emit_native_fixture() { # <ticks> -> path
    local ticks="$1" path="$WORK_DIR/native_flat_rss_${ticks}.esk"
    cat > "$path" <<EOF
;; generated by bench/axes/03_flat_rss.sh — same shape as
;; tests/memory/iter_scope_partial_reclaim_test.esk (ESH-0214e), ticks swept.
(define ticks $ticks)
(define kb-slots 256)
(define ws-slots 64)
(define scratch-len 200)
(define grow-every 1000)
(define kb (make-hash-table))
(define workspace (make-vector ws-slots 0))
(define trail (cons 'head '()))
(define (tick i tail)
  (guard (e (#t tail))
    (if (>= i ticks)
        i
        (begin
          (let ((scratch (make-vector scratch-len i)))
            (hash-table-set! kb (modulo i kb-slots)
                             (list i (* i 2) (vector-length scratch)))
            (vector-set! workspace (modulo i ws-slots) (list i (* i 3))))
          (if (= (modulo i grow-every) 0)
              (let ((cell (cons i '())))
                (set-cdr! tail cell)
                (tick (+ i 1) cell))
              (tick (+ i 1) tail))))))
(define result (tick 0 trail))
(display "PASS result=") (display result) (newline)
EOF
    printf '%s\n' "$path"
}

# ── VM fixture: same shape as tests/memory/vm_region_flat_rss_test.sh's
#    emit_fixture() — a with-region-wrapped scratch loop, parameterised on
#    iteration count. ─────────────────────────────────────────────────────
emit_vm_fixture() { # <n> -> path
    local n="$1" path="$WORK_DIR/vm_flat_rss_${n}.esk"
    cat > "$path" <<EOF
;; generated by bench/axes/03_flat_rss.sh — same shape as
;; tests/memory/vm_region_flat_rss_test.sh emit_fixture(), n swept.
(define (scratch-step k)
  (with-region ('step 65536)
    (let loop ((i 0) (acc '()))
      (if (< i 120)
          (loop (+ i 1) (cons (* i k) acc))
          (length acc)))))
(define (drive n total)
  (if (= n 0) total (drive (- n 1) (+ total (scratch-step n)))))
(display (drive $n 0))
(newline)
EOF
    printf '%s\n' "$path"
}

bench_disk_cap_check "$WORK_DIR"

NATIVE_ROWS_FILE="$WORK_DIR/native_rows.jsonl"
: > "$NATIVE_ROWS_FILE"
for ticks in $NATIVE_TICKS; do
    src="$(emit_native_fixture "$ticks")"
    bin="$WORK_DIR/native_bin_${ticks}"
    if ! "$ESHKOL_RUN" "$src" -o "$bin" >"$WORK_DIR/native_${ticks}.compile.log" 2>&1; then
        bench_log "03_flat_rss: native compile failed at ticks=$ticks (see $WORK_DIR/native_${ticks}.compile.log)"
        continue
    fi
    out="$WORK_DIR/native_${ticks}.out"
    timelog="$WORK_DIR/native_${ticks}.time"
    bench_run_rss "$bin" "$out" "$timelog" "$TIMEOUT_S"
    ok=0
    grep -q "^PASS" "$out" 2>/dev/null && [ "$BENCH_RUN_RC" -eq 0 ] && ok=1
    printf '{"ticks": %s, "peak_rss_mb": %s, "run_rc": %s, "ok": %s}\n' \
        "$ticks" "$BENCH_RSS_MB" "$BENCH_RUN_RC" "$( [ $ok -eq 1 ] && echo true || echo false )" >> "$NATIVE_ROWS_FILE"
    rm -f "$bin" "$src"
    bench_disk_cap_check "$WORK_DIR"
done

VM_ROWS_FILE="$WORK_DIR/vm_rows.jsonl"
: > "$VM_ROWS_FILE"
VM_AVAILABLE=0
if [ -x "$VM_BIN" ]; then
    VM_AVAILABLE=1
    for n in $VM_TICKS; do
        src="$(emit_vm_fixture "$n")"
        out="$WORK_DIR/vm_${n}.out"
        timelog="$WORK_DIR/vm_${n}.time"
        export ESHKOL_VM_NO_DISASM=1 ESHKOL_VM_HEAP_BUDGET_MB=0 ESHKOL_VM_REGION_QUIET=1
        bench_run_rss "$VM_BIN" "$out" "$timelog" "$TIMEOUT_S" "$src"
        ok=0
        [ "$BENCH_RUN_RC" -eq 0 ] && ok=1
        # evacuator-off comparison, largest point only (matches the existing gate's convention)
        off_rss=""
        if [ "$n" = "$(echo $VM_TICKS | awk '{print $NF}')" ]; then
            out_off="$WORK_DIR/vm_${n}_evac_off.out"
            timelog_off="$WORK_DIR/vm_${n}_evac_off.time"
            export ESHKOL_VM_REGION_EVAC=0
            bench_run_rss "$VM_BIN" "$out_off" "$timelog_off" "$TIMEOUT_S" "$src"
            unset ESHKOL_VM_REGION_EVAC
            off_rss="$BENCH_RSS_MB"
            # re-run the on-case so the reported peak_rss_mb below is evac-on
            bench_run_rss "$VM_BIN" "$out" "$timelog" "$TIMEOUT_S" "$src"
            ok=0
            [ "$BENCH_RUN_RC" -eq 0 ] && ok=1
        fi
        unset ESHKOL_VM_NO_DISASM ESHKOL_VM_HEAP_BUDGET_MB ESHKOL_VM_REGION_QUIET
        printf '{"n": %s, "peak_rss_mb": %s, "run_rc": %s, "ok": %s, "evac_off_peak_rss_mb": %s}\n' \
            "$n" "$BENCH_RSS_MB" "$BENCH_RUN_RC" "$( [ $ok -eq 1 ] && echo true || echo false )" \
            "${off_rss:-null}" >> "$VM_ROWS_FILE"
        rm -f "$src"
        bench_disk_cap_check "$WORK_DIR"
    done
else
    bench_log "03_flat_rss: $VM_BIN not found — VM curve unavailable (build with -DESHKOL_BUILD_TESTS=ON)"
fi

python3 "$SCRIPT_DIR/03_flat_rss_reduce.py" \
    --native-rows "$NATIVE_ROWS_FILE" --vm-rows "$VM_ROWS_FILE" --vm-available "$VM_AVAILABLE" \
    --json-out "$JSON_OUT" --md-out "$MD_OUT" \
    || bench_die "03_flat_rss: result reduction failed"

bench_log "03_flat_rss: wrote $JSON_OUT and $MD_OUT"
