// Generated by scripts/gen_geometric_boundary_golden.py.
// Each coordinate is an exact binary64 fixture. The denominator is the
// correctly rounded value of 1 - n * coordinate^2 computed using Fraction,
// with no floating-point multiply/sum/cancellation in the reference.
// Freeze inputs as well as answers so host sqrt rounding cannot change a case.
#ifndef ESHKOL_GEOMETRIC_BOUNDARY_GOLDEN_H
#define ESHKOL_GEOMETRIC_BOUNDARY_GOLDEN_H
struct GeometricBoundaryGolden { double coordinate; double denominator; };
static const GeometricBoundaryGolden geometric_boundary_golden[] = {
    {0x1.ffffffffffffcp-1, 0x1.ffffffffffffep-51}, // n=1
    {0x1.6a09e667f3bc8p-1, 0x1.9d24808334678p-50}, // n=2
    {0x1.279a745903319p-1, 0x1.6df3d6ff0716bp-50}, // n=3
    {0x1.ffffffffffffcp-2, 0x1.ffffffffffffep-51}, // n=4
    {0x1.c9f25c5bfedd5p-2, 0x1.2d241f4883680p-50}, // n=5
    {0x1.a20bd700c2c3bp-2, 0x1.d3dcce987aff3p-51}, // n=6
    {0x1.83091e6a7f7e2p-2, 0x1.7fd821fa74b1ep-50}, // n=7
    {0x1.6a09e667f3bc8p-2, 0x1.9d24808334678p-50}, // n=8
    {0x1.5555555555551p-2, 0x1.9fffffffffffdp-50}, // n=9
    {0x1.43d136248490bp-2, 0x1.863b15066dcfdp-50}, // n=10
    {0x1.34bf63d156822p-2, 0x1.9c0869412cfb9p-50}, // n=11
    {0x1.279a745903319p-2, 0x1.6df3d6ff0716bp-50}, // n=12
    {0x1.1c01aa03be892p-2, 0x1.b3293c8a9be96p-50}, // n=13
    {0x1.11acee5602426p-2, 0x1.c55d3b1862844p-50}, // n=14
    {0x1.08654a2d4f6d6p-2, 0x1.170bbee22e099p-49}, // n=15
    {0x1.ffffffffffffcp-3, 0x1.ffffffffffffep-51}, // n=16
    {0x1.f0b6848d2af18p-3, 0x1.126468b12c10ap-50}, // n=17
    {0x1.e2b7dddfefa63p-3, 0x1.a2fdddd1769aep-51}, // n=18
    {0x1.d5d7ea914b932p-3, 0x1.4d10b2bf60f3ap-50}, // n=19
    {0x1.c9f25c5bfedd5p-3, 0x1.2d241f4883680p-50}, // n=20
    {0x1.bee9056fb9c35p-3, 0x1.0e3c6aed3dca2p-50}, // n=21
    {0x1.b4a293c1d954bp-3, 0x1.618acb0f2c369p-50}, // n=22
    {0x1.ab099ae8f5396p-3, 0x1.1cfe330efffffp-50}, // n=23
    {0x1.a20bd700c2c3bp-3, 0x1.d3dcce987aff3p-51}, // n=24
    {0x1.9999999999996p-3, 0x1.1ffffffffffffp-50}, // n=25
    {0x1.91a5561517618p-3, 0x1.2149cd894b886p-50}, // n=26
    {0x1.8a2345cc04422p-3, 0x1.3686e12e567d6p-50}, // n=27
    {0x1.83091e6a7f7e2p-3, 0x1.7fd821fa74b1ep-50}, // n=28
    {0x1.7c4dd663ebb84p-3, 0x1.601f58bfe9ad2p-50}, // n=29
    {0x1.75e9746a0b094p-3, 0x1.87a0747ec1cf9p-50}, // n=30
    {0x1.6fd4e79325463p-3, 0x1.464b82998d955p-50}, // n=31
    {0x1.6a09e667f3bc8p-3, 0x1.9d24808334678p-50}, // n=32
    {0x1.6482d37a5a3cep-3, 0x1.41e32a26024cep-50}, // n=33
    {0x1.5f3aa673fa90cp-3, 0x1.b221addf7d33dp-50}, // n=34
    {0x1.5a2cd8c69d616p-3, 0x1.a2d6be3ba2866p-50}, // n=35
    {0x1.5555555555551p-3, 0x1.9fffffffffffdp-50}, // n=36
    {0x1.50b06a8fc6b6cp-3, 0x1.7c62f1bb91002p-50}, // n=37
    {0x1.4c3abe93bcf70p-3, 0x1.7504a6866effap-50}, // n=38
    {0x1.47f144fe17f9bp-3, 0x1.9818d5a7562eep-50}, // n=39
    {0x1.43d136248490bp-3, 0x1.863b15066dcfdp-50}, // n=40
    {0x1.3fd8077e70573p-3, 0x1.824d19e4e248cp-50}, // n=41
    {0x1.3c03650e00dffp-3, 0x1.969664d695c98p-50}, // n=42
    {0x1.38512ba21f51ap-3, 0x1.a4faa13cf14a2p-50}, // n=43
    {0x1.34bf63d156822p-3, 0x1.9c0869412cfb9p-50}, // n=44
    {0x1.314c3d92a9e8dp-3, 0x1.9878ecee1323dp-50}, // n=45
    {0x1.2df60c5df2c9ap-3, 0x1.a8e97b37ce43bp-50}, // n=46
    {0x1.2abb43c0eb0f0p-3, 0x1.ad057b87a80b1p-50}, // n=47
    {0x1.279a745903319p-3, 0x1.6df3d6ff0716bp-50}, // n=48
    {0x1.249249249248ep-3, 0x1.dfffffffffffcp-50}, // n=49
    {0x1.21a1851ff6306p-3, 0x1.ca65bd5032df1p-50}, // n=50
    {0x1.1ec70124e98f5p-3, 0x1.f96233310f77ap-50}, // n=51
    {0x1.1c01aa03be892p-3, 0x1.b3293c8a9be96p-50}, // n=52
    {0x1.19507ecf5b9e5p-3, 0x1.a36160d54b0d5p-50}, // n=53
    {0x1.16b28f55d72d0p-3, 0x1.d515103cab0dap-50}, // n=54
    {0x1.1426fac0654d7p-3, 0x1.bbe4eb3634d0dp-50}, // n=55
    {0x1.11acee5602426p-3, 0x1.c55d3b1862844p-50}, // n=56
    {0x1.0f43a45cdeda9p-3, 0x1.cf16c7f50000fp-50}, // n=57
    {0x1.0cea6317186d8p-3, 0x1.0fc7564ce49bbp-49}, // n=58
    {0x1.0aa07bd7b7485p-3, 0x1.9c07566147ebbp-50}, // n=59
    {0x1.08654a2d4f6d6p-3, 0x1.170bbee22e099p-49}, // n=60
    {0x1.0638331ff3076p-3, 0x1.edcb66830a3cap-50}, // n=61
    {0x1.0418a4806de79p-3, 0x1.e3fe1bebd7edep-50}, // n=62
    {0x1.02061446ffa95p-3, 0x1.29c08f4e59356p-49}, // n=63
    {0x1.ffffffffffffcp-4, 0x1.ffffffffffffep-51}, // n=64
};
#endif
