#!/usr/bin/env python3
"""Validate and materialize the VM parity gap dispositions.

PARITY.tsv is the status ledger, not the evidence ledger.  A ``gap`` row is
useful only when a reader can answer two questions without guessing: what
kind of gap is it, and what can be run to observe it?  This tool keeps those
answers in a generated, one-row-per-gap sidecar.  Existing ``found/`` and
reclassified ``resolved/`` files are live reproducers; rows without a filed
behavioural reproducer use the deterministic probe generator below and are
explicitly marked as such.

The checker is intentionally build-free.  It validates the source and the
reproducer routes before a native/VM run, so a missing or stale evidence path
cannot be hidden behind a green runtime gate.
"""

from __future__ import annotations

import argparse
import os
import re
import sys


REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARITY = os.path.join(REPO, "tests", "vm_parity", "PARITY.tsv")
DISPOSITIONS = os.path.join(REPO, "tests", "vm_parity", "GAP_DISPOSITIONS.tsv")
FOUND_RE = re.compile(
    r"(?:tests/vm_parity/)?(?:found|resolved)/[A-Za-z0-9_.-]+\.esk"
)
VALID = {
    "behavioral-divergence",
    "native-defect",
    "cross-engine-uncomparable",
    "vm-unsupported-clean-error",
    "vm-unimplemented",
}


def read_parity(path: str = PARITY) -> list[tuple[str, str, str]]:
    rows = []
    with open(path, encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t", 2)
            if len(fields) < 2:
                raise ValueError(f"{path}:{line_number}: expected TSV row")
            name, status = fields[0].strip(), fields[1].strip()
            justification = fields[2].strip() if len(fields) == 3 else ""
            rows.append((name, status, justification))
    return rows


def _found_path(justification: str) -> str | None:
    match = FOUND_RE.search(justification)
    if not match:
        return None
    path = match.group(0)
    if not path.startswith("tests/"):
        path = "tests/vm_parity/" + path
    # Master reclassifies agreement reproducers under resolved/ while the
    # parity ledger retains the original found/ citation as historical
    # evidence.  Keep that citation meaningful without resurrecting deleted
    # files.
    if path.startswith("tests/vm_parity/found/"):
        resolved = path.replace("tests/vm_parity/found/", "tests/vm_parity/resolved/", 1)
        if os.path.isfile(os.path.join(REPO, resolved)):
            return resolved
    return path


def classify(name: str, justification: str) -> str:
    lowered = justification.lower()
    if _found_path(justification):
        if "native" in lowered and ("wrong" in lowered or "silent" in lowered):
            return "native-defect"
        return "behavioral-divergence"
    if "cannot be compared" in lowered or "cannot be compared" in lowered:
        return "cross-engine-uncomparable"
    if "clean undefined" in lowered or "undefined-variable" in lowered:
        return "vm-unsupported-clean-error"
    if "no vm" in lowered or "missing in vm" in lowered or "unimplemented" in lowered:
        return "vm-unimplemented"
    return "vm-unimplemented"


def generated_probe(name: str) -> str:
    """Return a deterministic one-row probe source for a manifest name."""
    call_name = name[3:].lower().replace("_", "-") if name.startswith("op:") else name
    if not re.fullmatch(r"[%A-Za-z][%A-Za-z0-9!?*/<>=._+\-]*", call_name):
        call_name = "quote"
        expression = "'gap-probe"
    else:
        expression = f"({call_name})"
    return (
        f";; GAP-PROBE: {name}\n"
        ";; Generated by scripts/canonicalize_vm_gaps.py.\n"
        "(guard (e (#t (write 'ERROR)))\n"
        f"  (write {expression}))\n"
    )


def canonical_rows(parity_rows: list[tuple[str, str, str]]) -> list[tuple[str, str, str, str]]:
    result = []
    for name, status, justification in parity_rows:
        if status != "gap":
            continue
        path = _found_path(justification)
        if path is not None:
            reproducer = path
        else:
            reproducer = "generated:scripts/canonicalize_vm_gaps.py"
        result.append((name, classify(name, justification), reproducer, justification))
    return result


def read_sidecar(path: str = DISPOSITIONS) -> dict[str, tuple[str, str, str]]:
    rows = {}
    with open(path, encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            fields = line.split("\t", 3)
            if len(fields) != 4:
                raise ValueError(f"{path}:{line_number}: expected name, disposition, reproducer, evidence")
            name, disposition, reproducer, evidence = (field.strip() for field in fields)
            if name in rows:
                raise ValueError(f"{path}:{line_number}: duplicate gap {name!r}")
            rows[name] = (disposition, reproducer, evidence)
    return rows


def check(parity_path: str = PARITY, sidecar_path: str = DISPOSITIONS) -> tuple[bool, list[str]]:
    errors = []
    expected_rows = canonical_rows(read_parity(parity_path))
    expected = {name: (disposition, reproducer, evidence)
                for name, disposition, reproducer, evidence in expected_rows}
    try:
        actual = read_sidecar(sidecar_path)
    except (OSError, ValueError) as exc:
        return False, [str(exc)]
    if set(actual) != set(expected):
        errors.append("sidecar gap names do not match PARITY.tsv")
        errors.append("missing: " + ", ".join(sorted(set(expected) - set(actual))))
        errors.append("stale: " + ", ".join(sorted(set(actual) - set(expected))))
    for name, (disposition, reproducer, evidence) in actual.items():
        if disposition not in VALID:
            errors.append(f"{name}: unknown disposition {disposition!r}")
        if not reproducer or not evidence:
            errors.append(f"{name}: reproducer and evidence are mandatory")
        if reproducer.startswith("generated:"):
            if not generated_probe(name).startswith(f";; GAP-PROBE: {name}\n"):
                errors.append(f"{name}: generated reproducer is not live")
        else:
            full = os.path.join(REPO, reproducer)
            if not os.path.isfile(full):
                errors.append(f"{name}: reproducer does not exist: {reproducer}")
    for name, (disposition, reproducer, evidence) in expected.items():
        if name not in actual:
            continue
        if actual[name] != expected[name]:
            errors.append(f"{name}: sidecar is stale; regenerate with --write")
    return not errors, errors


def write_sidecar(path: str = DISPOSITIONS) -> int:
    rows = canonical_rows(read_parity())
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("# name<TAB>disposition<TAB>reproducer<TAB>PARITY.tsv evidence\n")
        for row in rows:
            handle.write("\t".join(row) + "\n")
    print(f"wrote {len(rows)} VM gap dispositions to {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--parity", default=PARITY)
    parser.add_argument("--sidecar", default=DISPOSITIONS)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    if args.write:
        return write_sidecar(args.sidecar)
    passed, errors = check(args.parity, args.sidecar)
    print("vm_gap_canonicalization: " + ("PASS" if passed else "FAIL"))
    print(f"  gap rows    : {len(canonical_rows(read_parity(args.parity)))}")
    print(f"  sidecar     : {args.sidecar}")
    for error in errors:
        print("  ERROR: " + error, file=sys.stderr)
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
