#!/usr/bin/env python3
"""check_builtin_classification.py — the stablehlo_builtin_classification_complete gate.

Reads the compiler's real builtin registry (tests/coverage/language_surface.json,
generated by scripts/gen_language_surface.py directly from lib/backend/
eshkol_compiler.c BUILTINS[], lib/backend/eshkol_vm.c BUILTINS[], and the
quantum/PQC agent-module surface — never hand-maintained) and
lib/backend/xla/builtin_classification.yaml (the Eshkol-S label for every
builtin, see docs/design/ESHKOL_S_FRAGMENT.md) and FAILS if any of:

  1. A builtin in the registry has no entry in the YAML (unclassified).
  2. A YAML entry names a builtin that does not exist in the registry
     (stale/typo'd name).
  3. A YAML entry's label is not one of device / host / host-with-device-inner.
  4. A host-with-device-inner entry has no inner_op (or an empty one).
  5. The registry has a duplicate name (would make "every builtin has an
     entry" ambiguous) — defensive; gen_language_surface.py already
     deduplicates, but this gate does not trust that silently.

Regenerating tests/coverage/language_surface.json is the caller's
responsibility (scripts/gen_language_surface.py) when the compiler's
registry has changed; this script reads whatever manifest currently exists
on disk (fresh regeneration is one process running a full compiler-source
parse, so run_xla_gate.sh does not force it silently — see --refresh-surface
below if a caller wants that explicitly).

Exit status: 0 if every registry builtin is classified and every YAML entry
is valid; 1 otherwise, with every gap printed (not just the first).

Usage:
  python3 scripts/check_builtin_classification.py
  python3 scripts/check_builtin_classification.py --refresh-surface
  python3 scripts/check_builtin_classification.py --surface PATH --classification PATH
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SURFACE = os.path.join(REPO, "tests", "coverage", "language_surface.json")
DEFAULT_CLASSIFICATION = os.path.join(
    REPO, "lib", "backend", "xla", "builtin_classification.yaml"
)
GEN_SURFACE = os.path.join(REPO, "scripts", "gen_language_surface.py")

VALID_LABELS = {"device", "host", "host-with-device-inner"}


class CheckError(Exception):
    """Raised for a condition that prevents the gate from reaching a
    verdict at all (missing/unparseable input) — distinct from a
    classification gap, which is reported as a finding, not an exception."""


def _load_yaml(path):
    try:
        import yaml  # type: ignore
    except ImportError as exc:
        raise CheckError(
            "PyYAML is required to read the classification file "
            "(pip install pyyaml)"
        ) from exc
    if not os.path.isfile(path):
        raise CheckError(f"classification file not found: {path}")
    with open(path, encoding="utf-8") as fh:
        try:
            return yaml.safe_load(fh)
        except Exception as exc:  # noqa: BLE001
            raise CheckError(f"classification file is not parseable YAML: {exc}") from exc


def _load_surface(path):
    if not os.path.isfile(path):
        raise CheckError(
            f"registry manifest not found: {path} "
            f"(generate it with: python3 {os.path.relpath(GEN_SURFACE, REPO)})"
        )
    with open(path, encoding="utf-8") as fh:
        try:
            return json.load(fh)
        except json.JSONDecodeError as exc:
            raise CheckError(f"registry manifest is not parseable JSON: {exc}") from exc


def refresh_surface(out_path):
    result = subprocess.run(
        [sys.executable, GEN_SURFACE, "--out", out_path],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise CheckError(
            "scripts/gen_language_surface.py failed to regenerate the "
            f"registry manifest (exit {result.returncode}):\n{result.stderr}"
        )


def check(surface_path, classification_path):
    """Returns (ok, findings, summary_counts)."""
    surface = _load_surface(surface_path)
    classification = _load_yaml(classification_path)

    if not isinstance(classification, dict) or "builtins" not in classification:
        raise CheckError(
            f"{classification_path} does not have a top-level 'builtins' mapping"
        )

    registry_builtins = surface.get("builtins")
    if not isinstance(registry_builtins, list):
        raise CheckError(f"{surface_path} does not have a top-level 'builtins' list")

    findings = []

    # --- Registry duplicates (defensive) ---
    registry_names = []
    seen_registry = set()
    duplicate_registry_names = set()
    for b in registry_builtins:
        name = b.get("name")
        if name is None:
            findings.append("registry entry with no 'name' field")
            continue
        registry_names.append(name)
        if name in seen_registry:
            duplicate_registry_names.add(name)
        seen_registry.add(name)
    if duplicate_registry_names:
        for name in sorted(duplicate_registry_names):
            findings.append(
                f"registry manifest lists {name!r} more than once "
                "(gen_language_surface.py should deduplicate; this is a "
                "registry-manifest defect, not a classification gap)"
            )

    registry_set = set(registry_names)
    yaml_entries = classification["builtins"]
    if not isinstance(yaml_entries, dict):
        raise CheckError(f"{classification_path}'s 'builtins' key is not a mapping")

    yaml_names = set(yaml_entries.keys())

    # --- 1. Unclassified: in registry, not in YAML ---
    unclassified = sorted(registry_set - yaml_names)
    for name in unclassified:
        findings.append(f"UNCLASSIFIED builtin (in registry, missing from "
                         f"{os.path.relpath(classification_path, REPO)}): {name!r}")

    # --- 2. Stale: in YAML, not in registry ---
    stale = sorted(yaml_names - registry_set)
    for name in stale:
        findings.append(f"STALE classification entry (names a builtin that "
                         f"does not exist in {os.path.relpath(surface_path, REPO)}): {name!r}")

    # --- 3 & 4. Per-entry validation for names that do exist in both ---
    valid_names = sorted(yaml_names & registry_set)
    label_counts = {label: 0 for label in VALID_LABELS}
    for name in valid_names:
        entry = yaml_entries[name]
        if not isinstance(entry, dict):
            findings.append(f"malformed entry for {name!r}: not a mapping")
            continue

        label = entry.get("label")
        if label not in VALID_LABELS:
            findings.append(
                f"INVALID LABEL for {name!r}: {label!r} is not one of "
                f"{sorted(VALID_LABELS)}"
            )
            continue

        rationale = entry.get("rationale")
        if not rationale or not str(rationale).strip():
            findings.append(f"MISSING RATIONALE for {name!r} (label={label!r})")

        if label == "host-with-device-inner":
            inner_op = entry.get("inner_op")
            if not inner_op or not str(inner_op).strip():
                findings.append(
                    f"MISSING inner_op for host-with-device-inner entry {name!r}"
                )

        label_counts[label] += 1

    ok = not findings
    summary = {
        "registry_total": len(registry_set),
        "classified_total": len(valid_names),
        "unclassified": len(unclassified),
        "stale": len(stale),
        "label_counts": label_counts,
    }
    return ok, findings, summary


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--surface", default=DEFAULT_SURFACE)
    parser.add_argument("--classification", default=DEFAULT_CLASSIFICATION)
    parser.add_argument(
        "--refresh-surface",
        action="store_true",
        help="regenerate the registry manifest from compiler source before checking "
             "(runs scripts/gen_language_surface.py; the default is to check "
             "whatever manifest is already on disk)",
    )
    args = parser.parse_args(argv)

    try:
        if args.refresh_surface:
            refresh_surface(args.surface)
        ok, findings, summary = check(args.surface, args.classification)
    except CheckError as exc:
        print(f"FAIL: {exc}")
        return 1

    print(f"registry builtins: {summary['registry_total']}")
    print(f"classified:        {summary['classified_total']}")
    print(f"unclassified:      {summary['unclassified']}")
    print(f"stale entries:     {summary['stale']}")
    for label in sorted(summary["label_counts"]):
        print(f"  {label}: {summary['label_counts'][label]}")

    if not ok:
        print()
        print(f"FAIL: {len(findings)} gap(s) found:")
        for finding in findings:
            print(f"  - {finding}")
        return 1

    print()
    print("PASS: every registry builtin is classified exactly once, "
          "every classification entry names a real builtin, every label "
          "is valid, every host-with-device-inner entry names its inner op.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
