#!/usr/bin/env python3
"""eshkol_swarm_status.py — regenerate .swarm/status.md from the task ledger.

Mirrors the QGTL pattern (scripts/qgtl_swarm_status.py).  Reads:

  .swarm/tasks/*.json     — task specs with id, title, status, priority,
                             workstream, owner, file_globs.
  .swarm/claims/*.json    — active claims: agent + task-id + glob set.
  .swarm/events.jsonl     — append-only event ledger.

Writes .swarm/status.md when --write-status is given; otherwise prints to
stdout.  Exits 0 on success.

Usage:
    python3 scripts/eshkol_swarm_status.py [--write-status]
"""
import argparse
import datetime as _dt
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SWARM = REPO / ".swarm"
TASKS_DIR = SWARM / "tasks"
CLAIMS_DIR = SWARM / "claims"
EVENTS_FILE = SWARM / "events.jsonl"
STATUS_FILE = SWARM / "status.md"


def _load_tasks():
    tasks = []
    if not TASKS_DIR.exists():
        return tasks
    for f in sorted(TASKS_DIR.glob("*.json")):
        try:
            tasks.append(json.loads(f.read_text()))
        except Exception as e:
            print(f"warning: failed to parse {f}: {e}", file=sys.stderr)
    return tasks


def _load_claims():
    claims = []
    if not CLAIMS_DIR.exists():
        return claims
    for f in sorted(CLAIMS_DIR.glob("*.json")):
        try:
            claims.append(json.loads(f.read_text()))
        except Exception as e:
            print(f"warning: failed to parse {f}: {e}", file=sys.stderr)
    return claims


def _load_events():
    events = []
    if not EVENTS_FILE.exists():
        return events
    for line in EVENTS_FILE.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            events.append(json.loads(line))
        except Exception as e:
            print(f"warning: failed to parse event line: {e}", file=sys.stderr)
    return events


def _by_status(tasks):
    out = {"pending": 0, "active": 0, "done": 0, "blocked": 0}
    for t in tasks:
        s = t.get("status", "pending")
        out[s] = out.get(s, 0) + 1
    return out


def _ready_work(tasks):
    """Tasks with status=pending and no unmet blocked_by."""
    done_ids = {t["id"] for t in tasks if t.get("status") == "done"}
    ready = []
    for t in tasks:
        if t.get("status") != "pending":
            continue
        blockers = t.get("blocked_by", []) or []
        if all(b in done_ids for b in blockers):
            ready.append(t)
    ready.sort(key=lambda t: ({"high": 0, "medium": 1, "low": 2}.get(t.get("priority", "medium"), 1), t["id"]))
    return ready


def _render_table(rows, headers):
    if not rows:
        return f"| {' | '.join(headers)} |\n| {' | '.join('---' for _ in headers)} |\n| *(none)* {'| ' * (len(headers) - 1)}|\n"
    lines = [f"| {' | '.join(headers)} |"]
    lines.append(f"| {' | '.join('---' for _ in headers)} |")
    for row in rows:
        lines.append(f"| {' | '.join(str(c) for c in row)} |")
    return "\n".join(lines) + "\n"


def _render_status(tasks, claims, events):
    now = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    counts = _by_status(tasks)
    latest_event = events[-1] if events else None

    out = ["# Eshkol Swarm Status", ""]
    out.append(f"This file is generated by `python3 scripts/eshkol_swarm_status.py --write-status`.")
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append(f"- tasks: `{len(tasks)}`")
    out.append(f"- active claims: `{len(claims)}`")
    if latest_event:
        ev_ts = latest_event.get("ts", "?")
        ev_type = latest_event.get("type", "?")
        ev_actor = latest_event.get("actor", "?")
        out.append(f"- latest event: `{ev_ts}` `{ev_type}` by `{ev_actor}`")
    else:
        out.append(f"- latest event: *(none)*")
    states_str = " ".join(f"{k}={v}" for k, v in counts.items() if v > 0)
    out.append(f"- task states: `{states_str if states_str else 'all pending'}`")
    out.append("")

    out.append("## Active Claims")
    out.append("")
    claim_rows = [
        [c.get("agent", "?"), c.get("role", "?"), c.get("task_id", "?"), ", ".join(c.get("file_globs", []))]
        for c in claims
    ]
    out.append(_render_table(claim_rows, ["Agent", "Role", "Task", "File Globs"]))

    out.append("## Ready Work")
    out.append("")
    ready = _ready_work(tasks)
    ready_rows = [
        [t["id"], t.get("priority", "medium"), t.get("workstream", "?"), t.get("title", "?")]
        for t in ready
    ]
    out.append(_render_table(ready_rows, ["Task", "Priority", "Workstream", "Title"]))

    out.append("## Latest Events")
    out.append("")
    recent = events[-10:]
    event_rows = [
        [
            f"`{e.get('ts', '?')}`",
            f"`{e.get('type', '?')}`",
            f"`{e.get('actor', '?')}`",
            e.get("summary", ""),
        ]
        for e in recent
    ]
    out.append(_render_table(event_rows, ["Time", "Type", "Actor", "Summary"]))

    out.append("")
    out.append(f"*Generated: {now}*")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-status", action="store_true", help="Write to .swarm/status.md instead of stdout.")
    args = ap.parse_args(argv)

    tasks = _load_tasks()
    claims = _load_claims()
    events = _load_events()
    rendered = _render_status(tasks, claims, events)

    if args.write_status:
        STATUS_FILE.write_text(rendered)
        print(f"wrote {STATUS_FILE} — tasks={len(tasks)} claims={len(claims)} events={len(events)}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
