#!/usr/bin/env python3
"""Generate exact-rational denominator references for frozen binary64 points."""
from fractions import Fraction
import math
from pathlib import Path

root = Path(__file__).resolve().parents[1]
rows = []
for n in range(1, 65):
    coordinate = 1.0 / math.sqrt(n)
    for _ in range(4):
        coordinate = math.nextafter(coordinate, 0.0)
    exact = 1 - n * Fraction.from_float(coordinate) ** 2
    assert exact > 0
    rows.append(f'    {{{coordinate.hex()}, {float(exact).hex()}}}, // n={n}')
header = '''// Generated by scripts/gen_geometric_boundary_golden.py.
// Each coordinate is an exact binary64 fixture. The denominator is the
// correctly rounded value of 1 - n * coordinate^2 computed using Fraction,
// with no floating-point multiply/sum/cancellation in the reference.
// Freeze inputs as well as answers so host sqrt rounding cannot change a case.
#ifndef ESHKOL_GEOMETRIC_BOUNDARY_GOLDEN_H
#define ESHKOL_GEOMETRIC_BOUNDARY_GOLDEN_H
struct GeometricBoundaryGolden { double coordinate; double denominator; };
static const GeometricBoundaryGolden geometric_boundary_golden[] = {
''' + '\n'.join(rows) + '\n};\n#endif\n'
(root / 'tests/bridge/geometric_boundary_golden.h').write_text(header)
