#!/usr/bin/env python3
"""gen_numeric_depth.py — depth/scale-parametric NUMERIC TOWER test generator
(adversarial testing pillar P6d, .swarm/DEPTH_PARAMETRIC_TESTING.md).

Sweeps the R7RS numeric tower to arbitrary scale/depth with EXACT ground truth
(Python arbitrary-precision int / fractions.Fraction as the oracle where possible,
analytic identities otherwise). For every family a parameter n is escalated
1..NMAX; at each n an Eshkol self-check compares the tower operation against a
Python-computed literal baked into the source. A SILENT WRONG value at any n is a
compiler bug; a clean crash/limit is a documented capability boundary.

Each generated tests/numeric_depth/<family>.esk prints one line per n:

    PASS  <family> <n>
    WRONG <family> <n> got=<value> want=<value>

and a final "DONE <family>" marker (its absence => the family hit a LIMIT — a
crash/compile-fail — and the boundary is the last emitted n). Every line is
flushed so the boundary survives stdout buffering when an AOT binary crashes.

The companion scripts/run_numeric_depth.sh runs each family under BOTH -r (JIT)
and AOT, classifies PASS / WRONG / LIMIT, records the max-correct-n per family,
and separates NEW silent-wrong regressions from documented degradation
boundaries listed in the emitted manifest (tests/numeric_depth/manifest.json).

Usage:
    python3 scripts/gen_numeric_depth.py [--out-dir tests/numeric_depth] [--scale S]

--scale multiplies every family's NMAX (default 1.0) so the sweep can be pushed
harder in the nightly lane without editing the generator.
"""

import argparse
import json
import os
from fractions import Fraction

# ---------------------------------------------------------------------------
# helpers to build Eshkol source
# ---------------------------------------------------------------------------

HEADER = "; AUTO-GENERATED by scripts/gen_numeric_depth.py — do not edit by hand.\n(require stdlib)\n"

FLUSH = "(flush-output-port (current-output-port))"


def check_bool(family, n, ok_expr, got_expr, want_str):
    """Emit an Eshkol form that prints PASS/WRONG for a boolean self-check.

    ok_expr  : Eshkol expression that is #t iff the tower op is correct.
    got_expr : Eshkol expression displayed on WRONG (the actual value).
    want_str : literal string shown as the expected value on WRONG.
    """
    return (
        f"(if {ok_expr}\n"
        f"    (begin (display \"PASS {family} {n}\") (newline))\n"
        f"    (begin (display \"WRONG {family} {n} got=\") (display {got_expr})"
        f" (display \" want={want_str}\") (newline)))\n"
        f"{FLUSH}\n"
    )


def done(family):
    return f'(display "DONE {family}") (newline) {FLUSH}\n'


# ---------------------------------------------------------------------------
# Family 1: bignum magnitude — (expt B n) and +/-/*/quotient/remainder/gcd,
# number->string round-trip, all EXACT vs Python big-int.
# ---------------------------------------------------------------------------

def gen_bignum_magnitude(scale):
    fam = "bignum_magnitude"
    ns = list(range(1, 65)) + list(range(70, int(1024 * scale) + 1, 32))
    lines = [HEADER, f'; Family: {fam} — (expt B n), arithmetic, string round-trip vs Python int\n']
    for n in ns:
        # base-2 power; exact ground truth
        v2 = 2 ** n
        # exact power equality
        lines.append(check_bool(fam, n,
                                f"(= (expt 2 {n}) {v2})",
                                f"(expt 2 {n})", str(v2)))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


def gen_bignum_arith(scale):
    fam = "bignum_arith"
    ns = list(range(20, int(400 * scale) + 1, 10))
    lines = [HEADER, f'; Family: {fam} — +/-/* (closed ops) on 10^n,3^n vs Python int\n']
    for n in ns:
        a = 10 ** n
        b = 3 ** n
        s = a + b
        d = a - b
        p = a * b
        ok = (f"(and (= (+ {a} {b}) {s})"
              f" (= (- {a} {b}) {d})"
              f" (= (* {a} {b}) {p}))")
        lines.append(check_bool(fam, n, ok, f"(+ {a} {b})", f"add/sub/mul@10^{n}"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1],
                "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


def gen_bignum_divmod(scale):
    """quotient/remainder on bignums. FINDING (ESH): bignum division is wrong
    at scale — the fundamental identity a = q*b + r fails (remainder, and at
    larger scale the quotient too, are silently incorrect). Verifies value vs
    Python AND the reconstruction identity so the runner pins where it breaks.
    """
    fam = "bignum_divmod"
    ns = list(range(20, int(200 * scale) + 1, 5))
    lines = [HEADER, f'; Family: {fam} — quotient/remainder + (= a (+ (* q b) r)) on 10^n,7^n\n']
    for n in ns:
        a = 10 ** n
        b = 7 ** n
        q = a // b
        r = a % b
        ok = (f"(and (= (quotient {a} {b}) {q})"
              f" (= (remainder {a} {b}) {r})"
              f" (= {a} (+ (* (quotient {a} {b}) {b}) (remainder {a} {b}))))")
        lines.append(check_bool(fam, n, ok, f"(remainder {a} {b})", f"q={q} r={r}"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1],
                "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


def gen_bignum_gcd(scale):
    """gcd across the int64<->bignum boundary. FINDING (ESH): gcd returns
    INT64_MAX (2^63-1) whenever BOTH operands are bignums, regardless of the
    true (often small) result — a silent wrong value. Operands here are
    a = 3*2^n and b = 5*2^n (true gcd = 2^n); both cross into bignum at n>=62.
    """
    import math
    fam = "bignum_gcd"
    ns = list(range(1, int(128 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — gcd(3*2^n, 5*2^n)=2^n across int64<->bignum vs Python\n']
    expected_wrong = []
    for n in ns:
        a = 3 * 2 ** n
        b = 5 * 2 ** n
        g = math.gcd(a, b)  # == 2**n
        ok = f"(= (gcd {a} {b}) {g})"
        lines.append(check_bool(fam, n, ok, f"(gcd {a} {b})", str(g)))
        if a > 2 ** 63 - 1 or b > 2 ** 63 - 1:
            expected_wrong.append(n)  # any-operand-bignum: known gcd bug
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1],
                "known_degradation": [], "expected_wrong": expected_wrong}
    return fam, "".join(lines), manifest


def gen_bignum_roundtrip(scale):
    fam = "bignum_roundtrip"
    ns = list(range(1, int(600 * scale) + 1, 7))
    lines = [HEADER, f'; Family: {fam} — number->string / string->number round-trip vs Python\n']
    for n in ns:
        v = 10 ** n  # decimal digits = n+1
        s = str(v)
        # value = round-trip through string, and printed string matches Python's
        ok = (f"(and (= (string->number (number->string (expt 10 {n}))) {v})"
              f" (equal? (number->string (expt 10 {n})) \"{s}\")"
              f" (= (string-length (number->string (expt 10 {n}))) {len(s)}))")
        lines.append(check_bool(fam, n, ok,
                                f"(string-length (number->string (expt 10 {n})))",
                                f"digits={len(s)}"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


# ---------------------------------------------------------------------------
# Family 2: rational depth — harmonic sum & product, EXACT reduced form vs
# Python Fraction. Pins the bignum-in-rational contagion (ESH-0105/0110):
# result silently becomes an inexact double once num/denom exceeds int64.
# ---------------------------------------------------------------------------

def gen_rational_harmonic(scale):
    fam = "rational_harmonic"
    ns = list(range(1, int(80 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — (+ 1/1 1/2 ... 1/n) EXACT reduced vs Python Fraction\n']
    # Build the sum expression incrementally so depth n is literally n-deep.
    known_deg = []
    for n in ns:
        f = sum(Fraction(1, k) for k in range(1, n + 1))
        p, q = f.numerator, f.denominator
        # n-deep nested sum: (+ (+ (+ 1/1 1/2) 1/3) ...)
        expr = "1/1"
        for k in range(2, n + 1):
            expr = f"(+ {expr} 1/{k})"
        # EXACT check: value equals reduced p/q AND result is exact.
        # want (R7RS): exact reduced p/q. Both must hold to PASS.
        # Build the expected via runtime division (/ p q) — a p/q *literal*
        # with bignum components is rejected by the parser (ESH finding), so
        # we must not bake one here.
        val_ok = f"(= {expr} (/ {p} {q}))" if q != 1 else f"(= {expr} {p})"
        exact_ok = f"(exact? {expr})"
        ok = f"(and {val_ok} {exact_ok})"
        lines.append(check_bool(fam, n, ok, expr, f"{p}/{q} exact"))
        # denominator > 2^63 -> known degradation to double (exactness lost)
        if q > 2 ** 63 or p > 2 ** 63:
            known_deg.append(n)
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1],
                "known_degradation": known_deg, "expected_wrong": known_deg}
    return fam, "".join(lines), manifest


def gen_rational_product(scale):
    fam = "rational_product"
    ns = list(range(1, int(40 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — product of (k+1)/k, growing num/denom, EXACT vs Fraction\n']
    known_deg = []
    for n in ns:
        f = Fraction(1)
        for k in range(1, n + 1):
            f *= Fraction(k + 1, k)  # telescopes to (n+1)/1 in value, but force big denom
        # Force a genuinely large reduced denominator: product of 1/prime-ish
        f = Fraction(1)
        for k in range(2, n + 2):
            f *= Fraction(1, k)      # = 1/(n+1)!  -> denominator explodes
        p, q = f.numerator, f.denominator
        expr = "(/ 1 2)"
        for k in range(3, n + 2):
            expr = f"(* {expr} (/ 1 {k}))"
        val_ok = f"(= {expr} (/ {p} {q}))" if q != 1 else f"(= {expr} {p})"
        ok = f"(and {val_ok} (exact? {expr}))"
        lines.append(check_bool(fam, n, ok, expr, f"{p}/{q} exact"))
        if q > 2 ** 63 or p > 2 ** 63:
            known_deg.append(n)
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1],
                "known_degradation": known_deg, "expected_wrong": known_deg}
    return fam, "".join(lines), manifest


# ---------------------------------------------------------------------------
# Family 3: exactness contagion chains — R7RS result-type at each step.
# (a) all-exact integer chain of depth n must stay EXACT (even into bignum).
# (b) tail-inexact chain must be INEXACT for all n once an inexact appears.
# ---------------------------------------------------------------------------

def gen_exactness_contagion(scale):
    fam = "exactness_contagion"
    ns = list(range(1, int(60 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — R7RS exact/inexact result type at depth n\n']
    for n in ns:
        # all-exact nested add: (((1 + 2) + 3) + ... + n) — must be exact always.
        exact_expr = "1"
        for k in range(2, n + 1):
            exact_expr = f"(+ {exact_expr} {k})"
        # tail-inexact: add 0.5 at the OUTER level -> whole thing inexact.
        inexact_expr = f"(+ {exact_expr} 0.5)"
        # inject inexact at the INNERMOST level -> must propagate out to inexact.
        inner_inexact = "1.0"
        for k in range(2, n + 1):
            inner_inexact = f"(+ {inner_inexact} {k})"
        ok = (f"(and (exact? {exact_expr})"          # all-exact stays exact
              f" (inexact? {inexact_expr})"          # outer inexact contaminates
              f" (inexact? {inner_inexact}))")       # inner inexact propagates out
        lines.append(check_bool(fam, n, ok, exact_expr, "exact/inexact-typed"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


# ---------------------------------------------------------------------------
# Family 4: complex arithmetic chains — n-fold products/powers vs analytic.
# i^n cycles (1, i, -1, -i); (r e^{iθ})^n has magnitude r^n and angle nθ.
# Complex is inexact (double) so compare within a tolerance.
# ---------------------------------------------------------------------------

def gen_complex_power(scale):
    import math
    fam = "complex_power"
    ns = list(range(1, int(128 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — (make-rectangular ..)^n vs analytic re/im/magnitude\n']
    # fixed base r*e^{iθ} with r slightly >1 so magnitude grows measurably
    r = 1.03
    theta = 0.4
    re0 = r * math.cos(theta)   # real floats (cmath.* would yield complex reprs)
    im0 = r * math.sin(theta)
    lines.append(f"(define zb (make-rectangular {re0!r} {im0!r}))\n")
    for n in ns:
        w = complex(re0, im0) ** n
        mag = abs(w)
        # tolerance scales with magnitude (float rounding accumulates over n mults)
        tol = max(1e-9, abs(mag) * 1e-9 * n)
        # i^n cycle: exact-ish analytic values
        icyc = [(1.0, 0.0), (0.0, 1.0), (-1.0, 0.0), (0.0, -1.0)][n % 4]
        ok = (f"(let ((zn (expt zb {n})) (in (expt (make-rectangular 0.0 1.0) {n})))"
              f" (and (< (abs (- (real-part zn) {w.real!r})) {tol!r})"
              f" (< (abs (- (imag-part zn) {w.imag!r})) {tol!r})"
              f" (< (abs (- (magnitude zn) {mag!r})) {tol!r})"
              f" (< (abs (- (real-part in) {icyc[0]!r})) 1e-6)"
              f" (< (abs (- (imag-part in) {icyc[1]!r})) 1e-6)))")
        lines.append(check_bool(fam, n, ok, f"(real-part (expt zb {n}))",
                                f"re={w.real:.6g} im={w.imag:.6g}"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


# ---------------------------------------------------------------------------
# Family 5: mixed-tower coercion depth — int -> rational -> real -> complex.
# At each level verify the R7RS predicate widening holds.
# ---------------------------------------------------------------------------

def gen_tower_coercion(scale):
    fam = "tower_coercion"
    ns = list(range(1, int(40 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — int->rational->real->complex coercion at depth n\n']
    for n in ns:
        # Depth-n cycle through the tower, re-widening each round.
        # Start exact int, add exact rational (stays exact/rational),
        # add inexact real (becomes inexact real), add complex (becomes complex).
        # Repeat n times; the final value must satisfy complex?/number? and,
        # crucially, adding a pure-imaginary must produce nonzero imag-part.
        expr = "1"
        for _ in range(n):
            expr = f"(+ {expr} 1/3)"           # exact rational rung
        rat_ok = f"(and (exact? {expr}) (rational? {expr}))"
        # widen to real
        rexpr = f"(+ {expr} 0.5)"
        real_ok = f"(and (inexact? {rexpr}) (real? {rexpr}))"
        # widen to complex
        cexpr = f"(+ {rexpr} (make-rectangular 0.0 1.0))"
        cplx_ok = f"(and (complex? {cexpr}) (> (imag-part {cexpr}) 0.5))"
        # rational sum value is exactly 1 + n/3
        rp = 3 + n
        ok = f"(and {rat_ok} (= {expr} {rp}/3) {real_ok} {cplx_ok})"
        lines.append(check_bool(fam, n, ok, expr, f"{rp}/3 -> real -> complex"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


# ---------------------------------------------------------------------------
# Family 6: numeric extremes at depth — repeated doubling across the
# int64<->bignum boundary and back; nan/inf propagation through n-deep exprs.
# ---------------------------------------------------------------------------

def gen_extremes_doubling(scale):
    fam = "extremes_doubling"
    # crossing the int64<->bignum boundary happens at n=63; 1..100 covers it
    # with margin while keeping the O(n^2) nested source compilable.
    ns = list(range(1, int(100 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — 2^n by repeated doubling then halving back, vs Python int\n']
    for n in ns:
        v = 2 ** n
        # n-deep doubling: (* 2 (* 2 ... 1))
        up = "1"
        for _ in range(n):
            up = f"(* 2 {up})"
        # halve all the way back to 1 with quotient (exact integer division)
        down = f"(expt 2 {n})"
        for _ in range(n):
            down = f"(quotient {down} 2)"
        ok = (f"(and (= {up} {v})"                 # crosses int64 boundary at n=63
              f" (= (expt 2 {n}) {v})"
              f" (exact? (expt 2 {n}))"            # bignum stays exact
              f" (= {down} 1))")                   # round-trip back to 1
        lines.append(check_bool(fam, n, ok, up, str(v)))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


def gen_naninf_propagation(scale):
    fam = "naninf_propagation"
    ns = list(range(1, int(60 * scale) + 1))
    lines = [HEADER, f'; Family: {fam} — nan/inf propagate through n-deep arithmetic\n']
    for n in ns:
        # inf through n additions stays inf; nan through n stays nan.
        inf_expr = "(/ 1.0 0.0)"
        for _ in range(n):
            inf_expr = f"(+ {inf_expr} 1.0)"
        nan_expr = "(/ 0.0 0.0)"
        for _ in range(n):
            nan_expr = f"(* {nan_expr} 2.0)"
        ok = f"(and (infinite? {inf_expr}) (nan? {nan_expr}))"
        lines.append(check_bool(fam, n, ok, inf_expr, "inf & nan preserved"))
    lines.append(done(fam))
    manifest = {"family": fam, "ns": ns, "expected_max": ns[-1], "known_degradation": [], "expected_wrong": []}
    return fam, "".join(lines), manifest


GENERATORS = [
    gen_bignum_magnitude,
    gen_bignum_arith,
    gen_bignum_divmod,
    gen_bignum_gcd,
    gen_bignum_roundtrip,
    gen_rational_harmonic,
    gen_rational_product,
    gen_exactness_contagion,
    gen_complex_power,
    gen_tower_coercion,
    gen_extremes_doubling,
    gen_naninf_propagation,
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default="tests/numeric_depth")
    ap.add_argument("--scale", type=float, default=1.0)
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)
    manifests = []
    for g in GENERATORS:
        fam, text, manifest = g(args.scale)
        path = os.path.join(args.out_dir, fam + ".esk")
        with open(path, "w") as f:
            f.write(text)
        manifests.append(manifest)
        print(f"wrote {path}  ({len(manifest['ns'])} depths, "
              f"n=1..{manifest['expected_max']}, "
              f"known_degradation={len(manifest['known_degradation'])})")
    with open(os.path.join(args.out_dir, "manifest.json"), "w") as f:
        json.dump({"families": manifests, "scale": args.scale}, f, indent=2)
    print(f"wrote {os.path.join(args.out_dir, 'manifest.json')}")


if __name__ == "__main__":
    main()
