#!/usr/bin/env python3
"""gen_region_tables.py — compile the two Eshkol-S data tables into a C++ header
the region-formation pass can consult without opening a file at run time.

WHY GENERATE RATHER THAN PARSE AT RUN TIME.

The region-formation pass runs inside the compiler. A compiler that had to
locate lib/backend/xla/builtin_classification.yaml on disk to decide whether
`display` is a host builtin would answer differently depending on where it was
invoked from, and would answer "I cannot classify anything" for an installed
compiler with no source tree beside it. Since a builtin that cannot be
classified is a graph break, that failure mode is not a crash: it is a pass
that quietly stops forming regions. So the tables are compiled in.

WHY NOT WRITE THE TABLE BY HAND. There are two sources of truth already and
neither of them is C++:

  lib/backend/xla/builtin_classification.yaml   label per builtin
        (device / host / host-with-device-inner), itself generated from the
        compiler's own registry by scripts/gen_builtin_classification.py.
  lib/backend/xla/device_lowering_table.yaml    which device-labelled builtins
        have an actual StableHLO lowering, as data shared with
        tests/xla/builtin_parity_test.

A hand-written third copy would drift from both the first time either moved,
and the drift would be invisible: the pass would form a region around a
builtin nobody can lower, and the failure would surface as a compile error
inside the emitter rather than as the graph break it actually is.

Output: lib/backend/xla/region_tables.inc, committed, regenerated with

    python3 scripts/gen_region_tables.py

scripts/check_region_tables.py fails if the committed .inc and the two YAML
files disagree, which is what makes "regenerate it" a checkable instruction
rather than a hope.
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLASSIFICATION = os.path.join(REPO, "lib", "backend", "xla",
                              "builtin_classification.yaml")
LOWERING = os.path.join(REPO, "lib", "backend", "xla",
                        "device_lowering_table.yaml")
OUTPUT = os.path.join(REPO, "lib", "backend", "xla", "region_tables.inc")

LABEL_ENUM = {
    "device": "BuiltinLabel::Device",
    "host": "BuiltinLabel::Host",
    "host-with-device-inner": "BuiltinLabel::HostWithDeviceInner",
}


def load_yaml(path):
    try:
        import yaml  # type: ignore
    except ImportError:
        sys.stderr.write(
            "gen_region_tables.py needs PyYAML to read %s (pip install pyyaml)\n"
            % path)
        raise SystemExit(2)
    with open(path, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def c_string(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ord(ch) < 32 or ord(ch) > 126:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    classification = load_yaml(CLASSIFICATION)
    entries = classification.get("builtins")
    if not isinstance(entries, dict) or not entries:
        sys.stderr.write("no builtins[] map in %s\n" % CLASSIFICATION)
        return 2

    labelled = []
    for name in sorted(entries):
        label = entries[name].get("label")
        if label not in LABEL_ENUM:
            sys.stderr.write("builtin %r has unknown label %r\n" % (name, label))
            return 2
        labelled.append((name, LABEL_ENUM[label]))

    lowering = load_yaml(LOWERING)
    rows = lowering.get("builtins")
    if isinstance(rows, dict):
        lowered = sorted(rows)
    elif isinstance(rows, list):
        lowered = sorted(r["name"] for r in rows if isinstance(r, dict) and "name" in r)
    else:
        sys.stderr.write("no builtins collection in %s\n" % LOWERING)
        return 2

    core = lowering.get("core_ops")
    if not isinstance(core, dict) or not core:
        sys.stderr.write("no core_ops map in %s\n" % LOWERING)
        return 2
    core_rows = []
    for name in sorted(core):
        row = core[name]
        arities = row.get("arity") or []
        if not arities:
            sys.stderr.write("core op %r lists no arity\n" % name)
            return 2
        core_rows.append((name, row["kind"], sorted(arities),
                          row.get("arity1_kind", "")))

    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write("// lib/backend/xla/region_tables.inc\n")
        fh.write("//\n")
        fh.write("// GENERATED by scripts/gen_region_tables.py from\n")
        fh.write("//   lib/backend/xla/builtin_classification.yaml\n")
        fh.write("//   lib/backend/xla/device_lowering_table.yaml\n")
        fh.write("// Do not hand-edit: scripts/check_region_tables.py compares this\n")
        fh.write("// file against both of those and fails if they have diverged.\n")
        fh.write("//\n")
        fh.write("// Both arrays are sorted by name so the pass can binary-search them.\n")
        fh.write("\n")
        fh.write("static const RegionBuiltinLabel kBuiltinLabels[] = {\n")
        for name, label in labelled:
            fh.write("    {%s, %s},\n" % (c_string(name), label))
        fh.write("};\n\n")
        fh.write("static const char* const kLoweredBuiltins[] = {\n")
        for name in lowered:
            fh.write("    %s,\n" % c_string(name))
        fh.write("};\n\n")
        fh.write("static const RegionCoreOp kCoreOps[] = {\n")
        for name, kind, arities, arity1 in core_rows:
            mask = 0
            for a in arities:
                if 0 <= a < 32:
                    mask |= 1 << a
            fh.write("    {%s, DeviceOpKind::%s, 0x%08xu, %s},\n"
                     % (c_string(name), kind, mask,
                        ("DeviceOpKind::" + arity1) if arity1
                        else ("DeviceOpKind::" + kind)))
        fh.write("};\n")

    sys.stdout.write("%s: %d labels, %d lowered builtins, %d core ops\n"
                     % (os.path.relpath(OUTPUT, REPO), len(labelled),
                        len(lowered), len(core_rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
