#!/usr/bin/env python3
"""gen_tensor_collection_depth.py — depth-parametric TENSOR / COLLECTION / STRING
test generator (adversarial depth-parametric pillar P6f).

Meta-lesson (P6): our shallow suites tested tensors of rank <=3, matmul at a
couple of sizes, and short strings. Depth-dependent bugs — a construct correct
at rank 3 but silently wrong at rank 4, a string length correct at 10^3 but
truncated at 10^6, a hash table that drops entries past some size — slip through.

Principle: for EVERY scalable tensor/collection/string construct we do NOT test
one or two sizes; we generate the construct PARAMETRICALLY at depth/size
d = 1,2,3,...,N (or 10^k) and attach a CLOSED-FORM or numpy ground truth that
scales with d. A silent wrong value at any depth is a bug; a clean compile/limit
error is a documented capability boundary; a value that differs across the
JIT (-r) / AOT-O0 / AOT-O2 axes is an axis-divergence bug.

Axes (families)
  tensor_rank     make-tensor at rank d=1..N; RESULT = (length (tensor-shape T)) -> d
  reshape_rank    reshape a flat vector into rank d;    RESULT = rank            -> d
  opchain_add     d-long chain of elementwise tensor-add; RESULT = cell(0,0)     -> 1+d
  opchain_mul     d-long chain of elementwise tensor-mul by 2; RESULT = cell     -> 2^d
  matmul_scale    NxN matmul, constant fills 0.5 * 2.0;  RESULT = cell(0,0)      -> N
  matmul_np       NxN matmul, deterministic fills, numpy oracle; RESULT = cell   -> numpy
  conv_scale      NxN ones (*) 3x3 ones, stride 1, valid; RESULT = interior cell -> 9
  nested_list     list nested d-deep, descend car^d;     RESULT = leaf           -> 42
  nested_vector   vector nested d-deep, vector-ref 0^d;  RESULT = leaf           -> 42
  hashtable_size  10^k int-keyed entries k->2k; RESULT = lookup(last)            -> 2*(n-1)
  list_length     list of length n built iteratively; RESULT = (length lst)      -> n
  string_length   (make-string n #\\x); RESULT = (string-length s)               -> n
  unicode_len     n copies of a 2-byte codepoint; RESULT = (string-length s)     -> n
  emoji_len       n copies of a 4-byte codepoint; RESULT = (string-length s)     -> n
  nul_len         string of n embedded NUL bytes; RESULT = (string-length s)     -> n

Usage:
  python3 scripts/gen_tensor_collection_depth.py [--out-dir DIR]
      [--max-rank R] [--max-chain C] [--max-nest D]

Manifest (one JSON object per line) drives the runner:
  {"family","depth","main","expected","note"}
"""
import argparse
import json
import os

try:
    import numpy as _np
except Exception:  # pragma: no cover
    _np = None

HDR = ";; GENERATED by scripts/gen_tensor_collection_depth.py -- DO NOT EDIT\n"
REQ = "(require stdlib)\n"


def w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def result(expr):
    return '(display "RESULT: ")(display %s)(newline)\n' % expr


# --------------------------------------------------------------------------
# tensor rank axis
# --------------------------------------------------------------------------

def gen_tensor_rank(d):
    # distinct dims 2,3,4,5,... so a dropped dim changes the RANK (length of
    # shape), which is what we measure — robust to element-count coincidences.
    dims = " ".join(str(k + 2) for k in range(d))
    src = HDR + REQ + (
        "(define T (make-tensor (list %s) 7.0))\n" % dims +
        result("(length (tensor-shape T))")
    )
    return src, d


def gen_reshape_rank(d):
    dims = [2] * d
    n = 1
    for x in dims:
        n *= x
    dimargs = " ".join(str(x) for x in dims)
    src = HDR + REQ + (
        "(define v (make-vector %d 1.0))\n" % n +
        "(define T (reshape v %s))\n" % dimargs +
        result("(length (tensor-shape T))")
    )
    return src, d


# --------------------------------------------------------------------------
# tensor op-composition chains
# --------------------------------------------------------------------------

def gen_opchain_add(d):
    # start at 2x2 of 1.0, add a 2x2 of 1.0 d times -> cell = 1 + d
    body = "base"
    for _ in range(d):
        body = "(tensor-add %s one)" % body
    src = HDR + REQ + (
        "(define base (make-tensor (list 2 2) 1.0))\n"
        "(define one (make-tensor (list 2 2) 1.0))\n"
        "(define R %s)\n" % body +
        result("(tensor-ref R (list 0 0))")
    )
    return src, 1 + d


def gen_opchain_mul(d):
    # start at 2x2 of 1.0, multiply by a 2x2 of 2.0 d times -> cell = 2^d
    body = "base"
    for _ in range(d):
        body = "(tensor-mul %s two)" % body
    src = HDR + REQ + (
        "(define base (make-tensor (list 2 2) 1.0))\n"
        "(define two (make-tensor (list 2 2) 2.0))\n"
        "(define R %s)\n" % body +
        result("(tensor-ref R (list 0 0))")
    )
    return src, 2 ** d


# --------------------------------------------------------------------------
# matmul / conv at scale
# --------------------------------------------------------------------------

def gen_matmul_scale(n):
    # constant fills: C[i,j] = sum_k 0.5*2.0 = n
    src = HDR + REQ + (
        "(define A (make-tensor (list %d %d) 0.5))\n" % (n, n) +
        "(define B (make-tensor (list %d %d) 2.0))\n" % (n, n) +
        "(define C (tensor-matmul A B))\n" +
        result("(tensor-ref C (list 0 0))")
    )
    return src, n


def _det_fill(n):
    # deterministic reproducible integer-valued matrix, values 1..7
    return [[(i * n + j) % 7 + 1 for j in range(n)] for i in range(n)]


def gen_matmul_np(n):
    A = _det_fill(n)
    B = _det_fill(n)
    if _np is not None:
        C = _np.array(A, dtype=float) @ _np.array(B, dtype=float)
        expected = C[0][0]
    else:
        expected = sum(A[0][k] * B[k][0] for k in range(n))
    flatA = " ".join("%.1f" % v for row in A for v in row)
    flatB = " ".join("%.1f" % v for row in B for v in row)
    exp = int(expected) if float(expected).is_integer() else expected
    src = HDR + REQ + (
        "(define A (reshape (vector %s) %d %d))\n" % (flatA, n, n) +
        "(define B (reshape (vector %s) %d %d))\n" % (flatB, n, n) +
        "(define C (tensor-matmul A B))\n" +
        result("(tensor-ref C (list 0 0))")
    )
    return src, exp


def gen_conv_scale(n):
    # NxN ones convolved with 3x3 ones, stride 1, valid -> interior cell = 9
    src = HDR + REQ + (
        "(define img (make-tensor (list %d %d) 1.0))\n" % (n, n) +
        "(define ker (make-tensor (list 3 3) 1.0))\n" +
        "(define out (conv2d img ker 1))\n" +
        result("(tensor-ref out (list 0 0))")
    )
    return src, 9


# --------------------------------------------------------------------------
# nested collections
# --------------------------------------------------------------------------

def gen_nested_list(d):
    body = "42"
    for _ in range(d):
        body = "(list %s)" % body
    accessor = "leaf"
    for _ in range(d):
        accessor = "(car %s)" % accessor
    src = HDR + REQ + (
        "(define leaf %s)\n" % body +
        result(accessor)
    )
    return src, 42


def gen_nested_vector(d):
    body = "42"
    for _ in range(d):
        body = "(vector %s)" % body
    accessor = "leaf"
    for _ in range(d):
        accessor = "(vector-ref %s 0)" % accessor
    src = HDR + REQ + (
        "(define leaf %s)\n" % body +
        result(accessor)
    )
    return src, 42


# --------------------------------------------------------------------------
# scaled sizes (10^k)
# --------------------------------------------------------------------------

def gen_hashtable_size(n):
    src = HDR + REQ + (
        "(define h (make-hash-table))\n"
        "(let loop ((i 0))\n"
        "  (when (< i %d)\n" % n +
        "    (hash-table-set! h i (* i 2))\n"
        "    (loop (+ i 1))))\n" +
        result("(hash-table-ref h %d #f)" % (n - 1))
    )
    return src, 2 * (n - 1)


def gen_list_length(n):
    src = HDR + REQ + (
        "(define lst\n"
        "  (let loop ((i 0) (acc (quote ())))\n"
        "    (if (< i %d) (loop (+ i 1) (cons i acc)) acc)))\n" % n +
        result("(length lst)")
    )
    return src, n


def gen_string_length(n):
    src = HDR + REQ + (
        "(define s (make-string %d #\\x))\n" % n +
        result("(string-length s)")
    )
    return src, n


def gen_unicode_len(n):
    # lambda U+03BB, 2-byte UTF-8
    lit = "λ" * n
    src = HDR + REQ + (
        '(define s "%s")\n' % lit +
        result("(string-length s)")
    )
    return src, n


def gen_emoji_len(n):
    # rocket U+1F680, 4-byte UTF-8, single codepoint
    lit = "\U0001f680" * n
    src = HDR + REQ + (
        '(define s "%s")\n' % lit +
        result("(string-length s)")
    )
    return src, n


def gen_nul_len(n):
    # n embedded NUL bytes built with (string #\nul ...) — string-length must
    # not truncate at the first NUL.
    chars = " ".join("#\\nul" for _ in range(n))
    src = HDR + REQ + (
        "(define s (string %s))\n" % chars +
        result("(string-length s)")
    )
    return src, n


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir",
                    default="tests/tensor_collection_depth/generated")
    ap.add_argument("--max-rank", type=int, default=8)
    ap.add_argument("--max-chain", type=int, default=16)
    ap.add_argument("--max-nest", type=int, default=32)
    args = ap.parse_args()

    out = args.out_dir
    manifest = []

    def add(family, depth, src, expected, note=""):
        rel = "%s/d%03d.esk" % (family, depth)
        w(os.path.join(out, rel), src)
        manifest.append({"family": family, "depth": depth, "main": rel,
                         "expected": str(expected), "note": note})

    # rank axes
    for d in range(1, args.max_rank + 1):
        s, e = gen_tensor_rank(d);   add("tensor_rank", d, s, e)
        s, e = gen_reshape_rank(d);  add("reshape_rank", d, s, e)

    # op-composition chains
    for d in range(1, args.max_chain + 1):
        s, e = gen_opchain_add(d);   add("opchain_add", d, s, e)
        s, e = gen_opchain_mul(d);   add("opchain_mul", d, s, e)

    # matmul / conv at scale
    for n in [2, 4, 8, 16, 32, 64, 128, 256]:
        s, e = gen_matmul_scale(n);  add("matmul_scale", n, s, e)
    for n in [2, 3, 4, 8, 16]:
        s, e = gen_matmul_np(n);     add("matmul_np", n, s, e, "numpy oracle")
    for n in [3, 4, 8, 16, 32, 64]:
        s, e = gen_conv_scale(n);    add("conv_scale", n, s, e)

    # nested collections
    for d in range(1, args.max_nest + 1):
        s, e = gen_nested_list(d);   add("nested_list", d, s, e)
        s, e = gen_nested_vector(d); add("nested_vector", d, s, e)

    # scaled sizes (10^k)
    for n in [10, 100, 1000, 10000, 100000]:
        s, e = gen_hashtable_size(n); add("hashtable_size", n, s, e)
    for n in [10, 100, 1000, 10000, 100000, 1000000]:
        s, e = gen_list_length(n);   add("list_length", n, s, e)
        s, e = gen_string_length(n); add("string_length", n, s, e)
    # unicode / embedded-NUL: codepoint counts (R7RS: length in codepoints)
    for n in [1, 10, 100, 1000, 10000]:
        s, e = gen_unicode_len(n);   add("unicode_len", n, s, e)
        s, e = gen_emoji_len(n);     add("emoji_len", n, s, e)
    for n in [1, 2, 4, 8, 16, 64, 256]:
        s, e = gen_nul_len(n);       add("nul_len", n, s, e)

    mpath = os.path.join(out, "manifest.jsonl")
    os.makedirs(out, exist_ok=True)
    with open(mpath, "w") as f:
        for m in manifest:
            f.write(json.dumps(m) + "\n")
    print("gen_tensor_collection_depth: wrote %d programs -> %s"
          % (len(manifest), out))


if __name__ == "__main__":
    main()
