#!/usr/bin/env python3
"""gen_builtin_classification.py — derive lib/backend/xla/builtin_classification.yaml
from the compiler's real builtin registry.

This is the "never by hand" mechanism the Eshkol-S contract
(docs/design/ESHKOL_S_FRAGMENT.md, "Three labels for every builtin") calls
for: it does not invent a builtin list, it reads tests/coverage/language_surface.json
(itself generated by scripts/gen_language_surface.py directly from the
compiler/VM source — lib/backend/eshkol_compiler.c BUILTINS[], lib/backend/
eshkol_vm.c BUILTINS[], and the small quantum/PQC agent-module surface) and
assigns each of the builtins it finds exactly one of the three labels the
contract defines: device, host, host-with-device-inner.

Classification method: every builtin inherits a default label from its
language_surface.json category (CATEGORY_DEFAULT below), then a curated,
per-name override table (OVERRIDES) corrects the entries where the category
default is wrong for that specific builtin — the tape-facing half of
tensor_ad versus its pure-tensor half is the largest such split; see the
category notes inline. Every override carries its own rationale text
distinct from the category template, because an override is exactly the
judgment call this file exists to make explicit and reviewable.

Re-run this script whenever the registry changes (a builtin is added,
renamed, or removed) and re-review the diff — it is expected to require a
human decision for any newly-added builtin that does not fit an existing
category cleanly, which is why this is a checked-in generator rather than a
one-shot script: scripts/check_builtin_classification.py fails the gate the
moment the registry and the committed YAML disagree, and regenerating is
the first step of resolving that failure (followed by reviewing any name
gen_builtin_classification.py could not place confidently).

Usage:
  python3 scripts/gen_builtin_classification.py
      [--surface tests/coverage/language_surface.json]
      [--out lib/backend/xla/builtin_classification.yaml]
"""

from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SURFACE = os.path.join(REPO, "tests", "coverage", "language_surface.json")
DEFAULT_OUT = os.path.join(REPO, "lib", "backend", "xla", "builtin_classification.yaml")

DEVICE = "device"
HOST = "host"
HDI = "host-with-device-inner"

# ---------------------------------------------------------------------------
# Category defaults. See docs/design/ESHKOL_S_FRAGMENT.md for the reasoning;
# short version repeated here so this file is self-explaining without it.
# ---------------------------------------------------------------------------
CATEGORY_DEFAULT = {
    # Scalar/tensor arithmetic, comparisons, math: mostly device. The
    # arbitrary-precision exact/rational tower and complex-as-heap-value
    # subset are overridden to host below (condition 1, value domain).
    "numeric": DEVICE,
    # Riemannian/hyperbolic/spherical geometry: pure tensor arithmetic once
    # you are inside a manifold operation, per the campaign doc's explicit
    # callout of these as the S2 device-parity subject. Handle lifecycle
    # (construct/destroy/query an opaque manifold object) is overridden to
    # host below (condition 5 / host-side object lifecycle).
    "geometry": DEVICE,
    # tensor_ad mixes pure tensor arithmetic (device) with the AD tape,
    # optimizer state mutation, dataloaders, model I/O, and direct GPU
    # kernel dispatch (all host by nature). Default device, with a large
    # override block below carrying the host half explicitly.
    "tensor_ad": DEVICE,
    # Scheme vectors are heterogeneous host containers (condition 1); the
    # one geometric outlier (vector-transport) is overridden below.
    "vector": HOST,
    # True higher-order functions: host by nature (they walk a list or
    # dispatch dynamically), but the callback they invoke can itself be a
    # device region. parallel-* and vector-for-each are overridden to plain
    # host below (host-side thread-pool parallelism / pure side effect).
    "higher_order": HDI,
    # Type predicates are meaningless inside a statically-typed fragment —
    # they exist to answer "what dynamic tag does this host value carry".
    # The pure numeric-scalar predicates (zero?, nan?, ...) are overridden
    # to device below; everything else stays host.
    "predicate": HOST,
    # cons/lists excluded from the value domain outright (condition 1).
    "list_pair": HOST,
    # Strings/chars/ports excluded from the value domain (condition 1) /
    # I/O excluded by purity (condition 4).
    "string_char": HOST,
    "io_port": HOST,
    # Hash tables: host associative containers, not tensor values.
    "hash": HOST,
    # Knowledge bases, factor graphs, workspaces: consciousness-engine
    # values, explicitly excluded from the value domain (condition 1).
    "consciousness": HOST,
    # OS/thread/process/file/network/crypto/quantum-hardware FFI: host by
    # construction, no exceptions.
    "ffi_system": HOST,
    # Arena/region memory management: host runtime bookkeeping.
    "memory_region": HOST,
    # Promises, force, exception handling: non-local/side-effecting control
    # excluded by condition 3. `not` is a pure boolean op and is overridden
    # to device below.
    "control_flow": HOST,
    # Reflection, eval, error objects, environments: meta-language features
    # with no device meaning.
    "misc_core": HOST,
    # Grab-bag: mostly host (i128 arbitrary-precision, parameter/fluid
    # binding runtime, symbol generation, consciousness constructors,
    # string formatting); a few numeric-duplicate internal helpers are
    # overridden to device below.
    "misc": HOST,
}

# ---------------------------------------------------------------------------
# Rationale templates for entries that keep their category default. Devices
# name the StableHLO mechanism at the category level; the contract document
# has the exact op-by-op mapping this refers to.
# ---------------------------------------------------------------------------
CATEGORY_RATIONALE = {
    ("numeric", DEVICE):
        "Scalar arithmetic, comparison, or elementary-function primitive on "
        "a StableHLO-representable element type; has a direct StableHLO op "
        "(add/subtract/multiply/divide/compare/exponential/log/power/sine/"
        "cosine/...) or a CHLO-style decomposition into those ops (e.g. "
        "gcd/lcm decompose into a bounded stablehlo.while computing "
        "repeated remainder; bit ops map to shift_left/shift_right_logical/"
        "shift_right_arithmetic/and/or/xor/not/popcnt). See "
        "docs/design/ESHKOL_S_FRAGMENT.md condition 5.",
    ("geometry", DEVICE):
        "Riemannian/hyperbolic/spherical/Euclidean manifold computation "
        "over tensor-valued points and tangent vectors; decomposes into "
        "device-eligible tensor arithmetic (matmul, elementwise transcen"
        "dentals, reductions). See docs/design/ESHKOL_S_FRAGMENT.md "
        "condition 5 and the campaign's S2 geometric-parity target.",
    ("tensor_ad", DEVICE):
        "Pure tensor-in tensor-out computation (elementwise op, reduction, "
        "dot_general-shaped contraction, or structural reshape/transpose/"
        "pad/slice/concatenate) with a direct StableHLO op or a standard "
        "decomposition (e.g. softmax/layer-norm/attention decompose into "
        "elementwise + reduction + dot_general ops already on this list). "
        "See docs/design/ESHKOL_S_FRAGMENT.md condition 5.",
    ("higher_order", HDI):
        "Host-side traversal or dispatch (walks a list, or dispatches "
        "dynamically) whose argument procedure's body may itself be a "
        "device region when that body is in Eshkol-S. See "
        "docs/design/ESHKOL_S_FRAGMENT.md, 'Three labels for every "
        "builtin'.",
    ("predicate", HOST):
        "Dynamic-type or host-domain predicate (tests a runtime tag, or "
        "operates on a string/char/port/symbol/pair/promise/parameter/"
        "procedure value); meaningless inside a statically-typed fragment "
        "where the operand's type is already known at compile time. See "
        "docs/design/ESHKOL_S_FRAGMENT.md condition 1.",
    ("list_pair", HOST):
        "Operates on cons cells/lists, excluded from the Eshkol-S value "
        "domain by name. See docs/design/ESHKOL_S_FRAGMENT.md condition 1.",
    ("string_char", HOST):
        "Operates on strings or characters, excluded from the Eshkol-S "
        "value domain by name. See docs/design/ESHKOL_S_FRAGMENT.md "
        "condition 1.",
    ("io_port", HOST):
        "Performs I/O (port/file read or write, including port predicates "
        "and metadata queries tied to a live port), excluded by the "
        "purity condition. See docs/design/ESHKOL_S_FRAGMENT.md "
        "condition 4.",
    ("hash", HOST):
        "Operates on a hash table, a host associative container outside "
        "the Eshkol-S value domain. See docs/design/ESHKOL_S_FRAGMENT.md "
        "condition 1.",
    ("consciousness", HOST):
        "Operates on a consciousness-engine value (knowledge base, factor "
        "graph, workspace, substitution), excluded from the Eshkol-S value "
        "domain by name. See docs/design/ESHKOL_S_FRAGMENT.md condition 1.",
    ("ffi_system", HOST):
        "OS/thread/process/file/network/crypto/timing/quantum-hardware "
        "FFI; performs I/O or manages host-only resources, excluded by "
        "the purity condition and/or the value domain. See "
        "docs/design/ESHKOL_S_FRAGMENT.md conditions 1 and 4.",
    ("memory_region", HOST):
        "Arena/region memory-management runtime call; host bookkeeping "
        "with no StableHLO representation. See "
        "docs/design/ESHKOL_S_FRAGMENT.md 'What is host-only, and why'.",
    ("control_flow", HOST):
        "Non-local or side-effecting control (lazy promise construction/"
        "forcing, exception handling), excluded by the structured-control-"
        "flow condition. See docs/design/ESHKOL_S_FRAGMENT.md condition 3.",
    ("misc_core", HOST):
        "Reflection, eval, or error-object introspection; a meta-language "
        "feature with no StableHLO representation. See "
        "docs/design/ESHKOL_S_FRAGMENT.md 'What is host-only, and why'.",
    ("misc", HOST):
        "Host runtime helper (arbitrary-precision i128 arithmetic, "
        "parameter/fluid-binding machinery, symbol generation, or "
        "consciousness-object construction) with no StableHLO "
        "representation. See docs/design/ESHKOL_S_FRAGMENT.md 'What is "
        "host-only, and why'.",
}

# ---------------------------------------------------------------------------
# Per-name overrides: (label, rationale[, inner_op]).
# ---------------------------------------------------------------------------

_NUMERIC_NOT_DEVICE_REPRESENTABLE = {
    "/rational": "Constructs an arbitrary-precision exact rational, outside "
        "StableHLO's fixed-width element types.",
    "angle": "Operates on Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "complex?": "Tests membership in the tagged-heap complex-number "
        "representation, a dynamic-type predicate outside the fragment.",
    "conjugate": "Operates on Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "denominator": "Reads a component of the arbitrary-precision exact "
        "rational representation, outside StableHLO's element types.",
    "exact": "Converts into the arbitrary-precision exact numeric tower, "
        "outside StableHLO's fixed-width element types.",
    "exact->inexact": "Converts out of the arbitrary-precision exact "
        "numeric tower; the tower itself is outside the fragment's value "
        "domain even though the inexact result would be representable.",
    "imag-part": "Operates on Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "inexact": "Reads the inexact/exact numeric-tower tag, a dynamic-type "
        "distinction outside the fragment.",
    "inexact->exact": "Converts into the arbitrary-precision exact numeric "
        "tower, outside StableHLO's fixed-width element types.",
    "magnitude": "Operates on Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "make-polar": "Constructs Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "make-rational": "Constructs an arbitrary-precision exact rational, "
        "outside StableHLO's fixed-width element types.",
    "make-rectangular": "Constructs Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "number->string": "Produces a string, excluded from the value domain.",
    "numerator": "Reads a component of the arbitrary-precision exact "
        "rational representation, outside StableHLO's element types.",
    "rational?": "Tests membership in the arbitrary-precision exact "
        "rational representation, a dynamic-type predicate outside the "
        "fragment.",
    "rationalize": "Operates on the arbitrary-precision exact rational "
        "representation, outside StableHLO's fixed-width element types.",
    "real-part": "Operates on Eshkol's tagged-heap complex-number "
        "representation, not a fixed-width complex element type.",
    "string->number": "Consumes a string, excluded from the value domain.",
}

_GEOMETRY_HANDLE_LIFECYCLE = {
    "make-product-manifold": "Constructs an opaque host-side manifold "
        "handle; object construction, not a tensor computation.",
    "manifold-destroy!": "Releases a host-side manifold handle; object "
        "lifecycle, not a tensor computation, and mutates host state.",
    "manifold-handle-type": "Queries static metadata of a host-side "
        "manifold handle, not its tensor contents.",
    "manifold-dim": "Queries static metadata (declared dimension) of a "
        "host-side manifold handle, not its tensor contents.",
    "get-curvature": "Reads mutable host-side manifold-handle state.",
    "set-curvature!": "Mutates host-side manifold-handle state; violates "
        "the purity condition.",
    "transition-geometry!": "Mutates host-side manifold-handle state; "
        "violates the purity condition.",
    "make-riemannian-adam-state": "Constructs an opaque host-side "
        "optimizer-state handle; object construction, not a tensor "
        "computation.",
}

_VECTOR_OVERRIDES = {
    "vector-transport": (DEVICE,
        "Parallel-transports a tangent vector along a manifold; pure "
        "tensor arithmetic mirroring the geometry category's "
        "parallel-transport, despite being registered under the vector "
        "category."),
}

_HIGHER_ORDER_HOST_ONLY = {
    "parallel-execute": "Host-side thread-pool parallelism (OS threads), "
        "unrelated to device execution; the dispatched work is not "
        "outlined as a device region by this mechanism.",
    "parallel-filter": "Host-side thread-pool parallelism (OS threads), "
        "unrelated to device execution.",
    "parallel-fold": "Host-side thread-pool parallelism (OS threads), "
        "unrelated to device execution.",
    "parallel-for-each": "Host-side thread-pool parallelism (OS threads) "
        "invoked purely for side effects; also excluded by the purity "
        "condition.",
    "parallel-map": "Host-side thread-pool parallelism (OS threads), "
        "unrelated to device execution.",
    "vector-for-each": "Invoked purely for side effects on a host vector; "
        "excluded by the purity condition, unlike value-producing map.",
}

_HDI_INNER_OP = "the argument procedure's body, when that body is itself in Eshkol-S"

_PREDICATE_NUMERIC_SCALAR = {
    "zero?": "Pure numeric-scalar predicate (compare against the additive "
        "identity); StableHLO compare op.",
    "positive?": "Pure numeric-scalar predicate; StableHLO compare op.",
    "negative?": "Pure numeric-scalar predicate; StableHLO compare op.",
    "odd?": "Pure numeric-scalar predicate on a fixed-width integer; "
        "decomposes into a bitwise-and with 1 and a compare.",
    "even?": "Pure numeric-scalar predicate on a fixed-width integer; "
        "decomposes into a bitwise-and with 1 and a compare.",
    "nan?": "Pure numeric-scalar predicate; decomposes into a "
        "self-compare (StableHLO NaN is not equal to itself under "
        "stablehlo.compare).",
    "finite?": "Pure numeric-scalar predicate; direct stablehlo.is_finite.",
    "infinite?": "Pure numeric-scalar predicate; decomposes into "
        "is_finite and a NaN check.",
}

_CONTROL_FLOW_NOT = {
    "not": (DEVICE, "Pure boolean negation on a StableHLO-representable "
        "boolean scalar/tensor; direct stablehlo.not."),
}

_MISC_NUMERIC_DUPLICATES = {
    "_atan1": (DEVICE, "Internal single-argument atan helper; same "
        "classification as atan."),
    "_max2": (DEVICE, "Internal binary-max helper; same classification "
        "as max."),
    "_min2": (DEVICE, "Internal binary-min helper; same classification "
        "as min."),
}

_TENSOR_AD_HOST = {
    # AD tape machinery — see docs/design/ESHKOL_S_FRAGMENT.md's explicit
    # "the tape" host callout.
    "ad-abs": "Records/replays against the host AD tape.",
    "ad-add": "Records/replays against the host AD tape.",
    "ad-backward": "Runs the reverse pass over the host AD tape.",
    "ad-const": "Constructs a host AD-tape node.",
    "ad-cos": "Records/replays against the host AD tape.",
    "ad-counters": "Reads host AD-tape instrumentation counters.",
    "ad-div": "Records/replays against the host AD tape.",
    "ad-exp": "Records/replays against the host AD tape.",
    "ad-finite-difference-evals": "Reads host AD-tape instrumentation "
        "counters.",
    "ad-gradient": "Runs the reverse pass over the host AD tape.",
    "ad-gradient-of": "Runs the reverse pass over the host AD tape.",
    "ad-log": "Records/replays against the host AD tape.",
    "ad-mul": "Records/replays against the host AD tape.",
    "ad-neg": "Records/replays against the host AD tape.",
    "ad-node-value": "Reads a host AD-tape node's stored value.",
    "ad-note-finite-difference!": "Mutates host AD-tape instrumentation "
        "state.",
    "ad-pow": "Records/replays against the host AD tape.",
    "ad-primal-calls": "Reads host AD-tape instrumentation counters.",
    "ad-relu": "Records/replays against the host AD tape.",
    "ad-reset-counters!": "Mutates host AD-tape instrumentation state.",
    "ad-reverse-passes": "Reads host AD-tape instrumentation counters.",
    "ad-sigmoid": "Records/replays against the host AD tape.",
    "ad-sin": "Records/replays against the host AD tape.",
    "ad-sqrt": "Records/replays against the host AD tape.",
    "ad-sub": "Records/replays against the host AD tape.",
    "ad-tanh": "Records/replays against the host AD tape.",
    "ad-tape-allocations": "Reads host AD-tape instrumentation counters.",
    "ad-tape-length": "Reads host AD-tape state.",
    "ad-tape-new": "Constructs a host AD-tape object.",
    "ad-tape-release": "Releases a host AD-tape object; mutates host "
        "state.",
    "ad-value": "Reads a host AD-tape node's stored value.",
    "ad-value-of": "Reads a host AD-tape node's stored value.",
    "ad-var": "Constructs a host AD-tape leaf node.",
    "dual*": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual+": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-cos": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-derivative": "Reads a host dual-number's derivative component.",
    "dual-exp": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-log": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-primal": "Reads a host dual-number's primal component.",
    "dual-sin": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-sqrt": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual-tangent": "Reads a host dual-number's tangent component.",
    "dual-value": "Reads a host dual-number's value component.",
    "dual/": "Forward-mode dual-number arithmetic over the host AD "
        "representation.",
    "dual?": "Tests membership in the host dual-number representation, a "
        "dynamic-type predicate.",
    "make-dual": "Constructs a host dual-number object.",
    "derivative": "Orchestrates the host AD tape to compute a derivative.",
    "diff": "Orchestrates the host AD tape to compute a derivative.",
    "directional-derivative": "Orchestrates the host AD tape.",
    "gradient": "Orchestrates the host AD tape's reverse pass.",
    "hessian": "Orchestrates two nested passes over the host AD tape.",
    "jacobian": "Orchestrates the host AD tape's reverse pass per output "
        "component.",
    "reverse-gradient": "Orchestrates the host AD tape's reverse pass.",
    "check-grad-health": "Diagnostic introspection over the host AD tape.",
    "clip-grad-norm!": "Mutates gradient values held in host AD-tape "
        "state; violates the purity condition.",
    "zero-grad!": "Mutates host AD-tape/optimizer state; violates the "
        "purity condition.",
    "curl": "Orchestrates the host AD tape to assemble a Jacobian.",
    "laplacian": "Orchestrates the host AD tape to assemble a Hessian "
        "trace.",
    "divergence": "Orchestrates the host AD tape to assemble a Jacobian "
        "trace.",
    # Optimizer step functions mutate host-tracked parameter/state records.
    "adagrad-step": "Mutates host-tracked optimizer and parameter state; "
        "violates the purity condition.",
    "adam-step": "Mutates host-tracked optimizer and parameter state; "
        "violates the purity condition.",
    "adamw-step": "Mutates host-tracked optimizer and parameter state; "
        "violates the purity condition.",
    "rmsprop-step": "Mutates host-tracked optimizer and parameter state; "
        "violates the purity condition.",
    "sgd-step": "Mutates host-tracked optimizer and parameter state; "
        "violates the purity condition.",
    # LR schedules: host training-loop scheduling, not tensor computation.
    "cosine-annealing-lr": "Host training-loop scheduling logic over "
        "scalar host state (epoch/step counters), not a tensor "
        "computation the fragment needs to capture.",
    "exponential-decay-lr": "Host training-loop scheduling logic over "
        "scalar host state, not a tensor computation.",
    "linear-warmup-lr": "Host training-loop scheduling logic over scalar "
        "host state, not a tensor computation.",
    "step-decay-lr": "Host training-loop scheduling logic over scalar "
        "host state, not a tensor computation.",
    # Initializers mutate a tensor in place from host-managed PRNG state.
    "kaiming-normal!": "Mutates a tensor argument in place, drawing from "
        "host-managed PRNG state; violates the purity condition.",
    "kaiming-uniform!": "Mutates a tensor argument in place, drawing from "
        "host-managed PRNG state; violates the purity condition.",
    "lecun-normal!": "Mutates a tensor argument in place, drawing from "
        "host-managed PRNG state; violates the purity condition.",
    "xavier-normal!": "Mutates a tensor argument in place, drawing from "
        "host-managed PRNG state; violates the purity condition.",
    "xavier-uniform!": "Mutates a tensor argument in place, drawing from "
        "host-managed PRNG state; violates the purity condition.",
    # Dataloaders: host I/O over a dataset.
    "dataloader-has-next?": "Queries mutable host dataloader state.",
    "dataloader-length": "Queries mutable host dataloader state.",
    "dataloader-next": "Reads from a host dataset (I/O) and advances "
        "mutable host dataloader state.",
    "dataloader-reset": "Mutates host dataloader state.",
    "dataloader-reset!": "Mutates host dataloader state.",
    "make-dataloader": "Constructs a host dataloader object over a "
        "dataset (I/O).",
    "train-test-split": "Operates on a host dataset via I/O/host "
        "iteration, not a tensor computation.",
    # Model/tensor I/O.
    "model-load": "Reads from disk; excluded by the purity condition.",
    "model-save": "Writes to disk; excluded by the purity condition.",
    "onnx-export-tensor": "Writes to disk; excluded by the purity "
        "condition.",
    "tensor-load": "Reads from disk; excluded by the purity condition.",
    "tensor-save": "Writes to disk; excluded by the purity condition.",
    "tensor-disk-fill!": "Reads from disk and mutates a tensor in place; "
        "excluded by the purity condition.",
    "tensor-rect-fill!": "Mutates a tensor argument in place; excluded by "
        "the purity condition.",
    # Block quantization: no standard StableHLO representation.
    "dequant-q4_0": "GGML-style block-quantized dequantization; no "
        "standard StableHLO op or decomposition for this packed format.",
    "dequant-q8_0": "GGML-style block-quantized dequantization; no "
        "standard StableHLO op or decomposition for this packed format.",
    # Direct GPU kernel dispatch, distinct backend from XLA/StableHLO.
    "gpu-elementwise": "Dispatches directly to the CUDA/Metal accelerator "
        "backend by name; not lowered through StableHLO, which is a "
        "separate device backend from these hand-written GPU kernels.",
    "gpu-matmul": "Dispatches directly to the CUDA/Metal accelerator "
        "backend by name; not lowered through StableHLO.",
    "gpu-reduce": "Dispatches directly to the CUDA/Metal accelerator "
        "backend by name; not lowered through StableHLO.",
    "gpu-softmax": "Dispatches directly to the CUDA/Metal accelerator "
        "backend by name; not lowered through StableHLO.",
    "gpu-transpose": "Dispatches directly to the CUDA/Metal accelerator "
        "backend by name; not lowered through StableHLO.",
    # Quantum chemistry: quantum-state simulation, not tensor arithmetic.
    "hamiltonian-exact-ground-energy": "Orchestrates classical "
        "quantum-state simulation and the host AD tape, not a plain "
        "tensor computation.",
    "vqe-energy": "Orchestrates classical quantum-state simulation and "
        "the host AD tape.",
    "vqe-gradient": "Orchestrates the host AD tape over a quantum-state "
        "simulation.",
    "vqe-optimize": "Orchestrates an optimizer loop over host-tracked "
        "quantum-state simulation state; mutates host state.",
    # Dense linear algebra without a standard StableHLO decomposition.
    "tensor-det": "Dense determinant; no standard StableHLO op, and no "
        "decomposition into a bounded structured-control-flow form "
        "(LU-style elimination is not expressible as a fixed-iteration "
        "stablehlo.while over a statically unknown pivot sequence).",
    "tensor-inverse": "Dense matrix inverse; same LU-decomposition "
        "limitation as tensor-det.",
    "tensor-lu": "Dense LU decomposition; not a standard StableHLO op, "
        "and not expressible as a bounded structured-control-flow "
        "decomposition (pivoting is data-dependent).",
    "tensor-qr": "Dense QR decomposition; not a standard StableHLO op or "
        "a bounded-loop decomposition.",
    "tensor-solve": "General (non-triangular) linear solve; not a "
        "standard StableHLO op — only stablehlo.triangular_solve exists, "
        "which tensor-solve does not restrict itself to.",
    "tensor-svd": "Dense singular value decomposition; not a standard "
        "StableHLO op or a bounded-loop decomposition.",
    # Mutation and boundary transfer.
    "tensor-set!": "Mutates a tensor argument in place; excluded by the "
        "purity condition, unlike the value-returning tensor-set.",
    "tensor-shape": "Queries static shape metadata, not tensor contents; "
        "host-side bookkeeping.",
    "tensor-dtype": "Queries static dtype metadata, not tensor contents; "
        "host-side bookkeeping.",
    "tensor-length": "Queries static shape metadata, not tensor "
        "contents; host-side bookkeeping.",
    "tensor?": "Dynamic-type predicate, meaningless inside a "
        "statically-typed fragment.",
    "tensor-data": "Returns a raw host memory pointer into the tensor's "
        "storage; an escape hatch to host memory, not a computation over "
        "device values.",
    "make-tensor": "Materializes a tensor from host data; this is the "
        "host-to-device transfer boundary itself (see 'Region formation' "
        "in docs/design/ESHKOL_S_FRAGMENT.md), not a computation over an "
        "already-resident device tensor.",
    "tensor": "Materializes a tensor from a host literal; the "
        "host-to-device transfer boundary, same reasoning as make-tensor.",
    "tensor->vector": "Converts a device-domain tensor to a host-domain "
        "vector; the device-to-host transfer boundary.",
}

_TENSOR_AD_HDI = {
    "tensor-apply": "Applies an arbitrary procedure per element; the "
        "per-element procedure body may itself be a device region when "
        "it is in Eshkol-S.",
}


def build_overrides():
    overrides = {}

    for name, extra in _NUMERIC_NOT_DEVICE_REPRESENTABLE.items():
        overrides[name] = (HOST, extra)

    for name, extra in _GEOMETRY_HANDLE_LIFECYCLE.items():
        overrides[name] = (HOST, extra)

    for name, (label, rationale) in _VECTOR_OVERRIDES.items():
        overrides[name] = (label, rationale)

    for name, extra in _HIGHER_ORDER_HOST_ONLY.items():
        overrides[name] = (HOST, extra)

    for name, extra in _PREDICATE_NUMERIC_SCALAR.items():
        overrides[name] = (DEVICE, extra)

    for name, (label, rationale) in _CONTROL_FLOW_NOT.items():
        overrides[name] = (label, rationale)

    for name, (label, rationale) in _MISC_NUMERIC_DUPLICATES.items():
        overrides[name] = (label, rationale)

    for name, extra in _TENSOR_AD_HOST.items():
        overrides[name] = (HOST, extra)

    for name, extra in _TENSOR_AD_HDI.items():
        overrides[name] = (HDI, extra, _HDI_INNER_OP)

    return overrides


def classify(builtin, overrides):
    name = builtin["name"]
    category = builtin["category"]

    if name in overrides:
        entry = overrides[name]
        if len(entry) == 3:
            label, rationale, inner_op = entry
        else:
            label, rationale = entry
            inner_op = None
        return label, rationale, inner_op

    label = CATEGORY_DEFAULT.get(category)
    if label is None:
        return None, None, None

    rationale = CATEGORY_RATIONALE.get((category, label))
    if rationale is None:
        rationale = f"Category '{category}' defaults to {label}; see " \
            "docs/design/ESHKOL_S_FRAGMENT.md."

    inner_op = _HDI_INNER_OP if label == HDI else None
    return label, rationale, inner_op


def yaml_escape(text):
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def yaml_key(name):
    # Builtin names contain characters (?, !, +, <, ->, ...) that are not
    # bare YAML scalars; always double-quote keys for a parser-agnostic file.
    escaped = name.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_yaml(entries, surface_path, meta):
    lines = []
    lines.append("# lib/backend/xla/builtin_classification.yaml")
    lines.append("#")
    lines.append("# Generated by scripts/gen_builtin_classification.py — do not hand-edit.")
    lines.append("# Regenerate with:")
    lines.append("#   python3 scripts/gen_builtin_classification.py")
    lines.append("#")
    lines.append("# Every builtin the compiler registers (per")
    lines.append(f"# {os.path.relpath(surface_path, REPO)}'s builtins[] array, itself derived")
    lines.append("# from lib/backend/eshkol_compiler.c BUILTINS[], lib/backend/eshkol_vm.c")
    lines.append("# BUILTINS[], and the quantum/PQC agent-module surface — see")
    lines.append("# scripts/gen_language_surface.py) gets exactly one of the three labels")
    lines.append("# docs/design/ESHKOL_S_FRAGMENT.md defines: device, host,")
    lines.append("# host-with-device-inner. scripts/check_builtin_classification.py enforces")
    lines.append("# that this file and the registry agree exactly.")
    lines.append("version: 1")
    lines.append(f"source_registry: {os.path.relpath(surface_path, REPO)}")
    lines.append("generator: scripts/gen_builtin_classification.py")
    lines.append("labels: [device, host, host-with-device-inner]")
    lines.append(f"builtin_count: {meta['count']}")
    lines.append("counts_by_label:")
    for label in (DEVICE, HOST, HDI):
        lines.append(f"  {label}: {meta['by_label'][label]}")
    lines.append("builtins:")
    for name, label, rationale, inner_op in entries:
        lines.append(f"  {yaml_key(name)}:")
        lines.append(f"    label: {label}")
        lines.append(f"    rationale: {yaml_escape(rationale)}")
        if inner_op:
            lines.append(f"    inner_op: {yaml_escape(inner_op)}")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--surface", default=DEFAULT_SURFACE)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    with open(args.surface, encoding="utf-8") as fh:
        surface = json.load(fh)

    builtins = surface["builtins"]
    overrides = build_overrides()

    entries = []
    unclassifiable = []
    by_label = {DEVICE: 0, HOST: 0, HDI: 0}
    seen = set()
    for b in sorted(builtins, key=lambda x: x["name"]):
        name = b["name"]
        if name in seen:
            continue
        seen.add(name)
        label, rationale, inner_op = classify(b, overrides)
        if label is None:
            unclassifiable.append((name, b["category"]))
            continue
        by_label[label] += 1
        entries.append((name, label, rationale, inner_op))

    if unclassifiable:
        sys.stderr.write(
            "gen_builtin_classification.py: no category default for "
            f"{len(unclassifiable)} builtin(s):\n"
        )
        for name, category in unclassifiable:
            sys.stderr.write(f"  {name!r} (category={category!r})\n")
        return 1

    # Every declared override must have matched a real builtin, or the
    # override table has drifted from the registry (a rename, a removal).
    all_names = {b["name"] for b in builtins}
    stale_overrides = sorted(set(overrides) - all_names)
    if stale_overrides:
        sys.stderr.write(
            "gen_builtin_classification.py: overrides reference builtins "
            f"not present in {args.surface}:\n"
        )
        for name in stale_overrides:
            sys.stderr.write(f"  {name!r}\n")
        return 1

    meta = {"count": len(entries), "by_label": by_label}
    out_text = render_yaml(entries, args.surface, meta)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(out_text)

    print(f"Wrote {args.out}")
    print(f"  {meta['count']} builtins classified: "
          f"device={by_label[DEVICE]} host={by_label[HOST]} "
          f"host-with-device-inner={by_label[HDI]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
