#!/usr/bin/env python3
"""gen_metaprog_depth.py — depth-parametric METAPROGRAMMING + MODULE test
generator (adversarial depth-parametric pillar P6e).

For every composable metaprogramming construct we do NOT test one or two fixed
shapes — we generate the construct PARAMETRICALLY at depth d = 1,2,3,...,N and
attach a closed-form ground-truth value that scales with depth. A silent wrong
value or a crash at any depth is a bug; a clean compile/limit error is a
documented capability boundary. scripts/run_metaprog_depth.sh consumes the
emitted files + manifest and diffs the printed "RESULT: <v>" against expected on
both the JIT (-r) and AOT axes.

Families
  recmac_and    recursive syntax-rules macro (my-and) expanding n-deep      -> n
  recmac_list   recursive syntax-rules macro (my-list) building n cons cells -> n
  nested_macro  macro invocation nested n-deep ((inc (inc ... 0)))          -> n
  ellipsis_flat single-ellipsis template summing n elements                 -> n
  nested_ellip  nested-ellipsis template ((row ...) ...) summing n*n ones    -> n*n
  match_nest    match with n-deep nested (list ...) pattern, innermost bind  -> n
  qq_macro      macro emitting quasiquote/unquote, nested n-deep             -> n
  module_chain  n modules each (require)-ing + calling the next, transitive  -> n
  deflib_chain  n define-library modules with (import) chain, transitive     -> n

Usage:
  python3 scripts/gen_metaprog_depth.py [--out-dir DIR] [--max-depth N]
      [--module-max-depth M] [--depths a,b,c]

Manifest (one JSON object per line) drives the runner:
  {"family","depth","main","expected","modes":["r","aot"],"note"}
"""
import argparse
import json
import os

HDR = ";; GENERATED by scripts/gen_metaprog_depth.py -- DO NOT EDIT\n"


def w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


# --------------------------------------------------------------------------
# single-file families: return (source_text, expected)
# --------------------------------------------------------------------------

def gen_recmac_and(d):
    args = " ".join(str(i) for i in range(1, d + 1))  # 1..d, all truthy
    src = HDR + (
        "(define-syntax my-and\n"
        "  (syntax-rules ()\n"
        "    ((_) #t)\n"
        "    ((_ e) e)\n"
        "    ((_ e r ...) (if e (my-and r ...) #f))))\n"
        '(display "RESULT: ")(display (my-and ' + args + "))(newline)\n"
    )
    return src, d  # last truthy value == d


def gen_recmac_list(d):
    args = " ".join(str(i) for i in range(1, d + 1))
    # NB: base template uses (quote ()) long-form; the shorthand '() as a
    # top-level rule template is rejected by the parser (see ESH finding).
    src = HDR + (
        "(require stdlib)\n"
        "(define-syntax my-list\n"
        "  (syntax-rules ()\n"
        "    ((_) (quote ()))\n"
        "    ((_ x r ...) (cons x (my-list r ...)))))\n"
        '(display "RESULT: ")(display (length (my-list ' + args + ")))(newline)\n"
    )
    return src, d


def gen_nested_macro(d):
    body = "0"
    for _ in range(d):
        body = "(inc " + body + ")"
    src = HDR + (
        "(define-syntax inc (syntax-rules () ((_ x) (+ x 1))))\n"
        '(display "RESULT: ")(display ' + body + ")(newline)\n"
    )
    return src, d


def gen_ellipsis_flat(d):
    ones = " ".join("1" for _ in range(d))
    src = HDR + (
        "(define-syntax vsum (syntax-rules () ((_ x ...) (+ 0 x ...))))\n"
        '(display "RESULT: ")(display (vsum ' + ones + "))(newline)\n"
    )
    return src, d


def gen_nested_ellip(d):
    # d rows, each row has d ones -> nested ellipsis flattens to d*d ones.
    rows = " ".join("(" + " ".join("1" for _ in range(d)) + ")" for _ in range(d))
    src = HDR + (
        "(define-syntax mat\n"
        "  (syntax-rules ()\n"
        "    ((_ (row ...) ...) (+ 0 row ... ...))))\n"
        '(display "RESULT: ")(display (mat ' + rows + "))(newline)\n"
    )
    return src, d * d


def _match_data_inner(k, d):
    if k == d:
        return "(list %d)" % d
    return "(list %d %s)" % (k, _match_data_inner(k + 1, d))


def _match_data(d):
    if d == 1:
        return "(list %d)" % d
    return _match_data_inner(1, d)


def _match_pat_inner(k, d):
    if k == d:
        return "(list v%d)" % d
    return "(list v%d %s)" % (k, _match_pat_inner(k + 1, d))


def _match_pat(d):
    if d == 1:
        return "(list v1)"
    return _match_pat_inner(1, d)


def gen_match_nest(d):
    src = HDR + (
        "(require stdlib)\n"
        '(display "RESULT: ")\n'
        "(display (match " + _match_data(d) + "\n"
        "  (" + _match_pat(d) + " v%d)\n" % d
        + "  (_ -1)))\n(newline)\n"
    )
    return src, d


def gen_qq_macro(d):
    # macro emits quasiquote/unquote; nesting n-deep threads +1 through
    # a `(,(+ x 1)) template and cars it back out.
    body = "0"
    for _ in range(d):
        body = "(add1q " + body + ")"
    src = HDR + (
        "(define-syntax add1q (syntax-rules () ((_ x) (car `(,(+ x 1))))))\n"
        '(display "RESULT: ")(display ' + body + ")(newline)\n"
    )
    return src, d


SINGLE = {
    "recmac_and": gen_recmac_and,
    "recmac_list": gen_recmac_list,
    "nested_macro": gen_nested_macro,
    "ellipsis_flat": gen_ellipsis_flat,
    "nested_ellip": gen_nested_ellip,
    "match_nest": gen_match_nest,
    "qq_macro": gen_qq_macro,
}


# --------------------------------------------------------------------------
# module-chain families: emit a directory of modules + main.esk
# --------------------------------------------------------------------------

def gen_module_chain(out_dir, d):
    """n modules mod0..mod{d-1}; f_k adds 1 and calls f_{k+1}; f0(0)==d."""
    base = os.path.join(out_dir, "module_chain", "d%03d" % d)
    for k in range(d):
        if k == d - 1:
            body = "(define (f%d x) (+ x 1))" % k
            req = ""
        else:
            body = "(define (f%d x) (f%d (+ x 1)))" % (k, k + 1)
            req = "(require mod%d)\n" % (k + 1)
        w(os.path.join(base, "mod%d.esk" % k),
          HDR + req + "(provide f%d)\n" % k + body + "\n")
    main = os.path.join(base, "main.esk")
    w(main, HDR + "(require mod0)\n"
      '(display "RESULT: ")(display (f0 0))(newline)\n')
    return main, d


def gen_deflib_chain(out_dir, d):
    """n define-library modules; lib_k exports g_k that calls g_{k+1}."""
    base = os.path.join(out_dir, "deflib_chain", "d%03d" % d)
    for k in range(d):
        if k == d - 1:
            imp = ""
            body = "    (define (g%d x) (+ x 1))" % k
        else:
            imp = "  (import (lib%d))\n" % (k + 1)
            body = "    (define (g%d x) (g%d (+ x 1)))" % (k, k + 1)
        src = (HDR
               + "(define-library (lib%d)\n" % k
               + imp
               + "  (export g%d)\n" % k
               + "  (begin\n" + body + "))\n")
        w(os.path.join(base, "lib%d.esk" % k), src)
    main = os.path.join(base, "main.esk")
    w(main, HDR + "(import (lib0))\n"
      '(display "RESULT: ")(display (g0 0))(newline)\n')
    return main, d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default="tests/metaprog_depth/generated")
    ap.add_argument("--max-depth", type=int, default=48)
    ap.add_argument("--module-max-depth", type=int, default=24)
    ap.add_argument("--depths", default="",
                    help="explicit comma-separated depths (overrides --max-depth)")
    args = ap.parse_args()

    if args.depths:
        depths = [int(x) for x in args.depths.split(",") if x.strip()]
    else:
        depths = list(range(1, args.max_depth + 1))
    mod_depths = [d for d in depths if d <= args.module_max_depth]

    out = args.out_dir
    manifest = []

    for fam, fn in SINGLE.items():
        for d in depths:
            src, expected = fn(d)
            rel = os.path.join(fam, "d%03d.esk" % d)
            w(os.path.join(out, rel), src)
            manifest.append({
                "family": fam, "depth": d, "main": rel,
                "expected": expected, "modes": ["r", "aot"], "note": "",
            })

    for d in mod_depths:
        main_path, expected = gen_module_chain(out, d)
        manifest.append({
            "family": "module_chain", "depth": d,
            "main": os.path.relpath(main_path, out),
            "expected": expected, "modes": ["r", "aot"], "note": "",
        })
    for d in mod_depths:
        main_path, expected = gen_deflib_chain(out, d)
        manifest.append({
            "family": "deflib_chain", "depth": d,
            "main": os.path.relpath(main_path, out),
            "expected": expected, "modes": ["r", "aot"], "note": "",
        })

    mpath = os.path.join(out, "manifest.jsonl")
    with open(mpath, "w") as f:
        for m in manifest:
            f.write(json.dumps(m) + "\n")
    print("wrote %d test entries -> %s" % (len(manifest), mpath))
    fams = sorted(set(m["family"] for m in manifest))
    print("families: " + ", ".join(fams))
    print("depths: %s%s" % (depths[:8], " ..." if len(depths) > 8 else ""))


if __name__ == "__main__":
    main()
