#!/usr/bin/env python3
"""Offline checks of the independent public-tensor ESKM byte oracle."""

from pathlib import Path
import math
import struct
import tempfile
import unittest

from run_eskm_tensor_engine_parity import Failure, ROOT, expected_bytes, verify_bytes


class TensorOracleTest(unittest.TestCase):
    def test_historical_single_record_fixtures(self):
        # Immutable v1.2.4 writer outputs, not regenerated by this oracle.
        cases = {
            "scalar.eskm": ((), (42.5,)),
            "empty-0x3.eskm": ((0, 3), ()),
            "rank8.eskm": ((1,) * 8, (math.pi,)),
            "ordinary-2x3.eskm": ((2, 3), (
                1.0, -2.5, 0.0, -0.0, math.inf,
                struct.unpack("<d", bytes.fromhex("420000000000f87f"))[0])),
        }
        for name, (shape, values) in cases.items():
            with self.subTest(fixture=name):
                self.assertEqual(expected_bytes(shape, values),
                                 (ROOT / "tests/core/fixtures/eskm-v1" / name).read_bytes())

    def test_explicit_wire_fields(self):
        data = expected_bytes((2,), (0.0, -0.0))
        self.assertEqual(data[:16], bytes.fromhex("45534b4d010000000100000000000000"))
        self.assertEqual(data[16:33], bytes.fromhex("0000000001000000020000000000000000"))
        self.assertEqual(data[33:-4], bytes.fromhex("00000000000000000000000000000080"))

    def test_wrong_expectations_are_refused_without_changing_file(self):
        data = expected_bytes((2,), (0.0, -0.0))
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "valid.eskm"
            path.write_bytes(data)
            verify_bytes(path, data)
            for offset in (0, 4, 8, 12, 16, 20, 24, 32, 33, 48, 49):
                with self.subTest(offset=offset):
                    wrong = data[:offset] + bytes([data[offset] ^ 1]) + data[offset + 1:]
                    with self.assertRaises(Failure):
                        verify_bytes(path, wrong)
            self.assertEqual(path.read_bytes(), data)


if __name__ == "__main__":
    unittest.main()
