/**
 * @file region_formation.h
 * @brief Region formation: outlining the maximal device-eligible subgraphs of
 *        an Eshkol program, and reporting every graph break by name.
 *
 * WHAT THIS IS FOR. Eshkol-S (docs/design/ESHKOL_S_FRAGMENT.md) names the
 * subset of Eshkol that maps onto StableHLO honestly. Stages S2-S4 lowered and
 * measured the operations in that subset one at a time. Nothing yet decided
 * which PARTS OF A WHOLE PROGRAM belong to it, and a program is not written
 * entirely in the fragment; it is tensor arithmetic with printing, list
 * building, mutation and differentiation around it.
 *
 * This pass walks the AST, marks each node eligible or not against the
 * contract, and outlines each MAXIMAL eligible connected subgraph as one
 * region. The host calls the region at the boundary and continues. A program
 * that produces one region runs on the device; a program that produces none
 * runs exactly as it does today. Both are correct.
 *
 * THE GRAPH BREAK IS THE UNIT OF FAILURE AND IS REPORTED, NEVER HIDDEN. This
 * is the whole design, not a diagnostic nicety. A pass that quietly declined
 * to form a region would be indistinguishable, from the outside, from a pass
 * that formed one and got the numbers wrong: both look like a program that
 * ran. So every node that is not eligible produces a GraphBreak naming the
 * construct, the reason from the contract, and the builtin's label when a
 * builtin was the cause — and a break does not stop the walk, because a host
 * builtin's arguments can still contain regions of their own.
 *
 * WHAT DECIDES ELIGIBILITY. Not this file's opinion. Three data sources, all
 * compiled in through lib/backend/xla/region_tables.inc, generated by
 * scripts/gen_region_tables.py:
 *
 *   - lib/backend/xla/builtin_classification.yaml gives every builtin one of
 *     device / host / host-with-device-inner.
 *   - lib/backend/xla/device_lowering_table.yaml says which device-labelled
 *     builtins actually have a StableHLO lowering, as a composition
 *     (`builtins:`) or as a single op device_lowering.cpp owns (`core_ops:`).
 *   - The special forms admitted by contract condition 3 are listed in
 *     region_formation.cpp beside the reason text for each form that is not.
 *
 * A builtin labelled `device` with no lowering is a BREAK, not a region node:
 * the label is a claim that the builtin CAN be represented in the fragment,
 * which is not the claim that today's emitter can emit it. Confusing those two
 * is how a pass comes to outline a region nobody can compile.
 *
 * Copyright (C) tsotchke
 * SPDX-License-Identifier: MIT
 */

#ifndef ESHKOL_BACKEND_XLA_REGION_FORMATION_H
#define ESHKOL_BACKEND_XLA_REGION_FORMATION_H

#include <cstdint>
#include <iosfwd>
#include <string>
#include <vector>

#include "eshkol/eshkol.h"

namespace eshkol {
namespace xla {

/** @brief The Eshkol-S label a builtin carries, per the classification table. */
enum class BuiltinLabel {
    Device,                 ///< Has, or can have, a StableHLO lowering
    Host,                   ///< Host-only by nature
    HostWithDeviceInner,    ///< Host, but its argument evaluation can be a region
    Unclassified            ///< Not in the table at all. A gap, reported as one.
};

/** @brief Why a node is not device-eligible. Serialized as the strings in
 *         breakReasonName(); those strings are the report's contract with the
 *         expected-regions files, so they do not change casually. */
enum class BreakReason {
    HostBuiltin,            ///< Builtin labelled host
    HostWithDeviceInner,    ///< Builtin labelled host-with-device-inner
    UnclassifiedBuiltin,    ///< Builtin absent from the classification table
    NoLowering,             ///< Labelled device, but no lowering exists for it
    NonAdmittedConstruct,   ///< A special form condition 3 does not admit
    HostValueDomain,        ///< A string/char/symbol/list value (condition 1)
    UnknownShape,           ///< A shape that is not static and not bounded (condition 2)
    RecursiveCall,          ///< A call into a function that (transitively) calls itself
    HostFunction,           ///< A call into a top-level function whose own body breaks
    UnknownFunction         ///< A call to a name that is neither builtin nor defined here
};

/** @brief The report's name for a break reason. */
const char* breakReasonName(BreakReason reason);

/** @brief One reported graph break. */
struct GraphBreak {
    uint32_t line = 0;
    uint32_t column = 0;
    /** The construct that caused it: a special-form keyword ("set!"), or the
     *  builtin's name ("display"). Never a rendering of the whole subtree —
     *  a break is identified by what it IS, so that an expected-regions file
     *  can state it without transcribing source. */
    std::string construct;
    BreakReason reason = BreakReason::NonAdmittedConstruct;
    /** The sentence from the contract that excludes it. */
    std::string reason_text;
    /** The builtin's name when a builtin caused the break, else empty. */
    std::string builtin;
    /** The builtin's label when a builtin caused the break, else empty. */
    std::string label;
    /** The node the break is AT. Not owned, not serialized. The walk uses it
     *  to tell a break of its own from a break its subtree reported: line and
     *  column cannot, because a whole expression is routinely on one line. */
    const eshkol_ast_t* node = nullptr;
};

/** @brief A shape known statically, or explicitly not known.
 *
 *  `known == false` is not an error: the contract admits a region whose shape
 *  is only settled at run time, keyed by the shape signature at first
 *  execution through the executable cache. It IS reported, because a region
 *  that recompiles per shape has a cost the reader should be able to see.
 */
struct RegionShape {
    bool known = false;
    std::vector<int64_t> dims;   ///< Empty with known == true means a scalar.
    std::string text() const;    ///< "[2,3]", "[]" for a scalar, "?" when unknown.
};

/** @brief One value a region takes from the host. */
struct RegionInput {
    std::string name;            ///< The variable it is bound to, or "" for an expression
    RegionShape shape;
};

/** @brief One outlined maximal device region. */
struct Region {
    int id = 0;
    uint32_t line = 0;
    uint32_t column = 0;
    /** The device operations in the region, in evaluation order, named by the
     *  Eshkol builtin or operator that produced each. */
    std::vector<std::string> ops;
    std::vector<RegionInput> inputs;
    RegionShape result;
    /** True when this region sits inside a `gradient`/`derivative`/`jacobian`/
     *  `hessian` operand, so it must be emitted forward-and-VJP in one module
     *  rather than executed forward-only and silently leaving the tape. */
    bool inside_gradient = false;
    /** The executable-cache key: the region's identity plus the shapes it was
     *  entered with. One region compiles once per distinct shape signature. */
    std::string shape_signature;
    /** The subtree this region replaces. Not owned. */
    const eshkol_ast_t* root = nullptr;
};

/** @brief Everything the pass found in one top-level form. */
struct UnitReport {
    std::string unit;                  ///< The defined name, or "<toplevel>"
    std::vector<Region> regions;
    std::vector<GraphBreak> breaks;
};

/** @brief Everything the pass found in a module. */
struct ModuleReport {
    std::string program;               ///< Source path, for the report
    std::vector<UnitReport> units;
    int total_regions = 0;
    int total_device_ops = 0;
    int total_breaks = 0;
};

/** @brief How the pass was asked to report. */
struct RegionFormationOptions {
    /** ESHKOL_XLA_TRACE_REGIONS=1: human-readable report on stderr. */
    bool trace = false;
    /** ESHKOL_XLA_REGION_REPORT=<file>: machine-readable JSON to that path. */
    std::string report_path;
    /** ESHKOL_XLA_REGIONS=1: form regions over a whole module rather than one
     *  top-level definition. Analysis runs either way; this is what a caller
     *  inside the compiler consults before acting on the result. */
    bool enabled = false;
};

/** @brief Read the three environment variables above. */
RegionFormationOptions regionOptionsFromEnvironment();

/**
 * @brief The pass.
 *
 * Usage is two-phase because eligibility is interprocedural: a call to a
 * top-level function whose whole body is in the fragment is itself in the
 * fragment, and that cannot be decided until the function has been seen. So
 * every top-level form is declared first, then analysed.
 */
class RegionFormation {
public:
    explicit RegionFormation(RegionFormationOptions options = {});
    ~RegionFormation();

    RegionFormation(const RegionFormation&) = delete;
    RegionFormation& operator=(const RegionFormation&) = delete;

    /** @brief Name the program, for the report. */
    void setProgram(const std::string& path);

    /**
     * @brief Phase one: register a top-level form so that calls to it can be
     *        resolved. Registering is not analysis and forms no regions.
     */
    void declare(const eshkol_ast_t* form);

    /** @brief Phase two: analyse one registered form, forming its regions. */
    void analyze(const eshkol_ast_t* form);

    /** @brief The accumulated report. */
    const ModuleReport& report() const;

    /** @brief The report as JSON, the shape the expected-regions files use. */
    std::string toJson() const;

    /** @brief The human-readable report ESHKOL_XLA_TRACE_REGIONS asks for. */
    void writeTrace(std::ostream& out) const;

    /** @brief Write the JSON report to options.report_path, if one was given.
     *  @return false if a path was given and could not be written. */
    bool writeReportFile(std::string* error) const;

private:
    class Impl;
    Impl* impl_;
};

} // namespace xla
} // namespace eshkol

#endif // ESHKOL_BACKEND_XLA_REGION_FORMATION_H
