#!/usr/bin/env bash
# export_weights.sh — regenerate the QLMW v3 weight matrices from the ISA specification.
#
# The construction is deterministic: same ISA in, bit-identical weights out on any
# IEEE 754 float32 platform. No training, no random seeds.
#
# Usage:
#   bash scripts/paper/export_weights.sh [output_file]
#
# Output: QLMW v3 binary (10.6 MB) at $1 (default: artifacts/paper/outputs/weights.qlmw)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

OUTPUT="${1:-artifacts/paper/outputs/weights.qlmw}"
mkdir -p "$(dirname "$OUTPUT")"

# TODO (SDNC paper artifact): link this to the actual weight-generation entry
# point in lib/backend/weight_compiler.c. For the v1.1.13 release, the
# weight generation runs as part of the standalone VM compile path and
# produces the QLMW v3 binary alongside the interpreter binary.
#
# Current status: the one-shot compile-and-export path exists but the
# standalone entry point that writes the weights to an explicit file needs
# to be wired. Placeholder below runs the full build and copies the
# generated weights.

BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/build-paper}"
if [[ ! -d "$BUILD_DIR" ]]; then
    echo "  building Eshkol (paper config)..."
    cmake -S . -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release > /dev/null
    cmake --build "$BUILD_DIR" --target eshkol-run > /dev/null
fi

# Run the weight export entry (adapt target name once wired)
if [[ -x "$BUILD_DIR/tools/export-weights" ]]; then
    "$BUILD_DIR/tools/export-weights" --output "$OUTPUT"
elif [[ -f "$BUILD_DIR/weights.qlmw" ]]; then
    cp "$BUILD_DIR/weights.qlmw" "$OUTPUT"
else
    echo "  NOTE: weight export entry point not yet wired (TODO)."
    echo "  Producing placeholder marker at $OUTPUT"
    {
        echo "# QLMW v3 placeholder"
        echo "# Generated by scripts/paper/export_weights.sh"
        echo "# TODO: wire to lib/backend/weight_compiler.c export path"
        date
    } > "$OUTPUT"
fi

echo "  weights at: $OUTPUT ($(wc -c < "$OUTPUT") bytes)"
shasum -a 256 "$OUTPUT"
