#!/usr/bin/env python3
"""
gen_paper_tables.py — regenerate the LaTeX tables used in the SDNC paper
from the reproducibility outputs.

Generates:
  - tab_params.tex          — parameter count per layer
  - tab_verification.tex    — three-way verification summary
  - tab_opcode_coverage.tex — weight-implemented vs native-delegated
  - tab_runtime.tex         — forward/backward runtime per opcode class

Part of the artifact package for:
  "The Self-Differentiating Neural Computer: Computable Transformers
   via Analytical Weight Construction" (tsotchke, 2026)
"""
from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path


LATEX_PREAMBLE = "% Auto-generated by scripts/paper/gen_paper_tables.py\n"


def read_qlmw_header(weights_path: Path) -> tuple[int, int, int, int, int, int, int]:
    with weights_path.open("rb") as f:
        header = f.read(28)
    if len(header) != 28:
        raise ValueError(f"{weights_path} is too short to be a QLMW file")
    magic, version, d_model, n_layers, ffn_dim, n_heads, head_dim = struct.unpack("<7I", header)
    if magic != 0x514C4D57:
        raise ValueError(f"{weights_path} has invalid QLMW magic 0x{magic:08x}")
    return magic, version, d_model, n_layers, ffn_dim, n_heads, head_dim


def write_params_table(weights_path: Path, out_path: Path) -> None:
    """Parameter count summary from the QLMW header and file size."""
    if not weights_path.exists():
        content = LATEX_PREAMBLE + "% TODO: weights file not present\n"
        out_path.write_text(content)
        return

    _, version, d_model, n_layers, ffn_dim, n_heads, head_dim = read_qlmw_header(weights_path)
    total_params = (weights_path.stat().st_size - 28) // 4
    attn_per_layer = 4 * d_model * d_model + d_model
    ffn_per_layer = 3 * d_model * ffn_dim + 2 * ffn_dim + d_model
    attn_total = n_layers * attn_per_layer
    ffn_total = n_layers * ffn_per_layer
    metadata = total_params - attn_total - ffn_total

    content = LATEX_PREAMBLE + rf"""\begin{{tabular}}{{lrr}}
\toprule
Component & Dimensions & Parameters \\
\midrule
QLMW header       & v{version}, h={n_heads}, d\_h={head_dim} & -- \\
Attention blocks  & {n_layers} x (4 x {d_model} x {d_model} + {d_model}) & {attn_total:,} \\
FFN blocks        & {n_layers} x (3 x {d_model} x {ffn_dim} + 2 x {ffn_dim} + {d_model}) & {ffn_total:,} \\
Metadata          & ff\_type[{n_layers}] & {metadata:,} \\
\midrule
Total             & d={d_model}, L={n_layers}, FFN={ffn_dim} & {total_params:,} \\
\bottomrule
\end{{tabular}}
"""
    out_path.write_text(content)
    print(f"  wrote {out_path}")


def write_verification_table(comparison_path: Path, out_path: Path) -> None:
    """Three-way verification summary, paper §4.4."""
    if not comparison_path.exists():
        content = LATEX_PREAMBLE + "% TODO: comparison report not present\n"
        out_path.write_text(content)
        return
    report = json.loads(comparison_path.read_text())
    if report.get("status") == "todo":
        content = LATEX_PREAMBLE + "% TODO: upstream traces not yet wired\n"
        out_path.write_text(content)
        return
    total = report["total_programs"]
    output_agreeing = report.get("output_agreeing_programs", 0)
    fully_agreeing = report.get("fully_agreeing_programs", 0)
    content = LATEX_PREAMBLE + rf"""\begin{{tabular}}{{lrr}}
\toprule
Agreement scope & Programs & Fraction \\
\midrule
PRINT-output agreement (paper claim) & {output_agreeing}     & {output_agreeing}/{total} \\
Full-state per-step agreement        & {fully_agreeing}      & {fully_agreeing}/{total} \\
\bottomrule
\end{{tabular}}
"""
    out_path.write_text(content)
    print(f"  wrote {out_path} (output={output_agreeing}/{total}, fullstate={fully_agreeing}/{total})")


def write_coverage_table(coverage_path: Path, out_path: Path) -> None:
    """Opcode coverage breakdown."""
    if not coverage_path.exists():
        content = LATEX_PREAMBLE + "% TODO: coverage report not present\n"
        out_path.write_text(content)
        return
    report = json.loads(coverage_path.read_text())
    if report.get("status") == "todo":
        content = LATEX_PREAMBLE + "% TODO: upstream coverage not yet wired\n"
        out_path.write_text(content)
        return
    wi_count = len(report.get("weight_implemented", {}))
    nd_count = len(report.get("native_delegated", {}))
    total = wi_count + nd_count
    content = LATEX_PREAMBLE + rf"""\begin{{tabular}}{{lrr}}
\toprule
Opcode class & Count & Fraction of ISA \\
\midrule
Weight-implemented (matmul+bias) & {wi_count} & {wi_count}/{total} \\
Native-delegated (IS\_NATIVE)     & {nd_count} & {nd_count}/{total} \\
\midrule
Total ISA                         & {total}    & 1.00 \\
\bottomrule
\end{{tabular}}
"""
    out_path.write_text(content)
    print(f"  wrote {out_path} ({wi_count} wi, {nd_count} nd)")


def write_runtime_table(out_path: Path) -> None:
    """Placeholder for runtime table. Populated by a separate benchmark
    run not yet wired into this script."""
    content = LATEX_PREAMBLE + "% TODO: runtime benchmark not yet wired\n"
    out_path.write_text(content)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--comparison", required=True, type=Path)
    p.add_argument("--coverage", required=True, type=Path)
    p.add_argument("--weights", required=True, type=Path)
    p.add_argument("--out-dir", required=True, type=Path)
    args = p.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    write_params_table(args.weights, args.out_dir / "tab_params.tex")
    write_verification_table(args.comparison, args.out_dir / "tab_verification.tex")
    write_coverage_table(args.coverage, args.out_dir / "tab_opcode_coverage.tex")
    write_runtime_table(args.out_dir / "tab_runtime.tex")

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
