#!/usr/bin/env python3
"""
gen_paper_tables.py — regenerate the LaTeX tables used in the SDNC paper
from the reproducibility outputs.

Generates:
  - tab_params.tex          — parameter count per layer
  - tab_verification.tex    — three-way verification summary (74 programs)
  - tab_opcode_coverage.tex — weight-implemented vs native-delegated
  - tab_runtime.tex         — forward/backward runtime per opcode class

Part of the artifact package for:
  "The Self-Differentiating Neural Computer: Computable Transformers
   via Analytical Weight Construction" (tsotchke, 2026)
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


LATEX_PREAMBLE = "% Auto-generated by scripts/paper/gen_paper_tables.py\n"


def write_params_table(weights_path: Path, out_path: Path) -> None:
    """Parameter count per layer. For v1.1.13, this is static structural info
    read from the weight file header (QLMW v3 stores dimensions per layer)."""
    # TODO: parse QLMW v3 header. For now emit a placeholder that matches
    # the paper's current tab:params content.
    content = LATEX_PREAMBLE + r"""\begin{tabular}{lrr}
\toprule
Layer & Dimensions & Parameters \\
\midrule
0 (Gaussian attn) & 128x128 x 4 & 65{,}792 \\
1 (Square FFN)    & 1024x128 x 2 & 263{,}424 \\
2 (Gated FFN)     & 1024x128 x 2 & 263{,}424 \\
3 (Exec FFN)      & 1024x128 x 2 & 263{,}424 \\
4 (Frame FFN)     & 1024x128 x 2 & 263{,}424 \\
5 (AD tape FFN)   & 1024x128 x 2 & 263{,}424 \\
Embeddings + pos  & --            & 1{,}383{,}430 \\
\midrule
Total             & --            & 2{,}766{,}342 \\
\bottomrule
\end{tabular}
"""
    out_path.write_text(content)
    print(f"  wrote {out_path}")


def write_verification_table(comparison_path: Path, out_path: Path) -> None:
    """Three-way verification summary."""
    if not comparison_path.exists():
        content = LATEX_PREAMBLE + "% TODO: comparison report not present\n"
        out_path.write_text(content)
        return
    report = json.loads(comparison_path.read_text())
    if report.get("status") == "todo":
        content = LATEX_PREAMBLE + "% TODO: upstream traces not yet wired\n"
        out_path.write_text(content)
        return
    total = report["total_programs"]
    agreeing = report["fully_agreeing_programs"]
    content = LATEX_PREAMBLE + rf"""\begin{{tabular}}{{lrr}}
\toprule
Result & Programs & Fraction \\
\midrule
Fully agreeing (bitwise)     & {agreeing}     & {agreeing}/{total} \\
Any disagreement             & {total - agreeing} & {total - agreeing}/{total} \\
\bottomrule
\end{{tabular}}
"""
    out_path.write_text(content)
    print(f"  wrote {out_path} ({agreeing}/{total} agreeing)")


def write_coverage_table(coverage_path: Path, out_path: Path) -> None:
    """Opcode coverage breakdown."""
    if not coverage_path.exists():
        content = LATEX_PREAMBLE + "% TODO: coverage report not present\n"
        out_path.write_text(content)
        return
    report = json.loads(coverage_path.read_text())
    if report.get("status") == "todo":
        content = LATEX_PREAMBLE + "% TODO: upstream coverage not yet wired\n"
        out_path.write_text(content)
        return
    wi_count = len(report.get("weight_implemented", {}))
    nd_count = len(report.get("native_delegated", {}))
    total = wi_count + nd_count
    content = LATEX_PREAMBLE + rf"""\begin{{tabular}}{{lrr}}
\toprule
Opcode class & Count & Fraction of ISA \\
\midrule
Weight-implemented (matmul+bias) & {wi_count} & {wi_count}/{total} \\
Native-delegated (IS\_NATIVE)     & {nd_count} & {nd_count}/{total} \\
\midrule
Total ISA                         & {total}    & 1.00 \\
\bottomrule
\end{{tabular}}
"""
    out_path.write_text(content)
    print(f"  wrote {out_path} ({wi_count} wi, {nd_count} nd)")


def write_runtime_table(out_path: Path) -> None:
    """Placeholder for runtime table. Populated by a separate benchmark
    run not yet wired into this script."""
    content = LATEX_PREAMBLE + "% TODO: runtime benchmark not yet wired\n"
    out_path.write_text(content)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--comparison", required=True, type=Path)
    p.add_argument("--coverage", required=True, type=Path)
    p.add_argument("--weights", required=True, type=Path)
    p.add_argument("--out-dir", required=True, type=Path)
    args = p.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    write_params_table(args.weights, args.out_dir / "tab_params.tex")
    write_verification_table(args.comparison, args.out_dir / "tab_verification.tex")
    write_coverage_table(args.coverage, args.out_dir / "tab_opcode_coverage.tex")
    write_runtime_table(args.out_dir / "tab_runtime.tex")

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
