# Generate a Windows module-definition (.def) file that exports exactly the
# Eshkol runtime symbols the in-process JIT needs to resolve at runtime.
#
# WHY THIS EXISTS
# ---------------
# On macOS/Linux the REPL/`-r` JIT resolves host runtime symbols
# (eshkol_*, arena_*, the compiler-rt stack-probe builtin ___chkstk_ms, …)
# through DynamicLibrarySearchGenerator::GetForCurrentProcess, which works
# because those executables are linked with -export_dynamic / --export-dynamic
# and therefore publish every global symbol.
#
# On Windows (PE/COFF) symbols are NOT exported by default, so the generator
# finds nothing and `-r` dies with:
#     JIT session error: Symbols not found:
#       [ ___chkstk_ms, eshkol_repl_capture_last_value, eshkol_closure_get_arity, … ]
#
# The PE export table is hard-capped at 65535 ordinals, so the GNU driver's
# --export-all-symbols is unusable here: the exe statically links all of LLVM
# (~70k symbols) and the linker aborts with "export ordinal too large".
#
# The architectural fix is to export ONLY the Eshkol runtime namespace — a
# bounded set (~900 symbols) discovered directly from the runtime archives, so
# it never drifts as runtime functions are added/removed. The resulting .def is
# fed to the linker, populating the PE export table with exactly those names.
#
# Invoked as:
#   cmake -DARCHIVES=a.a;b.a;c.a -DNM=<nm> -DOUTPUT=<file.def>
#         -P cmake/gen_runtime_def.cmake

if(NOT DEFINED ARCHIVES OR NOT DEFINED NM OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "gen_runtime_def.cmake requires -DARCHIVES, -DNM, -DOUTPUT")
endif()

set(_exports "")

foreach(_archive IN LISTS ARCHIVES)
    if(NOT EXISTS "${_archive}")
        continue()
    endif()
    execute_process(
        COMMAND "${NM}" --defined-only "${_archive}"
        OUTPUT_VARIABLE _nm_out
        ERROR_QUIET
    )
    # nm lines look like:  0000000140298a90 T eshkol_stderr_stream
    # Only GLOBAL/external symbols (uppercase type letter) can be exported via a
    # .def — lowercase types (t/d/b/r) are file-local statics and the linker
    # rejects "cannot export <sym>: symbol not defined" for them.
    string(REGEX MATCHALL "[ \t][TDBR][ \t][^\r\n]+" _lines "${_nm_out}")
    foreach(_line IN LISTS _lines)
        # Strip the leading " <type> " to recover the bare symbol name.
        string(REGEX REPLACE "^[ \t][TDBR][ \t]+" "" _sym "${_line}")
        string(STRIP "${_sym}" _sym)
        if(_sym MATCHES "^(eshkol_|arena_|__eshkol|__repl_shared_arena|g_eshkol|g_current_exception|g_exception_handler_stack|g_lambda_registry)")
            list(APPEND _exports "${_sym}")
        endif()
    endforeach()
endforeach()

# Compiler-rt / CRT helpers that ONLY JIT-compiled code references (no host C++
# code does), so they would not otherwise be reachable through the runtime
# archives' exported namespace. They ARE defined in the final exe (pulled in by
# clang's automatic compiler-rt link), so exporting them by name is sufficient.
list(APPEND _exports "___chkstk_ms" "___chkstk")

list(REMOVE_DUPLICATES _exports)
list(SORT _exports)

set(_content "; Auto-generated by cmake/gen_runtime_def.cmake — DO NOT EDIT.\nEXPORTS\n")
foreach(_sym IN LISTS _exports)
    string(APPEND _content "    ${_sym}\n")
endforeach()

file(WRITE "${OUTPUT}" "${_content}")
list(LENGTH _exports _count)
message(STATUS "gen_runtime_def: wrote ${_count} exports to ${OUTPUT}")
