#!/usr/bin/env bash
# tests/memory/native_region_pin_diagnostic_test.sh — native/VM parity for the
# region-pin stderr note (SW-59 follow-up).
#
# BACKGROUND. Capturing a continuation inside `(with-region ...)` pins every
# region open at capture time on BOTH engines (heap_region_pin_all() in
# lib/backend/vm_core.c for the VM, eshkol_region_pin_all() in
# lib/core/runtime_regions.cpp for native): the region's arena is
# promoted/leaked rather than freed, because the continuation's saved state
# may hold interior pointers into it. The VM has always announced this once
# per process on stderr (vm_evac_pin_notice(), lib/backend/vm_region_evac.c);
# native only ever logged it through eshkol_debug(), which is silent unless
# the process log level is raised to DEBUG — so a native program that pinned a
# region gave no visible signal at all. eshkol_region_pin_notice()
# (lib/core/runtime_arena_diagnostics_hosted.cpp), called from
# region_destroy(), closes that gap: native now prints the same kind of note,
# gated by the same ESHKOL_VM_REGION_QUIET switch the VM already honors.
#
# WHAT THIS GATE PINS, on both native JIT (-r) and native AOT:
#
#   1. pin-note-jit    a program that captures a continuation inside a region
#                      prints the note on stderr under -r.
#   2. pin-note-aot    the same, compiled and run standalone.
#   3. quiet-jit       ESHKOL_VM_REGION_QUIET=1 suppresses it under -r.
#   4. quiet-aot       ...and under AOT.
#   5. no-false-note   a `with-region` program that never captures a
#                      continuation prints nothing — the note is conditioned on
#                      an actual pin, not on every region.
#   6. once-per-process the note fires at most once, even though the fixture
#                      resumes its captured continuation three times.
#   7. answers         none of the above changes what the program prints.
#
# Usage: tests/memory/native_region_pin_diagnostic_test.sh
#   BUILD_DIR env var selects the build directory (default: build).
set -u
export LC_ALL=C LC_CTYPE=C LANG=C
cd "$(dirname "$0")/../.."
REPO_ROOT="$(pwd)"

BUILD_DIR="${BUILD_DIR:-build}"
case "$BUILD_DIR" in
    /*) RUN="$BUILD_DIR/eshkol-run" ;;
    *)  RUN="$REPO_ROOT/$BUILD_DIR/eshkol-run" ;;
esac
if [ ! -x "$RUN" ]; then
    echo "native_region_pin_diagnostic_test.sh: $RUN not found — run \`cmake --build $BUILD_DIR\` first." >&2
    exit 2
fi

PIN_SRC="$REPO_ROOT/tests/continuations/region_capture_resume.esk"
if [ ! -f "$PIN_SRC" ]; then
    echo "native_region_pin_diagnostic_test.sh: $PIN_SRC not found." >&2
    exit 2
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/eshkol-native-region-pin.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT INT TERM

# The negative control: a `with-region` body that never captures a
# continuation. It must stay silent — the note is conditioned on an actual
# pin, not on `with-region` itself.
NO_PIN_SRC="$WORK/no_pin.esk"
cat > "$NO_PIN_SRC" <<'EOF'
;; generated by tests/memory/native_region_pin_diagnostic_test.sh
(with-region
  (display (+ 1 2 3))
  (newline))
EOF

NOTE_SUBSTRING="could not be reclaimed because a continuation was captured inside it"

PASS=0
FAIL=0
check() { # name condition-description result(0=ok)
    if [ "$3" -eq 0 ]; then
        echo "PASSED tests/memory/native_region_pin_diagnostic_test.sh::$1"
        PASS=$((PASS + 1))
    else
        echo "FAILED tests/memory/native_region_pin_diagnostic_test.sh::$1 — $2"
        FAIL=$((FAIL + 1))
    fi
}

echo "  Native region-pin stderr diagnostic (SW-59 follow-up)"

# ── 1/3. native JIT: the note, and its silencer ─────────────────────────────
"$RUN" -r "$PIN_SRC" >"$WORK/jit.out" 2>"$WORK/jit.err"
grep -qF "$NOTE_SUBSTRING" "$WORK/jit.err"
check pin_note_jit "native JIT did not print the region-pin note on stderr" $?

ESHKOL_VM_REGION_QUIET=1 "$RUN" -r "$PIN_SRC" >"$WORK/jit_quiet.out" 2>"$WORK/jit_quiet.err"
if grep -qF "$NOTE_SUBSTRING" "$WORK/jit_quiet.err"; then rc=1; else rc=0; fi
check quiet_jit "ESHKOL_VM_REGION_QUIET=1 did not suppress the native JIT note" $rc

# ── 2/4. native AOT: the note, and its silencer ─────────────────────────────
EXE="$WORK/region_capture_resume"
if "$RUN" -o "$EXE" "$PIN_SRC" >"$WORK/compile.out" 2>"$WORK/compile.err" && [ -x "$EXE" ]; then
    "$EXE" >"$WORK/aot.out" 2>"$WORK/aot.err"
    grep -qF "$NOTE_SUBSTRING" "$WORK/aot.err"
    check pin_note_aot "native AOT did not print the region-pin note on stderr" $?

    ESHKOL_VM_REGION_QUIET=1 "$EXE" >"$WORK/aot_quiet.out" 2>"$WORK/aot_quiet.err"
    if grep -qF "$NOTE_SUBSTRING" "$WORK/aot_quiet.err"; then rc=1; else rc=0; fi
    check quiet_aot "ESHKOL_VM_REGION_QUIET=1 did not suppress the native AOT note" $rc
else
    echo "FAILED tests/memory/native_region_pin_diagnostic_test.sh::pin_note_aot — AOT compile failed"
    echo "FAILED tests/memory/native_region_pin_diagnostic_test.sh::quiet_aot — AOT compile failed"
    FAIL=$((FAIL + 2))
fi

# ── 5. no false note for a with-region body that never pins ────────────────
"$RUN" -r "$NO_PIN_SRC" >"$WORK/nopin.out" 2>"$WORK/nopin.err"
if grep -qF "$NOTE_SUBSTRING" "$WORK/nopin.err"; then rc=1; else rc=0; fi
check no_false_note "a with-region body that never captured a continuation still printed the pin note" $rc

# ── 6. at most once per process, despite three resumes ──────────────────────
count=$(grep -cF "$NOTE_SUBSTRING" "$WORK/jit.err")
if [ "$count" -le 1 ]; then rc=0; else rc=1; fi
check once_per_process "the pin note printed $count times across three continuation resumes; expected at most once" $rc

# ── 7. none of this changes the program's answer ────────────────────────────
if [ -s "$WORK/jit.out" ] && [ -s "$WORK/jit_quiet.out" ] && \
   [ "$(cat "$WORK/jit.out")" = "$(cat "$WORK/jit_quiet.out")" ]; then
    rc=0
else
    rc=1
fi
check answers_unchanged_jit "ESHKOL_VM_REGION_QUIET changed native JIT stdout" $rc

if [ -f "$WORK/aot.out" ] && [ -f "$WORK/aot_quiet.out" ] && \
   [ "$(cat "$WORK/aot.out")" = "$(cat "$WORK/aot_quiet.out")" ] && \
   [ "$(cat "$WORK/jit.out")" = "$(cat "$WORK/aot.out")" ]; then
    rc=0
else
    rc=1
fi
check answers_unchanged_aot "the pin note (or its absence) changed native AOT stdout, or native JIT/AOT disagree" $rc

echo "  native-region-pin-diagnostic: $PASS passed, $FAIL failed"
if [ "$FAIL" -eq 0 ]; then
    echo "native_region_pin_diagnostic_test.sh: PASS"
    exit 0
fi
echo "native_region_pin_diagnostic_test.sh: FAIL"
exit 1
