#!/usr/bin/env bash
# tests/memory/vm_region_flat_rss_test.sh — the measurement half of the SW-14
# close.
#
# WHAT SW-14 WAS. `(with-region ...)` on the bytecode VM lowered to `begin`.
# The body ran, its value was returned, and the arena was never released:
# measured at the branch point on tests/memory/vm_region_growth_watchdog_test.esk,
# peak RSS was 1.503 GB WITH the wrapper and 1.504 GB without it — the same to
# within 0.06%. The form was inert, not merely weak.
#
# WHAT THIS GATE PINS. That the same fixture now holds FLAT peak RSS as its
# iteration count is swept, which is the ledger's stated close condition and the
# one claim that cannot be made by assertion. Flatness across a sweep is a
# stronger and far more portable signal than any single absolute number: a leak
# shows up as growth proportional to the sweep, whatever the host's baseline is.
#
# Four things are measured, in the order they can fail:
#
#   1. answers     the same program prints the same value with reclamation on
#                  and off. A memory change that alters a result is not a fix.
#   2. flat        16x the iteration count must not cost anywhere near 16x the
#                  memory. A linear leak would be ~16x; the allowance is 1.5x.
#   3. reclaims    at the largest sweep point, reclamation on must use
#                  materially less than reclamation off — this is the
#                  measurement the ledger requires, made at the head SHA rather
#                  than quoted.
#   4. ceiling     an absolute backstop so a host with an unusual baseline
#                  still fails loudly on unbounded growth.
#
# Exit 0 = PASS, 1 = FAIL, 2 = cannot gate.
#
# Usage: tests/memory/vm_region_flat_rss_test.sh [--ceiling-mb N] [--timeout S]
#   BUILD_DIR selects the build directory (default: build).
set -u
export LC_ALL=C LC_CTYPE=C LANG=C
cd "$(dirname "$0")/../.."
REPO_ROOT="$(pwd)"
. "$REPO_ROOT/scripts/lib/durable_work_root.sh"

BUILD_DIR="${BUILD_DIR:-build}"
case "$BUILD_DIR" in
    /*) VM="$BUILD_DIR/eshkol-vm-standalone-test" ;;
    *)  VM="$REPO_ROOT/$BUILD_DIR/eshkol-vm-standalone-test" ;;
esac
if [ ! -x "$VM" ]; then
    echo "vm_region_flat_rss_test.sh: $VM not found — run \`cmake --build $BUILD_DIR\` first." >&2
    exit 2
fi

# Measured with the evacuator: ~26-28 MB across the whole sweep. Without it the
# largest sweep point is ~3.7 GB. 120 MB separates those with wide margin and
# still leaves room for a host whose interpreter baseline is larger.
CEILING_MB=120
TIMEOUT_S=300
while [ $# -gt 0 ]; do
    case "$1" in
        --ceiling-mb) CEILING_MB="${2:-}"; shift 2 ;;
        --timeout)    TIMEOUT_S="${2:-}"; shift 2 ;;
        *) echo "vm_region_flat_rss_test.sh: unknown argument $1" >&2; exit 2 ;;
    esac
done

TIME_MODE=""
if /usr/bin/time -l true >/dev/null 2>/tmp/.eshkol_vm_flat_probe.$$ &&
   grep -q "maximum resident set size" /tmp/.eshkol_vm_flat_probe.$$; then
    TIME_MODE=bsd
elif /usr/bin/time -v true >/dev/null 2>/tmp/.eshkol_vm_flat_probe.$$ &&
     grep -q "Maximum resident set size" /tmp/.eshkol_vm_flat_probe.$$; then
    TIME_MODE=gnu
fi
rm -f /tmp/.eshkol_vm_flat_probe.$$
if [ -z "$TIME_MODE" ]; then
    echo "vm_region_flat_rss_test.sh: no usable /usr/bin/time; cannot gate." >&2
    exit 2
fi

if eshkol_durable_enabled; then
    WORK="$(eshkol_durable_prepare_dir vm-region-flat-rss)" || exit $?
else
    WORK="$(mktemp -d "${TMPDIR:-/tmp}/eshkol-vm-region-flat.XXXXXX")"
    trap 'rm -rf "$WORK"' EXIT INT TERM
fi

PASS=0
FAIL=0
check() {
    if [ "$3" -eq 0 ]; then
        echo "PASSED tests/memory/vm_region_flat_rss_test.sh::$1"
        PASS=$((PASS + 1))
    else
        echo "FAILED tests/memory/vm_region_flat_rss_test.sh::$1 — $2"
        FAIL=$((FAIL + 1))
    fi
}

# The shape the memory model documents as the way to keep a resident loop flat:
# a per-iteration region around a body that allocates and then drops everything
# it allocated. Parameterised by iteration count so flatness can be SWEPT.
emit_fixture() { # iterations wrap(1|0) -> path
    n="$1"; wrap="$2"; path="$WORK/tick_${n}_${wrap}.esk"
    if [ "$wrap" -eq 1 ]; then open="(with-region ('step 65536)"; close=")"
    else                       open="(begin";                     close=")"
    fi
    cat > "$path" <<EOF
;; generated by tests/memory/vm_region_flat_rss_test.sh
(define (scratch-step k)
  $open
    (let loop ((i 0) (acc '()))
      (if (< i 120)
          (loop (+ i 1) (cons (* i k) acc))
          (length acc)))$close)
(define (drive n total)
  (if (= n 0) total (drive (- n 1) (+ total (scratch-step n)))))
(display (drive $n 0))
(newline)
EOF
    echo "$path"
}

RSS_MB=0
RUN_RC=0
ANSWER=""
timed_run() { # tag src env...
    tag="$1"; src="$2"; shift 2
    if [ "$TIME_MODE" = bsd ]; then
        env "$@" ESHKOL_VM_NO_DISASM=1 ESHKOL_VM_HEAP_BUDGET_MB=0 ESHKOL_VM_REGION_QUIET=1 \
            /usr/bin/time -l perl -e 'my $s=shift; alarm $s; exec @ARGV; die "exec failed: $!\n"' \
            "$TIMEOUT_S" "$VM" "$src" >"$WORK/$tag.out" 2>"$WORK/$tag.time"
        RUN_RC=$?
        RSS_MB=$(awk '/maximum resident set size/{printf "%d", $1/1048576}' "$WORK/$tag.time")
    else
        env "$@" ESHKOL_VM_NO_DISASM=1 ESHKOL_VM_HEAP_BUDGET_MB=0 ESHKOL_VM_REGION_QUIET=1 \
            /usr/bin/time -v perl -e 'my $s=shift; alarm $s; exec @ARGV; die "exec failed: $!\n"' \
            "$TIMEOUT_S" "$VM" "$src" >"$WORK/$tag.out" 2>"$WORK/$tag.time"
        RUN_RC=$?
        RSS_MB=$(awk -F: '/Maximum resident set size/{printf "%d", $2/1024}' "$WORK/$tag.time")
    fi
    [ -n "$RSS_MB" ] || RSS_MB=0
    # The program's own answer is the one line that is nothing but digits;
    # tr-ing the whole stream would also pick up digits from the compile banner's
    # file path, which differs between the wrapped and unwrapped fixtures.
    ANSWER=$(grep -E '^[0-9]+$' "$WORK/$tag.out" | tail -1)
}

echo "  SW-14 close: VM with-region flat-RSS sweep (ceiling ${CEILING_MB} MB, time=$TIME_MODE)"

STEPS="1000 4000 16000"
FIRST_RSS=""
LAST_RSS=""
SWEEP_RC=0
for n in $STEPS; do
    src="$(emit_fixture "$n" 1)"
    timed_run "sweep_$n" "$src"
    [ "$RUN_RC" -eq 0 ] || SWEEP_RC=1
    echo "    iterations=$n  peak RSS=${RSS_MB} MB  answer=${ANSWER}"
    [ -n "$FIRST_RSS" ] || FIRST_RSS="$RSS_MB"
    LAST_RSS="$RSS_MB"
done
check sweep_runs "a sweep point exited nonzero or timed out" $SWEEP_RC

# 16x the work must not cost 16x the memory. 1.5x covers allocator and OS
# variance; a per-iteration leak of the pre-Stage-1 kind is ~16x.
LIMIT=$(( FIRST_RSS * 15 / 10 ))
[ "$LIMIT" -gt 0 ] || LIMIT=1
if [ "$LAST_RSS" -gt "$LIMIT" ]; then rc=1; else rc=0; fi
check flat \
  "peak RSS grows with iteration count (${FIRST_RSS} MB at 1000 -> ${LAST_RSS} MB at 16000, allowance ${LIMIT} MB): with-region is not reclaiming" $rc

if [ "$LAST_RSS" -gt "$CEILING_MB" ]; then rc=1; else rc=0; fi
check ceiling "peak RSS ${LAST_RSS} MB at 16000 iterations exceeds ${CEILING_MB} MB" $rc

# ── The comparison the ledger asks for: reclamation on vs off, same fixture ──
BIG=16000
src_on="$(emit_fixture "$BIG" 1)"
timed_run recl_on "$src_on"
ON_RSS=$RSS_MB; ON_ANS=$ANSWER; ON_RC=$RUN_RC
timed_run recl_off "$src_on" ESHKOL_VM_REGION_EVAC=0
OFF_RSS=$RSS_MB; OFF_ANS=$ANSWER; OFF_RC=$RUN_RC

if [ "$ON_RC" -eq 0 ] && [ "$OFF_RC" -eq 0 ]; then rc=0; else rc=1; fi
check comparison_runs "the on/off comparison runs did not both succeed" $rc

if [ -n "$ON_ANS" ] && [ "$ON_ANS" = "$OFF_ANS" ]; then rc=0; else rc=1; fi
check answers_unchanged \
  "reclamation changed the program's output ('$ON_ANS' with, '$OFF_ANS' without)" $rc

# At the branch point these two were IDENTICAL (1.503 GB vs 1.504 GB) because
# the form reclaimed nothing. Requiring a 2x separation is what turns "it
# reclaims" into a measurement.
HALF_OFF=$(( OFF_RSS / 2 ))
if [ "$ON_RSS" -lt "$HALF_OFF" ]; then rc=0; else rc=1; fi
check reclaims \
  "with-region did not measurably reclaim: ${ON_RSS} MB with the evacuator vs ${OFF_RSS} MB without, at ${BIG} iterations" $rc

# ── Unwrapped control: the same body with `begin` in place of `with-region` ──
# Reported, never gated. It is the legibility half — it shows that the win comes
# from the region form and not from an unrelated change in the interpreter.
src_plain="$(emit_fixture "$BIG" 0)"
timed_run plain "$src_plain"
echo "    unwrapped control (begin instead of with-region): peak RSS=${RSS_MB} MB, answer=${ANSWER}"

echo "  vm-region-flat-rss: $PASS passed, $FAIL failed"
echo "  at ${BIG} iterations: with-region+evacuator=${ON_RSS} MB, evacuator disabled=${OFF_RSS} MB"
if [ "$FAIL" -eq 0 ]; then
    echo "vm_region_flat_rss_test.sh: PASS"
    exit 0
fi
echo "vm_region_flat_rss_test.sh: FAIL"
exit 1
