#!/usr/bin/env bash
# tests/memory/vm_region_growth_watchdog_test.sh — the VM heap growth watchdog,
# after the SW-14 close.
#
# WHAT CHANGED. This gate was written when the bytecode VM had no heap
# reclamation of any kind: `(with-region ...)` lowered to `begin`, and the gate
# pinned the two INTERIM guards that at least made the resulting growth loud —
# a one-time note at the region form, and a diagnostic when the arena crossed a
# budget. The Stage-1 region evacuator (lib/backend/vm_region_evac.c) removed
# the premise of the first guard: `with-region` now reclaims, so a note saying
# it does not would be a false statement, and the fixture no longer crosses any
# reasonable budget. Reclamation itself is measured by
# tests/memory/vm_region_flat_rss_test.sh; coverage by
# tests/memory/vm_region_evac_subtype_coverage_test.sh.
#
# WHAT THIS GATE PINS NOW. The watchdog survived the close because it is still
# needed and still true: OUTSIDE a region the VM heap grows monotonically, so a
# workload that never opens a region can still exhaust the host, and it should
# say so. Six behaviours:
#
#   1. no-false-note  a `with-region` program does NOT claim it reclaims
#                     nothing — the claim the evacuator retired.
#   2. handle-note    the region HANDLE surface (region-open / region-close),
#                     which is still bookkeeping-only on the VM, DOES announce
#                     that boundary. Stage-2 retires this line, not this gate.
#   3. note-silenced  ESHKOL_VM_REGION_QUIET=1 suppresses it, so it stays a
#                     diagnostic rather than unavoidable noise.
#   4. loud-growth    unbounded growth with no region around it still crosses
#                     ESHKOL_VM_HEAP_BUDGET_MB and names the size, the budget
#                     and the cause.
#   5. fail-closed    ESHKOL_VM_HEAP_BUDGET_FATAL=1 turns that into a nonzero
#                     exit, so a lane can gate on it; and
#                     ESHKOL_VM_HEAP_BUDGET_MB=0 disables it.
#   6. quiet-when-reclaiming
#                     the SAME allocation volume, wrapped in `with-region`, does
#                     NOT trip the budget — the watchdog no longer fires for a
#                     loop that gets its memory back.
#   7. answers        none of the above changes what the program prints.
#
# Usage: tests/memory/vm_region_growth_watchdog_test.sh
#   BUILD_DIR env var selects the build directory (default: build).
set -u
export LC_ALL=C LC_CTYPE=C LANG=C
cd "$(dirname "$0")/../.."
REPO_ROOT="$(pwd)"
. "$REPO_ROOT/scripts/lib/durable_work_root.sh"

BUILD_DIR="${BUILD_DIR:-build}"
case "$BUILD_DIR" in
    /*) VM="$BUILD_DIR/eshkol-vm-standalone-test" ;;
    *)  VM="$REPO_ROOT/$BUILD_DIR/eshkol-vm-standalone-test" ;;
esac
if [ ! -x "$VM" ]; then
    echo "vm_region_growth_watchdog_test.sh: $VM not found — run \`cmake --build $BUILD_DIR\` first." >&2
    exit 2
fi

SRC="$REPO_ROOT/tests/memory/vm_region_growth_watchdog_test.esk"
if [ ! -f "$SRC" ]; then
    echo "vm_region_growth_watchdog_test.sh: $SRC not found." >&2
    exit 2
fi

# Same convention as the other memory gates (define_loop_flat_rss_aot_test.sh):
# an ephemeral working directory, removed by the trap on every exit path. Total
# footprint is a few KB of captured stdout/stderr. Durable release runs retain
# those captures under their deterministic gate child instead.
if eshkol_durable_enabled; then
    WORK="$(eshkol_durable_prepare_dir vm-region-growth-watchdog)" || exit $?
else
    WORK="$(mktemp -d "${TMPDIR:-/tmp}/eshkol-vm-region-watchdog.XXXXXX")"
    trap 'rm -rf "$WORK"' EXIT INT TERM
fi

# The unbounded-growth control: the SAME allocation volume as the region
# fixture, with no region around it. This is the workload the watchdog exists
# for now — nothing in the language is asking for the memory back.
UNBOUNDED="$WORK/unbounded.esk"
cat > "$UNBOUNDED" <<'EOF'
;; generated by tests/memory/vm_region_growth_watchdog_test.sh
;; Same shape and volume as vm_region_growth_watchdog_test.esk, minus the
;; region: allocation the VM has no mechanism to reclaim.
(define (scratch-step k)
  (let loop ((i 0) (acc '()))
    (if (< i 120)
        (loop (+ i 1) (cons (* i k) acc))
        (length acc))))
(define (drive n total)
  (if (= n 0) total (drive (- n 1) (+ total (scratch-step n)))))
(display (drive 4000 0))
(newline)
EOF

# The handle-surface control: `region-open` / `region-close` are still
# bookkeeping-only on the VM (Stage-2), and still say so.
HANDLE="$WORK/handle.esk"
cat > "$HANDLE" <<'EOF'
;; generated by tests/memory/vm_region_growth_watchdog_test.sh
(define h (region-open 'scratch 4096))
(display (region-close h (list 1 2 3)))
(newline)
EOF

PASS=0
FAIL=0
check() { # name condition-description result(0=ok)
    if [ "$3" -eq 0 ]; then
        echo "PASSED tests/memory/vm_region_growth_watchdog_test.sh::$1"
        PASS=$((PASS + 1))
    else
        echo "FAILED tests/memory/vm_region_growth_watchdog_test.sh::$1 — $2"
        FAIL=$((FAIL + 1))
    fi
}

# Every compared run sets ESHKOL_VM_NO_DISASM=1 so stdout is the program's own
# output rather than the VM's disassembly dump; reduce it to the digits printed.
export ESHKOL_VM_NO_DISASM=1
answer_of() { grep -E '^[0-9]+$' "$1" | tail -1; }

echo "  VM heap growth watchdog (post-SW-14-close)"

# ── 1. the retired claim ────────────────────────────────────────────────────
ESHKOL_VM_HEAP_BUDGET_MB=0 "$VM" "$SRC" >"$WORK/note.out" 2>"$WORK/note.err"
if grep -q "reclaim no memory on the bytecode VM" "$WORK/note.err"; then rc=1; else rc=0; fi
check no_false_note \
  "a with-region program still claims the VM reclaims nothing — the Stage-1 evacuator made that claim false" $rc

# ── 2/3. the handle-surface note, and its silencer ──────────────────────────
ESHKOL_VM_HEAP_BUDGET_MB=0 "$VM" "$HANDLE" >"$WORK/handle.out" 2>"$WORK/handle.err"
grep -q "bookkeeping-only on the bytecode VM" "$WORK/handle.err"
check handle_note \
  "region-open/region-close did not announce that a close reclaims no VM heap (Stage-2 boundary)" $?

ESHKOL_VM_HEAP_BUDGET_MB=0 ESHKOL_VM_REGION_QUIET=1 \
    "$VM" "$HANDLE" >"$WORK/quiet.out" 2>"$WORK/quiet.err"
if grep -q "bookkeeping-only on the bytecode VM" "$WORK/quiet.err"; then rc=1; else rc=0; fi
check note_silenced "ESHKOL_VM_REGION_QUIET=1 did not suppress the handle note" $rc

# ── 4. the growth watchdog still speaks for genuinely unbounded growth ──────
ESHKOL_VM_HEAP_BUDGET_MB=64 "$VM" "$UNBOUNDED" >"$WORK/budget.out" 2>"$WORK/budget.err"
BUDGET_RC=$?
grep -q "heap budget exceeded" "$WORK/budget.err"
check loud_growth "crossing ESHKOL_VM_HEAP_BUDGET_MB produced no diagnostic" $?

grep -q "with-region" "$WORK/budget.err"
check names_remedy "the budget diagnostic does not name the mechanism that reclaims" $?

if [ "$BUDGET_RC" -eq 0 ]; then rc=0; else rc=1; fi
check advisory_by_default "the budget diagnostic is fatal without ESHKOL_VM_HEAP_BUDGET_FATAL" $rc

# ── 5. fail-closed, and off ─────────────────────────────────────────────────
ESHKOL_VM_HEAP_BUDGET_MB=64 ESHKOL_VM_HEAP_BUDGET_FATAL=1 \
    "$VM" "$UNBOUNDED" >"$WORK/fatal.out" 2>"$WORK/fatal.err"
FATAL_RC=$?
if [ "$FATAL_RC" -ne 0 ]; then rc=0; else rc=1; fi
check fail_closed "ESHKOL_VM_HEAP_BUDGET_FATAL=1 still exited 0 past the budget" $rc

ESHKOL_VM_HEAP_BUDGET_MB=0 "$VM" "$UNBOUNDED" >"$WORK/off.out" 2>"$WORK/off.err"
if grep -q "heap budget exceeded" "$WORK/off.err"; then rc=1; else rc=0; fi
check budget_off "ESHKOL_VM_HEAP_BUDGET_MB=0 did not disable the watchdog" $rc

# ── 6. and stays quiet for the loop that now gets its memory back ───────────
ESHKOL_VM_HEAP_BUDGET_MB=64 ESHKOL_VM_HEAP_BUDGET_FATAL=1 \
    "$VM" "$SRC" >"$WORK/region.out" 2>"$WORK/region.err"
REGION_RC=$?
if [ "$REGION_RC" -eq 0 ] && ! grep -q "heap budget exceeded" "$WORK/region.err"; then
    rc=0
else
    rc=1
fi
check quiet_when_reclaiming \
  "the watchdog still fires for a with-region loop that reclaims — the same volume that trips it unwrapped must not trip it wrapped" $rc

# ── 7. none of this changes an answer ───────────────────────────────────────
A_OFF="$(answer_of "$WORK/note.out")"
A_REGION="$(answer_of "$WORK/region.out")"
A_UNBOUNDED="$(answer_of "$WORK/budget.out")"
if [ -n "$A_OFF" ] && [ "$A_OFF" = "$A_REGION" ] && [ "$A_OFF" = "$A_UNBOUNDED" ]; then
    rc=0
else
    rc=1
fi
check answers_unchanged \
  "the region form, the watchdog, or the evacuator changed the program's output ('$A_OFF' / '$A_REGION' / '$A_UNBOUNDED')" $rc

echo "  vm-region-watchdog: $PASS passed, $FAIL failed"
if [ "$FAIL" -eq 0 ]; then
    echo "vm_region_growth_watchdog_test.sh: PASS"
    exit 0
fi
echo "vm_region_growth_watchdog_test.sh: FAIL"
exit 1
